export const imageToCartoonContent = {
  en: {
    heroTag: "Image to Cartoon",
    heroSubtitle:
      "Turn any photo into a cel-shaded cartoon — right in your browser. Posterized colors, hand-drawn outlines, live sliders. Download as PNG. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Cartoon", label: "Effect" },
      { value: "100%", label: "Private" },
      { value: "Live", label: "Preview" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Photos never leave your device." },
      { emoji: "🎨", title: "Cel-shaded look", text: "Posterize + Sobel outline algorithm." },
      { emoji: "🎚️", title: "3 live sliders", text: "Levels, edge strength, smoothness." },
      { emoji: "⚡", title: "Instant", text: "Renders in under a second." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
      { emoji: "🖼️", title: "PNG export", text: "High-res, ready to share." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Image to Cartoon converts a photo into a cel-shaded illustration. It smooths the photo to remove noise, posterizes each RGB channel into flat bands, then runs Sobel edge detection to find contours and darkens those contours. The result looks like a hand-drawn cartoon character or an anime still frame — without opening Photoshop." },
      { emoji: "📄", title: "When you need it", text: "Turn a selfie into a cartoon avatar. Make a headshot illustration for a profile picture. Create stylized illustrations for a blog, presentation, or social media post. Give a client a fun preview. Perfect for portraits, pets, and any photo with clear subjects." },
      { emoji: "⚡", title: "How it works", text: "Everything uses the Canvas API and pure pixel math. First a two-pass sliding-window blur softens the image — this makes the posterization bands look flat instead of noisy. Then each RGB channel is quantized to a fixed number of levels (4–16). Finally, a Sobel operator detects edges on the grayscale copy, and those edges are multiplied into the posterized image so contours become dark outlines." },
      { emoji: "🔐", title: "Your photos stay with you", text: "There is no server. No accounts. No analytics. Your photos — portraits, IDs, private shots — stay entirely inside your browser. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to turn a photo into a cartoon",
    howTo: [
      { step: 1, title: "Drop your photo", description: "Drag a JPG, PNG, or WebP into the upload area, or click to browse. Up to 25 MB." },
      { step: 2, title: "Adjust the sliders", description: "Levels control color flatness, Edge strength controls outline darkness, Smoothness controls noise reduction." },
      { step: 3, title: "Watch the preview", description: "The cartoon updates live as you move the sliders — no button required." },
      { step: 4, title: "Download PNG", description: "Click Download to save the cartoon as a PNG image." },
    ],
    featuresTitle: "Built for real cartoon output",
    features: [
      { emoji: "🎨", title: "Cel-shaded look", description: "Posterization + Sobel outlines produce the anime/cartoon aesthetic." },
      { emoji: "🎚️", title: "3 live sliders", description: "Levels, edge strength, and smoothness adjust in real time." },
      { emoji: "🔒", title: "Zero uploads", description: "Every pixel stays inside your browser." },
      { emoji: "⚡", title: "Fast", description: "Optimized blur and Sobel run in under a second on most photos." },
      { emoji: "📐", title: "Up to 1600px", description: "Large photos auto-downscale to keep processing smooth." },
      { emoji: "💾", title: "Any size", description: "Uploads up to 25 MB. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my photo uploaded?", answer: "No. Everything happens in your browser using the Canvas API. Your photo never leaves your device." },
      { question: "What does the Levels slider do?", answer: "It controls how many color bands each channel is quantized into. Lower levels (4–6) give a flat, poster-like cartoon. Higher levels (12–16) preserve more detail but look less cartoon-like." },
      { question: "What does the Edge strength slider do?", answer: "It controls how dark the outlines are. 0 = no outlines (just flat colors), 2 = very bold, comic-book style contours." },
      { question: "What does the Smoothness slider do?", answer: "It controls the blur applied before posterization. Higher values remove noise and give cleaner flat regions, but can blur away fine detail like freckles or eye highlights." },
      { question: "Why does my photo look less like a cartoon?", answer: "Photos with strong contrast, clear subjects, and simple backgrounds work best. Very busy scenes produce noisy edges — try increasing Smoothness or lowering Levels." },
      { question: "What's the maximum image size?", answer: "Uploads up to 25 MB. Images larger than 1600px on their long edge are automatically downscaled before processing." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your photo is processed entirely inside your browser using the Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ থেকে কার্টুন",
    heroSubtitle:
      "যেকোনো ছবিকে cel-shaded কার্টুনে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। Posterized রঙ, হাতে-আঁকা outline, লাইভ স্লাইডার। PNG ডাউনলোড।",
    heroStats: [
      { value: "কার্টুন", label: "ইফেক্ট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "লাইভ", label: "Preview" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ছবি কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "Cel-shaded look", text: "Posterize + Sobel outline অ্যালগরিদম।" },
      { emoji: "🎚️", title: "৩ লাইভ স্লাইডার", text: "Levels, edge strength, smoothness।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", text: "সেকেন্ডের কমে render হয়।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "🖼️", title: "PNG export", text: "হাই-রেজ, শেয়ার-ready।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Image to Cartoon একটি ছবিকে cel-shaded illustration-এ রূপান্তর করে। এটি ছবিকে smooth করে noise সরায়, প্রতিটি RGB channel-কে flat band-এ posterize করে, তারপর Sobel edge detection চালিয়ে contour খুঁজে বের করে এবং সেই contour গাঢ় করে। ফলাফল হাতে-আঁকা কার্টুন বা anime still frame-এর মতো — Photoshop খোলা ছাড়াই।" },
      { emoji: "📄", title: "কখন দরকার", text: "Selfie-কে cartoon avatar বানানো। Profile picture-এর জন্য headshot illustration। ব্লগ, presentation বা সোশ্যাল মিডিয়া পোস্টে stylized illustration। ক্লায়েন্টকে fun preview দেওয়া। Portrait, পেট এবং পরিষ্কার subject সহ যেকোনো ছবির জন্য perfect।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "সবকিছু Canvas API ও pure pixel math। প্রথমে two-pass sliding-window blur ছবিকে soften করে — যাতে posterization band flat দেখায়, noisy নয়। তারপর প্রতিটি RGB channel নির্দিষ্ট সংখ্যক level-এ quantize করা হয় (৪–১৬)। শেষে Sobel operator grayscale copy-তে edge detect করে, এবং সেই edge posterized ছবিতে multiply করা হয় যাতে contour গাঢ় outline হয়।" },
      { emoji: "🔐", title: "আপনার ছবি আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। আপনার ছবি — পোর্ট্রেট, আইডি, ব্যক্তিগত ছবি — সম্পূর্ণ আপনার ব্রাউজারেই থাকে।" },
    ],
    howToTitle: "ছবিকে কার্টুনে কীভাবে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "ছবি দিন", description: "JPG, PNG বা WebP ড্র্যাগ করুন বা ক্লিক করুন। ২৫ MB পর্যন্ত।" },
      { step: 2, title: "স্লাইডার ঠিক করুন", description: "Levels রঙের flatness নিয়ন্ত্রণ করে, Edge strength outline-এর গাঢ়তা, Smoothness noise কমানো।" },
      { step: 3, title: "Preview দেখুন", description: "স্লাইডার সরানোর সাথে সাথে cartoon লাইভ আপডেট হয়।" },
      { step: 4, title: "PNG ডাউনলোড", description: "Download চেপে cartoon PNG হিসেবে সেভ করুন।" },
    ],
    featuresTitle: "প্রকৃত কার্টুন আউটপুটের জন্য",
    features: [
      { emoji: "🎨", title: "Cel-shaded look", description: "Posterization + Sobel outline anime/cartoon aesthetic দেয়।" },
      { emoji: "🎚️", title: "৩ লাইভ স্লাইডার", description: "Levels, edge strength, smoothness রিয়েল-টাইমে ঠিক হয়।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "প্রতিটি pixel আপনার ব্রাউজারেই থাকে।" },
      { emoji: "⚡", title: "দ্রুত", description: "Optimized blur ও Sobel বেশিরভাগ ছবিতে সেকেন্ডের কমে।" },
      { emoji: "📐", title: "১৬০০px পর্যন্ত", description: "বড় ছবি automatically downscale হয়।" },
      { emoji: "💾", title: "যেকোনো সাইজ", description: "২৫ MB পর্যন্ত upload।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ছবি কি আপলোড হয়?", answer: "না। Canvas API দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "Levels স্লাইডার কী করে?", answer: "প্রতিটি channel কতগুলো color band-এ quantize হবে তা নিয়ন্ত্রণ করে। কম levels (৪–৬) flat poster-like cartoon দেয়। বেশি levels (১২–১৬) বেশি detail রাখে কিন্তু cartoon feel কম হয়।" },
      { question: "Edge strength স্লাইডার কী করে?", answer: "Outline-এর গাঢ়তা নিয়ন্ত্রণ করে। 0 = outline নেই (শুধু flat রঙ), 2 = খুব bold comic-book contour।" },
      { question: "Smoothness স্লাইডার কী করে?", answer: "Posterization-এর আগে কতটা blur হবে তা নিয়ন্ত্রণ করে। বেশি মান noise সরিয়ে পরিষ্কার flat region দেয়, কিন্তু freckle বা eye highlight-এর মতো সূক্ষ্ম detail blur করতে পারে।" },
      { question: "আমার ছবি কম cartoon দেখায় কেন?", answer: "Strong contrast, পরিষ্কার subject ও simple background সবচেয়ে ভালো কাজ করে। খুব busy scene noisy edge দেয় — Smoothness বাড়ান বা Levels কমান।" },
      { question: "সর্বোচ্চ ছবি সাইজ কত?", answer: "২৫ MB পর্যন্ত। ১৬০০px-এর বড় ছবি automatically downscale হয়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageToCartoonContent = typeof imageToCartoonContent;
