export const webpToPngContent = {
  en: {
    heroTag: "Image Converter",
    heroSubtitle:
      "Convert WebP images to PNG format instantly in your browser. Get lossless output with full transparency support — perfect for logos, icons, and graphics that need to be edited later. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "Lossless", label: "Output" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device. Zero uploads." },
      { emoji: "⚡", title: "Instant conversion", text: "Runs in your browser — no server wait." },
      { emoji: "📦", title: "Batch support", text: "Convert multiple WebP files at once." },
      { emoji: "🎨", title: "Lossless quality", text: "Every pixel preserved exactly." },
      { emoji: "✨", title: "Transparency kept", text: "Alpha channels preserved perfectly." },
      { emoji: "💾", title: "Download anytime", text: "Individual or bulk download with one click." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "WebP to PNG Converter takes your WebP images and re-encodes them as lossless PNG files. It reads the WebP locally in your browser, draws it onto an off-screen canvas at full resolution, and exports the result as a PNG blob — preserving any transparency. No byte leaves your device. Drop in one file or a hundred — the tool converts them one by one and shows both sizes side by side." },
      { emoji: "🎨", icon: "target", title: "Why PNG?", text: "PNG is a lossless format that supports full transparency. Unlike JPG, PNG does not introduce compression artefacts every time you re-save — making it ideal for graphics, logos, and images that will be edited multiple times. PNG is universally supported and preserves alpha channels, which matters for icons, cutout graphics, and any asset that needs a transparent background." },
      { emoji: "⚡", icon: "printer", title: "How the conversion works", text: "The tool uses the browser's built-in HTML5 Canvas API. When you drop a WebP, the browser decodes it into raw pixel data. The canvas re-draws those pixels one by one, then exports the result as a PNG blob using a lossless encoder. Because both decoding and encoding happen inside your browser, no network traffic is involved — conversion typically takes under a second per file." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript inside the page you are looking at. When you close the tab, every trace of your files is gone from memory. This makes the tool suitable for confidential logos, client work, and anything you would not want a third party to see." },
    ],
    howToTitle: "How to convert WebP to PNG",
    howTo: [
      { step: 1, title: "Drop your WebP files", description: "Drag and drop one or more WebP files into the upload area, or click to browse. Files up to 50 MB each are supported." },
      { step: 2, title: "Wait a moment", description: "The tool converts each file in sequence. Conversion happens on your device, so it usually takes less than a second per file." },
      { step: 3, title: "Review the results", description: "Each converted file appears with the original name, original size, and the new PNG size. Transparency is preserved." },
      { step: 4, title: "Download individually or all at once", description: "Click Download on any single file, or use Download All to grab every converted PNG in one go." },
    ],
    featuresTitle: "Built for real conversions",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "The file is decoded and re-encoded entirely in your browser. Nothing travels over the network." },
      { emoji: "⚡", title: "Instant results", description: "No queue, no waiting for a server. Every file converts in under a second on modern hardware." },
      { emoji: "📦", title: "Batch processing", description: "Drop multiple WebP files at once and convert them all in a single session." },
      { emoji: "🎨", title: "Lossless quality", description: "PNG encoding is lossless — every pixel from the WebP is preserved exactly." },
      { emoji: "✨", title: "Transparency preserved", description: "WebP's alpha channels are kept intact in the PNG output." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each are accepted. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser. Your files never leave your device." },
      { question: "Will the quality change?", answer: "No. PNG is lossless, so every pixel from the original WebP is preserved exactly." },
      { question: "Does the PNG keep transparency?", answer: "Yes. WebP's transparency is fully preserved in the PNG output." },
      { question: "Can I convert multiple files at once?", answer: "Yes. Drop as many WebP files as you want and they will all be converted. Use Download All to save every file in one click." },
      { question: "Is there a file size limit?", answer: "Each file can be up to 50 MB. There is no limit on the number of files you convert in one session." },
      { question: "Will the PNG be bigger than the WebP?", answer: "Usually yes — PNG uses lossless compression which is less efficient than WebP. This is expected and means no quality was lost." },
      { question: "Can I convert PNG back to WebP?", answer: "Yes — we also have a PNG to WebP converter. It works the same way in reverse." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ কনভার্টার",
    heroSubtitle:
      "WebP ছবি PNG ফরম্যাটে সাথে সাথে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। lossless আউটপুট এবং সম্পূর্ণ স্বচ্ছতা সাপোর্ট — লোগো, আইকন এবং পরে এডিট করার জন্য আদর্শ।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "লসলেস", label: "আউটপুট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক রূপান্তর", text: "ব্রাউজারেই চলে — সার্ভারের অপেক্ষা নেই।" },
      { emoji: "📦", title: "ব্যাচ সাপোর্ট", text: "একাধিক WebP একসাথে রূপান্তর করুন।" },
      { emoji: "🎨", title: "লসলেস কোয়ালিটি", text: "প্রতিটি পিক্সেল হুবহু সংরক্ষিত।" },
      { emoji: "✨", title: "স্বচ্ছতা সংরক্ষিত", text: "Alpha চ্যানেল নিখুঁতভাবে সংরক্ষিত।" },
      { emoji: "💾", title: "যেকোনো সময় ডাউনলোড", text: "এক ক্লিকে আলাদা বা সব একসাথে।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "WebP থেকে PNG কনভার্টার আপনার WebP ছবিগুলোকে lossless PNG ফাইলে রূপান্তর করে। এটি WebP ফাইলটি আপনার ব্রাউজারেই পড়ে, সম্পূর্ণ রেজোলিউশনে একটি off-screen ক্যানভাসে আঁকে এবং ফলাফলটি PNG হিসেবে এক্সপোর্ট করে — স্বচ্ছতা সংরক্ষণ করে। একটি বাইটও আপনার ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", icon: "target", title: "কেন PNG?", text: "PNG একটি lossless ফরম্যাট যা সম্পূর্ণ স্বচ্ছতা সাপোর্ট করে। JPG-এর বিপরীতে PNG প্রতিবার re-save করার সময় কোনো কম্প্রেশন আর্টিফ্যাক্ট তৈরি করে না — তাই গ্রাফিক্স, লোগো এবং বারবার এডিট করা ছবির জন্য আদর্শ।" },
      { emoji: "⚡", icon: "printer", title: "কনভার্সন কীভাবে কাজ করে", text: "টুলটি ব্রাউজারের HTML5 Canvas API ব্যবহার করে। WebP ড্রপ করলে ব্রাউজার সেটি raw pixel data-তে ডিকোড করে। ক্যানভাস পিক্সেলগুলো এক এক করে আঁকে, তারপর lossless encoder দিয়ে PNG হিসেবে এক্সপোর্ট করে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই আপনার ফাইলের সব চিহ্ন মেমরি থেকে মুছে যায়।" },
    ],
    howToTitle: "WebP কীভাবে PNG-তে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "আপনার WebP ফাইল দিন", description: "এক বা একাধিক WebP ফাইল upload এলাকায় ড্র্যাগ করে আনুন, বা ক্লিক করে ব্রাউজ করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "একটু অপেক্ষা করুন", description: "টুলটি একটার পর একটা ফাইল কনভার্ট করে। সাধারণত প্রতি ফাইল এক সেকেন্ডেরও কম সময় লাগে।" },
      { step: 3, title: "ফলাফল দেখুন", description: "প্রতিটি কনভার্টেড ফাইল তালিকায় দেখা যায় — মূল সাইজ ও নতুন PNG সাইজ সহ। স্বচ্ছতা সংরক্ষিত থাকে।" },
      { step: 4, title: "আলাদা বা সব একসাথে ডাউনলোড", description: "যেকোনো ফাইলে Download চাপুন, বা Download All দিয়ে সব PNG একবারে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত কনভার্সনের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল ডিকোড ও রি-এনকোড সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "তাৎক্ষণিক ফলাফল", description: "আধুনিক হার্ডওয়্যারে প্রতি ফাইল এক সেকেন্ডেরও কমে।" },
      { emoji: "📦", title: "ব্যাচ প্রসেসিং", description: "একাধিক WebP একবারে দিন এবং একটি সেশনেই সব কনভার্ট করুন।" },
      { emoji: "🎨", title: "লসলেস কোয়ালিটি", description: "PNG এনকোডিং lossless — WebP-এর প্রতিটি পিক্সেল হুবহু সংরক্ষিত।" },
      { emoji: "✨", title: "স্বচ্ছতা সংরক্ষিত", description: "WebP-এর alpha চ্যানেল PNG আউটপুটে অটুট থাকে।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত। কোনো signup নেই, ওয়াটারমার্ক নেই।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই, লুকানো সাইজ লিমিট নেই।" },
      { question: "আমার ফাইল কি সার্ভারে আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই হয়। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "কোয়ালিটি পরিবর্তন হবে?", answer: "না। PNG lossless, তাই মূল WebP-এর প্রতিটি পিক্সেল হুবহু সংরক্ষিত।" },
      { question: "PNG কি স্বচ্ছতা সংরক্ষণ করে?", answer: "হ্যাঁ। WebP-এর স্বচ্ছতা সম্পূর্ণভাবে PNG আউটপুটে সংরক্ষিত থাকে।" },
      { question: "একসাথে একাধিক ফাইল কনভার্ট করা যায়?", answer: "হ্যাঁ। যত চান WebP ড্রপ করুন, সব কনভার্ট হবে।" },
      { question: "ফাইল সাইজের লিমিট আছে?", answer: "প্রতি ফাইল ৫০ MB পর্যন্ত। এক সেশনে ফাইল সংখ্যার সীমা নেই।" },
      { question: "PNG কি WebP-এর চেয়ে বড় হবে?", answer: "সাধারণত হ্যাঁ — PNG lossless কম্প্রেশন ব্যবহার করে যা WebP-এর চেয়ে কম efficient। এটাই প্রত্যাশিত এবং কোনো কোয়ালিটি লস হয়নি।" },
      { question: "PNG থেকে WebP-তে কনভার্ট করা যায়?", answer: "হ্যাঁ — আমাদের PNG to WebP কনভার্টারও আছে। উল্টো পথে একইভাবে কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type WebpToPngContent = typeof webpToPngContent;
