export const imageToPdfContent = {
  en: {
    heroTag: "Image to PDF",
    heroSubtitle:
      "Combine JPG, PNG, and WebP images into a single PDF document right in your browser. Drag, reorder, pick A4 or Letter, set orientation and margins, and download — no uploads, no servers, no accounts.",
    heroStats: [
      { value: "3 formats", label: "JPG · PNG · WebP" },
      { value: "100%", label: "Private" },
      { value: "A4/Letter", label: "Page size" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "🖼️", title: "Mixed formats", text: "JPG, PNG, and WebP — all in one PDF." },
      { emoji: "📄", title: "Multi-page", text: "Combine dozens of images into one PDF." },
      { emoji: "🔀", title: "Reorder pages", text: "Move pages up or down before export." },
      { emoji: "📐", title: "A4 & Letter", text: "Portrait or landscape — your choice." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Image to PDF Converter turns one or many images into a clean, multi-page PDF. Unlike our JPG-to-PDF and PNG-to-PDF tools, this one accepts a mix of JPG, PNG, and WebP files in a single batch. Drop your images, reorder, choose A4 or US Letter (portrait or landscape), set page margins, and click Export. Everything is encoded using pdf-lib, a pure-JavaScript library that runs entirely inside your browser." },
      { emoji: "📄", icon: "target", title: "When you need it", text: "When your source folder has a mix of screenshots (PNG), photos (JPG), and web images (WebP) — and you just want one PDF at the end. Rather than converting each format separately and then merging, this tool handles the whole batch in one pass. Perfect for portfolios, receipts, scanned documents, and anything else that arrives in mixed formats." },
      { emoji: "⚡", icon: "printer", title: "How the conversion works", text: "JPG images are embedded byte-for-byte without re-compression — every pixel preserved. PNG and WebP images are drawn onto a canvas (with a white background for transparency) and encoded as PNG before being embedded. The PDF itself is built in memory and only written to a Blob when you click Download. No network requests are involved at any point." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your images is gone from memory." },
    ],
    howToTitle: "How to convert images to PDF",
    howTo: [
      { step: 1, title: "Drop your image files", description: "Drag JPG, PNG, or WebP files into the upload area, or click to browse. Up to 50 MB per file and up to 50 pages per PDF." },
      { step: 2, title: "Reorder pages", description: "Move pages up or down, or delete individual pages before export." },
      { step: 3, title: "Configure the PDF", description: "Choose page size (auto, A4, or Letter), orientation (portrait, landscape, or auto), and page margin." },
      { step: 4, title: "Export and download", description: "Click Export PDF. The file is built in your browser and downloaded instantly — no uploads involved." },
    ],
    featuresTitle: "Built for mixed image batches",
    features: [
      { emoji: "🖼️", title: "JPG + PNG + WebP", description: "The only PDF tool here that accepts all three formats in one batch." },
      { emoji: "🔒", title: "Zero uploads", description: "Images are read and embedded locally. Nothing travels over the network." },
      { emoji: "📄", title: "Up to 50 pages", description: "Combine dozens of images into a single multi-page PDF document." },
      { emoji: "📐", title: "A4 & US Letter", description: "Standard page sizes with portrait, landscape, or auto orientation." },
      { emoji: "🎯", title: "Full-resolution embedding", description: "JPGs are embedded byte-for-byte, preserving every pixel." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser using pdf-lib. Your files never leave your device." },
      { question: "Which image formats are supported?", answer: "JPG, JPEG, PNG, and WebP. You can mix them freely in the same batch." },
      { question: "What page sizes are supported?", answer: "Auto (matches each image's own size), A4 (210×297 mm), and US Letter (216×279 mm). Orientation can be portrait, landscape, or auto-detect." },
      { question: "How many pages can I combine?", answer: "Up to 50 pages per PDF. If you need more, run the tool again." },
      { question: "Will the image quality drop?", answer: "For JPG inputs, no — they are embedded byte-for-byte. For PNG and WebP, they are re-encoded losslessly to PNG before embedding, so visual quality is preserved." },
      { question: "Can I reorder pages?", answer: "Yes. Use the up/down arrows to reorder, and click X to remove individual pages." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your images are read and embedded entirely inside your browser using pdf-lib and the Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ থেকে PDF",
    heroSubtitle:
      "JPG, PNG ও WebP ছবি একটি PDF ডকুমেন্টে যুক্ত করুন — সম্পূর্ণ আপনার ব্রাউজারেই। ড্র্যাগ করুন, ক্রম বদলান, A4 বা Letter বেছে নিন, orientation ও margin ঠিক করুন, এবং ডাউনলোড করুন।",
    heroStats: [
      { value: "৩ ফরম্যাট", label: "JPG · PNG · WebP" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "A4/Letter", label: "পেজ সাইজ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🖼️", title: "মিশ্র ফরম্যাট", text: "JPG, PNG ও WebP — সব এক PDF-এ।" },
      { emoji: "📄", title: "মাল্টি-পেজ", text: "একাধিক ছবি এক PDF-এ।" },
      { emoji: "🔀", title: "পেজ সাজান", text: "এক্সপোর্টের আগে ক্রম বদলান।" },
      { emoji: "📐", title: "A4 ও Letter", text: "Portrait বা landscape — আপনার পছন্দ।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি হয়।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "Image to PDF Converter এক বা একাধিক ছবি থেকে পরিষ্কার multi-page PDF তৈরি করে। আমাদের JPG-to-PDF বা PNG-to-PDF টুলের থেকে আলাদা — এই টুলটি একই ব্যাচে JPG, PNG ও WebP মিশিয়ে নিতে পারে। সবকিছু pdf-lib ও Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "📄", icon: "target", title: "কখন দরকার", text: "যখন আপনার ফোল্ডারে স্ক্রিনশট (PNG), ছবি (JPG), আর ওয়েব ইমেজ (WebP) মিশে থাকে — এবং শেষে একটাই PDF দরকার। আলাদা আলাদা কনভার্ট করে merge করার বদলে এই টুল একবারেই সব সামলায়। পোর্টফোলিও, রিসিট, স্ক্যান করা ডকুমেন্ট — সবের জন্য পারফেক্ট।" },
      { emoji: "⚡", icon: "printer", title: "কনভার্সন কীভাবে কাজ করে", text: "JPG সরাসরি byte-for-byte embed হয় — কোনো re-compression নেই। PNG ও WebP কে canvas-এ (স্বচ্ছতার জন্য সাদা ব্যাকগ্রাউন্ড সহ) এঁকে PNG হিসেবে encode করে embed করা হয়। সম্পূর্ণ প্রক্রিয়া ব্রাউজার মেমরিতে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "ছবি কীভাবে PDF-এ রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "ছবি দিন", description: "JPG, PNG বা WebP ফাইল ড্র্যাগ করুন বা ক্লিক করুন। প্রতি ফাইল ৫০ MB পর্যন্ত, প্রতি PDF-এ ৫০ পেজ পর্যন্ত।" },
      { step: 2, title: "পেজ সাজান", description: "উপরে-নিচে সরান বা আলাদা পেজ মুছুন।" },
      { step: 3, title: "PDF কনফিগার করুন", description: "পেজ সাইজ (auto, A4, Letter), orientation (portrait, landscape, auto), এবং margin বেছে নিন।" },
      { step: 4, title: "Export করুন", description: "Export PDF চাপুন। ফাইল আপনার ব্রাউজারেই তৈরি হয় ও সাথে সাথে ডাউনলোড হয়।" },
    ],
    featuresTitle: "মিশ্র ব্যাচের জন্য তৈরি",
    features: [
      { emoji: "🖼️", title: "JPG + PNG + WebP", description: "একই ব্যাচে তিনটি ফরম্যাট নেয় এমন একমাত্র PDF টুল।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ছবি লোকালি পড়া ও embed করা হয়।" },
      { emoji: "📄", title: "৫০ পেজ পর্যন্ত", description: "একাধিক ছবি এক multi-page PDF-এ যুক্ত করুন।" },
      { emoji: "📐", title: "A4 ও Letter", description: "portrait, landscape বা auto orientation সহ স্ট্যান্ডার্ড পেজ সাইজ।" },
      { emoji: "🎯", title: "ফুল-রেজোলিউশন embed", description: "JPG byte-for-byte embed — প্রতিটি পিক্সেল সংরক্ষিত।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ফাইল কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "কোন ফরম্যাট সাপোর্টেড?", answer: "JPG, JPEG, PNG, WebP। একই ব্যাচে মিশিয়ে দেওয়া যায়।" },
      { question: "কোন পেজ সাইজ সাপোর্টেড?", answer: "Auto (প্রতিটি ছবির নিজের মাপ), A4 (২১০×২৯৭ মিমি), এবং Letter (২১৬×২৭৯ মিমি)।" },
      { question: "কত পেজ যুক্ত করা যায়?", answer: "প্রতি PDF-এ ৫০ পেজ পর্যন্ত।" },
      { question: "ছবির কোয়ালিটি কমবে?", answer: "JPG-এর ক্ষেত্রে না — byte-for-byte embed। PNG ও WebP lossless ভাবে PNG-তে encode হয়।" },
      { question: "পেজ ক্রম বদলানো যায়?", answer: "হ্যাঁ। উপরে-নিচে সরান বা X চেপে মুছুন।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি pdf-lib ও Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও embed করা হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageToPdfContent = typeof imageToPdfContent;
