export const pdfPageExtractorContent = {
  en: {
    heroTag: "PDF Page Extractor",
    heroSubtitle:
      "Extract pages from any PDF — in custom order, with duplicates if you want. Get one combined PDF or separate files per page. Everything runs in your browser — no uploads, no servers.",
    heroStats: [
      { value: "Custom order", label: "Preserved" },
      { value: "100%", label: "Private" },
      { value: "2 modes", label: "Combined / separate" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "PDF never leaves your device." },
      { emoji: "🎯", title: "Any order", text: "3, 1, 3, 5 — exactly as you type." },
      { emoji: "📄", title: "Combined PDF", text: "All selected pages in one file." },
      { emoji: "📁", title: "Separate files", text: "Each page as its own PDF." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
      { emoji: "⚡", title: "Lossless", text: "Pages copied byte-for-byte." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "PDF Page Extractor pulls pages out of your PDF and gives you either one combined PDF, or separate files — one per page. Unlike simpler extractors, this one respects the exact order you type and allows the same page to appear more than once. Enter '3, 1, 3, 5' and you'll get a 4-page PDF: page 3, then 1, then 3 again, then 5." },
      { emoji: "📄", title: "When you need it", text: "Reorder chapters before printing, duplicate a signature page in a document, extract cover pages for a preview, or grab a single page as its own file for emailing. All common extraction workflows, minus the upload." },
      { emoji: "⚡", title: "How the extraction works", text: "The tool loads your PDF with pdf-lib, copies each page you selected into a new document (in the exact order you typed), and saves the result. Pages are copied byte-for-byte with no re-rendering or re-compression, so text stays sharp and file size is proportional to what you extracted." },
      { emoji: "🔐", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs in your browser using JavaScript and pdf-lib. When you close the tab, every trace of your PDF is gone from memory." },
    ],
    howToTitle: "How to extract pages from PDF",
    howTo: [
      { step: 1, title: "Drop your PDF", description: "Drag a PDF into the upload area, or click to browse. Up to 100 MB." },
      { step: 2, title: "Enter the page list", description: "Type the pages you want in the order you want — e.g. 3, 1, 5-7. Duplicates allowed." },
      { step: 3, title: "Choose mode", description: "Combined: all pages in one new PDF. Separate: each page as its own file." },
      { step: 4, title: "Extract & download", description: "Click Extract. Download the result individually or all at once." },
    ],
    featuresTitle: "Built for real PDFs",
    features: [
      { emoji: "🎯", title: "Custom order", description: "Type pages in any order — 5, 1, 3, 2 works exactly as written." },
      { emoji: "🔁", title: "Duplicates allowed", description: "Extract the same page multiple times — useful for signatures." },
      { emoji: "📄", title: "Combined mode", description: "All selected pages become a single new PDF." },
      { emoji: "📁", title: "Separate mode", description: "One PDF per page, all downloaded in a batch." },
      { emoji: "🔒", title: "Zero uploads", description: "PDF parsing and saving happen entirely in your browser." },
      { emoji: "⚡", title: "Lossless copy", description: "Pages are copied byte-for-byte — no re-render, no quality loss." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my PDF uploaded?", answer: "No. Everything happens inside your browser using pdf-lib. Your file never leaves your device." },
      { question: "How is this different from Split PDF?", answer: "Split PDF extracts pages as a sorted unique set — and can split every page into a separate file. This tool preserves the order you type and allows the same page multiple times. If you need '3, 1, 3', use this tool. If you need '1, 3' sorted, either works." },
      { question: "Can I extract the same page twice?", answer: "Yes. Enter '3, 3' and you'll get a 2-page PDF with page 3 duplicated." },
      { question: "Can I reverse the order of pages?", answer: "Yes. Enter pages in reverse — e.g. '5, 4, 3, 2, 1' — to flip a document." },
      { question: "What's the difference between combined and separate modes?", answer: "Combined: one PDF containing all selected pages in your order. Separate: each selected page becomes its own PDF file, downloaded together." },
      { question: "Does it work on encrypted PDFs?", answer: "Password-protected PDFs can't be opened without the password. Encrypted-but-openable PDFs (owner password only) usually work." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your PDF is loaded, split, and saved entirely inside your browser using pdf-lib. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF পেজ এক্সট্রাক্টর",
    heroSubtitle:
      "যেকোনো PDF থেকে পেজ বের করুন — নিজের ক্রমে, চাইলে একই পেজ বারবার। একটি combined PDF বা প্রতিটি পেজ আলাদা ফাইল হিসেবে নিন। সম্পূর্ণ আপনার ব্রাউজারেই।",
    heroStats: [
      { value: "নিজের ক্রম", label: "সংরক্ষিত" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "২ মোড", label: "Combined / separate" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "PDF কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎯", title: "যেকোনো ক্রম", text: "3, 1, 3, 5 — যেমন লিখবে তেমন।" },
      { emoji: "📄", title: "Combined PDF", text: "সব নির্বাচিত পেজ এক ফাইলে।" },
      { emoji: "📁", title: "আলাদা ফাইল", text: "প্রতিটি পেজ আলাদা PDF।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "⚡", title: "Lossless", text: "পেজ byte-for-byte copy।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "PDF Page Extractor আপনার PDF থেকে পেজ বের করে — একটি combined PDF অথবা প্রতিটি পেজ আলাদা ফাইল হিসেবে দেয়। সাধারণ extractor-এর থেকে ভিন্ন, এটি আপনার লেখা exact order মানে এবং একই পেজ একাধিকবার ব্যবহার করতে দেয়। '3, 1, 3, 5' লিখলে আপনি 4-page PDF পাবেন: পেজ 3, তারপর 1, তারপর আবার 3, তারপর 5।" },
      { emoji: "📄", title: "কখন দরকার", text: "প্রিন্টের আগে chapter reorder করা, ডকুমেন্টে signature পেজ duplicate করা, preview-এর জন্য cover পেজ বের করা, বা email করার জন্য একটি পেজ আলাদা ফাইল হিসেবে নেওয়া — সব সাধারণ extraction workflow, upload ছাড়াই।" },
      { emoji: "⚡", title: "এক্সট্রাকশন কীভাবে কাজ করে", text: "টুলটি pdf-lib দিয়ে PDF লোড করে, আপনার নির্বাচিত প্রতিটি পেজ নতুন ডকুমেন্টে copy করে (আপনার লেখা exact order-এ), এবং result save করে। পেজ byte-for-byte copy হয় — কোনো re-render বা re-compression নেই, তাই text শার্প থাকে এবং ফাইল সাইজ proportional।" },
      { emoji: "🔐", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "PDF থেকে পেজ কীভাবে বের করবেন",
    howTo: [
      { step: 1, title: "PDF দিন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ১০০ MB পর্যন্ত।" },
      { step: 2, title: "পেজ লিস্ট লিখুন", description: "যে ক্রমে চান সেই ক্রমে পেজ লিখুন — যেমন 3, 1, 5-7। Duplicate চলে।" },
      { step: 3, title: "Mode বাছুন", description: "Combined: সব পেজ এক নতুন PDF-এ। Separate: প্রতিটি পেজ আলাদা ফাইলে।" },
      { step: 4, title: "Extract ও ডাউনলোড", description: "Extract চাপুন। আলাদা বা সব ফাইল ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত PDF-এর জন্য তৈরি",
    features: [
      { emoji: "🎯", title: "নিজের ক্রম", description: "যেকোনো ক্রমে পেজ লিখুন — 5, 1, 3, 2 হুবহু কাজ করবে।" },
      { emoji: "🔁", title: "Duplicate চলে", description: "একই পেজ একাধিকবার বের করা যায় — signature-এর জন্য কাজে লাগে।" },
      { emoji: "📄", title: "Combined mode", description: "সব নির্বাচিত পেজ এক নতুন PDF-এ।" },
      { emoji: "📁", title: "Separate mode", description: "প্রতি পেজ আলাদা PDF, batch-এ ডাউনলোড।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "PDF parse ও save সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "Lossless copy", description: "পেজ byte-for-byte copy — re-render নেই, quality loss নেই।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "Split PDF থেকে কী আলাদা?", answer: "Split PDF sorted unique set হিসেবে extract করে — আর প্রতিটি পেজ আলাদা ফাইল করতেও পারে। এই টুল আপনার লেখা order মানে এবং একই পেজ একাধিকবার দেয়। '3, 1, 3' দরকার হলে এই টুল। '1, 3' sorted দরকার হলে যেকোনোটা।" },
      { question: "একই পেজ দুইবার নেওয়া যায়?", answer: "হ্যাঁ। '3, 3' লিখলে 2-page PDF পাবেন যেখানে পেজ 3 duplicate।" },
      { question: "পেজ উল্টো করা যায়?", answer: "হ্যাঁ। উল্টো ক্রমে লিখুন — যেমন '5, 4, 3, 2, 1' — ডকুমেন্ট flip হবে।" },
      { question: "Combined আর Separate মোডের পার্থক্য?", answer: "Combined: আপনার ক্রমে সব নির্বাচিত পেজ এক PDF-এ। Separate: প্রতিটি নির্বাচিত পেজ আলাদা PDF, একসাথে ডাউনলোড।" },
      { question: "Encrypted PDF-এ কাজ করে?", answer: "Password-protected PDF খুলতে password লাগবে। Owner-password-only PDF সাধারণত কাজ করে।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari ও Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার PDF pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই load, split ও save হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type PdfPageExtractorContent = typeof pdfPageExtractorContent;
