export const faviconGeneratorContent = {
  en: {
    heroTag: "Favicon Generator",
    heroSubtitle:
      "Turn any image into a complete favicon set — browser icons, iOS home screen, Android PWA icons, and a web manifest. Add padding, background color, rounded corners. Download all at once. No uploads.",
    heroStats: [
      { value: "8 files", label: "In one export" },
      { value: "100%", label: "Private" },
      { value: "Live", label: "Preview" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Image never leaves your device." },
      { emoji: "🎨", title: "Live preview", text: "See every size as you tune." },
      { emoji: "📦", title: "8 files at once", text: "PNG + ICO + manifest." },
      { emoji: "🎯", title: "Auto background", text: "Detects image background color." },
      { emoji: "🖼️", title: "Rounded corners", text: "iOS/Android-style rounded icons." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Favicon Generator turns any image (JPG, PNG, WebP, SVG) into a complete favicon set. It generates every size modern browsers, iOS, and Android need, packs a multi-size favicon.ico, and includes a ready-to-use site.webmanifest. Add optional padding, background color (with auto-detect from the image itself), and rounded corners." },
      { emoji: "📄", title: "When you need it", text: "Launching a new website? You need a favicon for the browser tab, an apple-touch-icon for iOS home screens, and PWA icons for Android. Instead of manually generating eight files in Photoshop, this tool does it in one click from any image you already have." },
      { emoji: "⚡", title: "How it works", text: "The image is drawn onto canvases at each target size using the browser's Canvas API, preserving aspect ratio and centering with your chosen padding. The multi-size .ico file is packed in pure JavaScript (PNG-in-ICO format, supported by every modern browser). Everything runs in your browser — nothing is uploaded." },
      { emoji: "🔐", title: "Your image stays with you", text: "There is no server. No accounts. No analytics. Whatever image you drop — a logo, a headshot, brand asset — stays entirely inside your browser. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to generate a favicon",
    howTo: [
      { step: 1, title: "Upload your image", description: "Drop a JPG, PNG, WebP, or SVG. Square images work best but any aspect ratio is supported." },
      { step: 2, title: "Choose background", description: "Auto (detects from image), transparent, white, black, or custom color." },
      { step: 3, title: "Adjust padding & corners", description: "Add breathing room around the logo, and optionally apply rounded corners." },
      { step: 4, title: "Download all", description: "Get the full set — PNG icons, favicon.ico, and site.webmanifest — with one click." },
    ],
    featuresTitle: "Built for real websites",
    features: [
      { emoji: "📦", title: "Complete set", description: "16, 32, 48, 96, 180, 192, 512 PNGs + favicon.ico + manifest." },
      { emoji: "🎨", title: "Auto background", description: "Detects the dominant color at the image corner and uses it as the favicon background." },
      { emoji: "🖼️", title: "Rounded corners", description: "Optional radius (0–50%) for iOS/Android-style icons." },
      { emoji: "📐", title: "Smart padding", description: "Preserves aspect ratio and centers the image with configurable padding." },
      { emoji: "⚡", title: "Instant", description: "All eight files render in under a second — even at 512px." },
      { emoji: "🔒", title: "Zero uploads", description: "Image is processed entirely in your browser using the Canvas API." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no limits." },
      { question: "Is my image uploaded?", answer: "No. Everything happens in your browser using the Canvas API. Your image never leaves your device." },
      { question: "What files do I get?", answer: "favicon.ico (16/32/48 multi-size), favicon-16x16.png through favicon-512x512.png at standard sizes, apple-touch-icon.png (180×180), and site.webmanifest." },
      { question: "Where do I put these files?", answer: "Upload all PNGs and the .ico to your website's root directory (or /public in Vite/Next.js). Reference them in your HTML head with <link rel=\"icon\"> tags. The manifest goes at /site.webmanifest." },
      { question: "How do I add them to my HTML?", answer: "Add: <link rel=\"icon\" href=\"/favicon.ico\" sizes=\"any\" />, <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon-32x32.png\" />, <link rel=\"apple-touch-icon\" href=\"/apple-touch-icon.png\" />, <link rel=\"manifest\" href=\"/site.webmanifest\" />." },
      { question: "What does 'Auto' background do?", answer: "It samples the top-left corner pixels of your image. If they're transparent, no background is applied. Otherwise, that color becomes the favicon background — perfect for square logos on solid backgrounds." },
      { question: "Why rounded corners?", answer: "iOS and Android often apply their own rounding. Pre-rounding gives you control over how the icon looks on those platforms." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your image is read and processed entirely inside your browser using the Canvas API. Nothing is uploaded, tracked, or stored on any server.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ফ্যাভিকন জেনারেটর",
    heroSubtitle:
      "যেকোনো ছবি থেকে সম্পূর্ণ favicon সেট তৈরি করুন — ব্রাউজার আইকন, iOS হোম স্ক্রিন, Android PWA আইকন এবং web manifest। প্যাডিং, ব্যাকগ্রাউন্ড রঙ, রাউন্ডেড কর্নার যোগ করুন। একবারে সব ডাউনলোড।",
    heroStats: [
      { value: "৮টি ফাইল", label: "এক এক্সপোর্টে" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "লাইভ", label: "Preview" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ছবি কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "লাইভ preview", text: "প্রতিটি সাইজ দেখুন।" },
      { emoji: "📦", title: "৮টি ফাইল", text: "PNG + ICO + manifest।" },
      { emoji: "🎯", title: "Auto background", text: "ছবির রঙ নিজে থেকে ধরে।" },
      { emoji: "🖼️", title: "Rounded corners", text: "iOS/Android স্টাইল।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Favicon Generator যেকোনো ছবি (JPG, PNG, WebP, SVG) থেকে সম্পূর্ণ favicon সেট তৈরি করে। আধুনিক ব্রাউজার, iOS এবং Android-এর প্রয়োজনীয় সব সাইজ জেনারেট করে, multi-size favicon.ico প্যাক করে এবং ready-to-use site.webmanifest সহ দেয়।" },
      { emoji: "📄", title: "কখন দরকার", text: "নতুন website launch করছেন? Browser tab-এর জন্য favicon, iOS home screen-এর জন্য apple-touch-icon, Android PWA-এর জন্য icons দরকার। Photoshop-এ manually আটটা ফাইল বানানোর বদলে এই টুল এক ক্লিকে কাজ শেষ করে।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "ছবিটি Canvas API দিয়ে প্রতিটি target size-এ আঁকা হয়, aspect ratio বজায় রেখে, আপনার নির্বাচিত padding দিয়ে centered। multi-size .ico ফাইল pure JavaScript-এ pack করা হয় (PNG-in-ICO format, সব modern browser সাপোর্ট করে)।" },
      { emoji: "🔐", title: "আপনার ছবি আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। আপনি যে ছবি drop করেন — logo, headshot, brand asset — সম্পূর্ণ ব্রাউজারেই থাকে।" },
    ],
    howToTitle: "কীভাবে favicon তৈরি করবেন",
    howTo: [
      { step: 1, title: "ছবি upload করুন", description: "JPG, PNG, WebP বা SVG drop করুন। Square image ভালো কাজ করে কিন্তু যেকোনো aspect ratio চলে।" },
      { step: 2, title: "Background বাছুন", description: "Auto (ছবি থেকে detect), transparent, white, black, বা custom color।" },
      { step: 3, title: "Padding ও corners ঠিক করুন", description: "Logo-র চারপাশে জায়গা দিন, চাইলে rounded corners।" },
      { step: 4, title: "সব ডাউনলোড করুন", description: "সম্পূর্ণ সেট — PNG icons, favicon.ico, site.webmanifest — এক ক্লিকে।" },
    ],
    featuresTitle: "প্রকৃত website-এর জন্য তৈরি",
    features: [
      { emoji: "📦", title: "সম্পূর্ণ সেট", description: "16, 32, 48, 96, 180, 192, 512 PNG + favicon.ico + manifest।" },
      { emoji: "🎨", title: "Auto background", description: "ছবির corner থেকে dominant color detect করে background হিসেবে ব্যবহার করে।" },
      { emoji: "🖼️", title: "Rounded corners", description: "Optional radius (০–৫০%) iOS/Android স্টাইল।" },
      { emoji: "📐", title: "Smart padding", description: "Aspect ratio রক্ষা করে, configurable padding দিয়ে centered।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", description: "আটটা ফাইল সেকেন্ডের কমে render করে — 512px-ও।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ছবি সম্পূর্ণ ব্রাউজারেই Canvas API দিয়ে process হয়।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ছবি আপলোড হয়?", answer: "না। Canvas API দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "কী কী ফাইল পাবো?", answer: "favicon.ico (16/32/48 multi-size), favicon-16x16.png থেকে favicon-512x512.png পর্যন্ত, apple-touch-icon.png (180×180), এবং site.webmanifest।" },
      { question: "ফাইলগুলো কোথায় রাখবো?", answer: "সব PNG ও .ico আপনার website-এর root directory-তে (Vite/Next.js-এ /public) রাখুন। HTML head-এ <link rel=\"icon\"> দিয়ে reference করুন। Manifest /site.webmanifest-এ যাবে।" },
      { question: "HTML-এ কীভাবে যোগ করবো?", answer: "<link rel=\"icon\" href=\"/favicon.ico\" sizes=\"any\" />, <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon-32x32.png\" />, <link rel=\"apple-touch-icon\" href=\"/apple-touch-icon.png\" />, <link rel=\"manifest\" href=\"/site.webmanifest\" />।" },
      { question: "'Auto' background কী করে?", answer: "ছবির top-left corner pixel sample করে। Transparent হলে কোনো background নেই। নাহলে সেই রঙটাই favicon background হয়।" },
      { question: "Rounded corners কেন?", answer: "iOS/Android নিজেরাই rounding করে। Pre-rounding দিলে আপনি control পান।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি Canvas API দিয়ে সম্পূর্ণ ব্রাউজারেই process হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type FaviconGeneratorContent = typeof faviconGeneratorContent;
