export const jpgToWebpContent = {
  en: {
    heroTag: "Image Converter",
    heroSubtitle:
      "Convert JPG images to modern WebP format instantly in your browser. WebP files are typically 25-35% smaller than JPG with the same visual quality — perfect for websites, apps, and faster loading pages. No uploads, no servers.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "-30%", label: "File Size" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device. Zero uploads." },
      { emoji: "⚡", title: "Instant conversion", text: "Runs in your browser — no server wait." },
      { emoji: "📦", title: "Batch support", text: "Convert multiple JPGs at once." },
      { emoji: "📉", title: "25-35% smaller", text: "WebP saves bytes vs JPG at same quality." },
      { emoji: "🌐", title: "Modern format", text: "Supported by every modern browser." },
      { emoji: "💾", title: "Download anytime", text: "Individual or bulk download with one click." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "JPG to WebP Converter takes your JPEG photos and re-encodes them as modern WebP images at 85% quality. It reads the JPG locally in your browser, draws it onto an off-screen canvas at full resolution, and exports the result as a WebP blob. No byte leaves your device. You can drop in one file or a hundred — the tool converts them one by one and shows both original and converted sizes side by side." },
      { emoji: "📉", icon: "target", title: "Why WebP?", text: "WebP is a modern image format developed by Google. At the same visual quality as JPG, WebP files are typically 25-35% smaller. That means faster page loads, lower bandwidth costs, and better SEO scores. WebP is now supported by every modern browser — Chrome, Firefox, Safari, and Edge — and by most image editors and CDNs." },
      { emoji: "⚡", icon: "printer", title: "How the conversion works", text: "The tool uses the browser's built-in HTML5 Canvas API to encode WebP. Modern browsers have a native WebP encoder built in, so no external library is needed. When you drop a JPG, the browser decodes it, the canvas re-draws the pixels, and then exports the result as a WebP blob at 85% quality. Everything happens locally — no network traffic is involved." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript inside the page you are looking at. When you close the tab, every trace of your files is gone from memory. This makes the tool suitable for confidential photos, client work, and any image you would not want a third party to see." },
    ],
    howToTitle: "How to convert JPG to WebP",
    howTo: [
      { step: 1, title: "Drop your JPG files", description: "Drag and drop one or more JPG or JPEG files into the upload area, or click to browse. Files up to 50 MB each are supported." },
      { step: 2, title: "Wait a moment", description: "The tool converts each file in sequence. Conversion happens on your device, so it usually takes less than a second per file." },
      { step: 3, title: "Review the results", description: "Each converted file appears with the original name, original size, and the new WebP size — usually 25-35% smaller. Compare with preview thumbnails." },
      { step: 4, title: "Download individually or all at once", description: "Click Download on any single file, or use Download All to grab every converted WebP in one go." },
    ],
    featuresTitle: "Built for real conversions",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "The file is decoded and re-encoded entirely in your browser. Nothing travels over the network." },
      { emoji: "⚡", title: "Instant results", description: "No queue, no waiting for a server. Every file converts in under a second on modern hardware." },
      { emoji: "📦", title: "Batch processing", description: "Drop multiple JPGs at once and convert them all in a single session." },
      { emoji: "📉", title: "25-35% smaller", description: "WebP saves bytes vs JPG at the same visual quality, helping page speed and bandwidth." },
      { emoji: "🌐", title: "Universal browser support", description: "WebP works in Chrome, Firefox, Safari, Edge, and every modern mobile browser." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each are accepted. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit. The tool is supported by ads shown outside the workspace." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything — decoding, canvas rendering, and WebP encoding — happens inside your browser. Your files never leave your device." },
      { question: "Will the quality drop?", answer: "WebP uses lossy compression at 85% quality — the visual difference from the original JPG is usually impossible to spot, but the file is significantly smaller." },
      { question: "How much smaller will the file be?", answer: "Typically 25-35% smaller than the original JPG. A 2 MB JPG often becomes a 1.3-1.5 MB WebP." },
      { question: "Does WebP work everywhere?", answer: "Yes — every modern browser (Chrome, Firefox, Safari, Edge, Opera) supports WebP. Every modern operating system supports it too." },
      { question: "Can I convert multiple files at once?", answer: "Yes. Drop as many JPGs as you want and they will all be converted. Use Download All to save every file in one click." },
      { question: "Is there a file size limit?", answer: "Each file can be up to 50 MB. There is no limit on the number of files you convert in one session." },
      { question: "What if my browser doesn't support WebP encoding?", answer: "Every modern browser since 2020 supports WebP encoding. If you use a very old browser, the tool will show an error explaining that WebP encoding is not supported." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ কনভার্টার",
    heroSubtitle:
      "JPG ছবি আধুনিক WebP ফরম্যাটে সাথে সাথে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। WebP ফাইল সাধারণত JPG-এর চেয়ে ২৫-৩৫% ছোট, একই ভিজ্যুয়াল কোয়ালিটিতে। ওয়েবসাইট, অ্যাপ এবং দ্রুত পেজ লোডের জন্য আদর্শ।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "-৩০%", label: "ফাইল সাইজ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক রূপান্তর", text: "ব্রাউজারেই চলে — সার্ভারের অপেক্ষা নেই।" },
      { emoji: "📦", title: "ব্যাচ সাপোর্ট", text: "একাধিক JPG একসাথে রূপান্তর করুন।" },
      { emoji: "📉", title: "২৫-৩৫% ছোট", text: "একই কোয়ালিটিতে WebP বাইট সাশ্রয় করে।" },
      { emoji: "🌐", title: "আধুনিক ফরম্যাট", text: "সব আধুনিক ব্রাউজারে সাপোর্টেড।" },
      { emoji: "💾", title: "যেকোনো সময় ডাউনলোড", text: "এক ক্লিকে আলাদা বা সব একসাথে।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "JPG থেকে WebP কনভার্টার আপনার JPEG ছবিগুলোকে ৮৫% কোয়ালিটিতে আধুনিক WebP ছবিতে রূপান্তর করে। এটি JPG ফাইলটি আপনার ব্রাউজারেই পড়ে, সম্পূর্ণ রেজোলিউশনে একটি off-screen ক্যানভাসে আঁকে এবং ফলাফলটি WebP হিসেবে এক্সপোর্ট করে। একটি বাইটও আপনার ডিভাইস ছাড়ে না।" },
      { emoji: "📉", icon: "target", title: "কেন WebP?", text: "WebP একটি আধুনিক ইমেজ ফরম্যাট যা Google তৈরি করেছে। একই ভিজ্যুয়াল কোয়ালিটিতে WebP ফাইল সাধারণত JPG-এর চেয়ে ২৫-৩৫% ছোট। এর মানে দ্রুত পেজ লোড, কম ব্যান্ডউইথ খরচ, এবং ভালো SEO স্কোর। WebP এখন সব আধুনিক ব্রাউজারে সাপোর্টেড।" },
      { emoji: "⚡", icon: "printer", title: "কনভার্সন কীভাবে কাজ করে", text: "টুলটি ব্রাউজারের HTML5 Canvas API ব্যবহার করে WebP এনকোড করে। আধুনিক ব্রাউজারে নেটিভ WebP এনকোডার আছে, তাই কোনো বাইরের লাইব্রেরি লাগে না। JPG ড্রপ করলে ব্রাউজার সেটি ডিকোড করে, ক্যানভাস পিক্সেলগুলো আঁকে, এবং ৮৫% কোয়ালিটিতে WebP হিসেবে এক্সপোর্ট করে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই আপনার ফাইলের সব চিহ্ন মেমরি থেকে মুছে যায়।" },
    ],
    howToTitle: "JPG কীভাবে WebP-তে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "আপনার JPG ফাইল দিন", description: "এক বা একাধিক JPG/JPEG ফাইল upload এলাকায় ড্র্যাগ করে আনুন, বা ক্লিক করে ব্রাউজ করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "একটু অপেক্ষা করুন", description: "টুলটি একটার পর একটা ফাইল কনভার্ট করে। সাধারণত প্রতি ফাইল এক সেকেন্ডেরও কম সময় লাগে।" },
      { step: 3, title: "ফলাফল দেখুন", description: "প্রতিটি কনভার্টেড ফাইল তালিকায় দেখা যায় — মূল সাইজ ও নতুন WebP সাইজ সহ, সাধারণত ২৫-৩৫% ছোট।" },
      { step: 4, title: "আলাদা বা সব একসাথে ডাউনলোড", description: "যেকোনো ফাইলে Download চাপুন, বা Download All দিয়ে সব WebP একবারে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত কনভার্সনের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল ডিকোড ও রি-এনকোড সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "তাৎক্ষণিক ফলাফল", description: "আধুনিক হার্ডওয়্যারে প্রতি ফাইল এক সেকেন্ডেরও কমে।" },
      { emoji: "📦", title: "ব্যাচ প্রসেসিং", description: "একাধিক JPG একবারে দিন এবং একটি সেশনেই সব কনভার্ট করুন।" },
      { emoji: "📉", title: "২৫-৩৫% ছোট", description: "একই ভিজ্যুয়াল কোয়ালিটিতে WebP বাইট সাশ্রয় করে, পেজ স্পিড ও ব্যান্ডউইথ ভালো করে।" },
      { emoji: "🌐", title: "সার্বজনীন ব্রাউজার সাপোর্ট", description: "WebP Chrome, Firefox, Safari, Edge এবং সব আধুনিক মোবাইল ব্রাউজারে কাজ করে।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত। কোনো signup নেই, ওয়াটারমার্ক নেই।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই, লুকানো সাইজ লিমিট নেই।" },
      { question: "আমার ফাইল কি সার্ভারে আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই হয়। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "কোয়ালিটি কমে যাবে?", answer: "WebP ৮৫% কোয়ালিটিতে lossy কম্প্রেশন ব্যবহার করে — মূল JPG থেকে ভিজ্যুয়াল পার্থক্য সাধারণত চোখে পড়ে না, কিন্তু ফাইল অনেক ছোট হয়।" },
      { question: "ফাইল কতটা ছোট হবে?", answer: "সাধারণত মূল JPG-এর চেয়ে ২৫-৩৫% ছোট। ২ MB JPG প্রায়ই ১.৩-১.৫ MB WebP হয়।" },
      { question: "WebP সব জায়গায় কাজ করে?", answer: "হ্যাঁ — সব আধুনিক ব্রাউজার (Chrome, Firefox, Safari, Edge, Opera) WebP সাপোর্ট করে।" },
      { question: "একসাথে একাধিক ফাইল কনভার্ট করা যায়?", answer: "হ্যাঁ। যত চান JPG ড্রপ করুন, সব কনভার্ট হবে।" },
      { question: "ফাইল সাইজের লিমিট আছে?", answer: "প্রতি ফাইল ৫০ MB পর্যন্ত। এক সেশনে ফাইল সংখ্যার সীমা নেই।" },
      { question: "আমার ব্রাউজার WebP এনকোডিং সাপোর্ট না করলে?", answer: "২০২০ সালের পরের সব আধুনিক ব্রাউজার WebP এনকোডিং সাপোর্ট করে। খুব পুরনো ব্রাউজার হলে একটি error message দেখাবে।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্য যেসব টুল ভালো লাগতে পারে",
  },
};

export type JpgToWebpContent = typeof jpgToWebpContent;
