export const base64Content = {
  en: {
    heroTag: "Base64 Encoder",
    heroSubtitle:
      "Encode or decode Base64 for text and files — right in your browser. Unicode-safe, URL-safe option, image preview. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Encode", label: "& decode" },
      { value: "Files", label: "& text" },
      { value: "100%", label: "Private" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Data never leaves your device." },
      { emoji: "🔄", title: "Encode & decode", text: "Both directions, live output." },
      { emoji: "📄", title: "Text + files", text: "Anything — from text to images." },
      { emoji: "🌐", title: "Unicode safe", text: "Bangla, emoji, CJK — all handled." },
      { emoji: "🖼️", title: "Image preview", text: "See decoded images instantly." },
      { emoji: "🔗", title: "URL-safe option", text: "RFC 4648 base64url when needed." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Base64 Encoder / Decoder converts between raw data and Base64 — the standard text encoding that represents binary data using 64 printable characters. Use it to encode text, images, PDFs, or any file, and decode back to the original. Everything runs in your browser, no uploads." },
      { emoji: "📄", title: "When you need it", text: "Embed images in HTML/CSS without separate files. Send binary data through JSON APIs. Encode credentials for HTTP Basic auth. Inspect data URLs. Decode API responses. Base64 shows up everywhere — this tool makes both directions trivial." },
      { emoji: "⚡", title: "Unicode & URL safety", text: "Standard btoa fails on non-Latin1 characters. This tool uses TextEncoder to correctly encode Bangla, emoji, Arabic, Chinese, and any other Unicode first. The URL-safe toggle (RFC 4648 §5) swaps + and / for - and _ and strips padding — required for JWT, URLs, and filenames." },
      { emoji: "🔐", title: "Your data stays with you", text: "There is no server. No accounts. No analytics. Everything is processed in your browser using native APIs. Close the tab and everything disappears." },
    ],
    howToTitle: "How to encode or decode Base64",
    howTo: [
      { step: 1, title: "Choose mode", description: "Encode (to Base64) or Decode (from Base64)." },
      { step: 2, title: "Pick input kind", description: "Text for typed input, File for uploads (images, PDFs, etc.)." },
      { step: 3, title: "Adjust options", description: "Toggle URL-safe mode for JWT, URLs, and filenames." },
      { step: 4, title: "Copy or download", description: "Copy the result or download as a file." },
    ],
    featuresTitle: "Built for real Base64 work",
    features: [
      { emoji: "🌐", title: "Unicode-safe", description: "Bangla, emoji, Arabic, CJK — encoded correctly via TextEncoder." },
      { emoji: "📄", title: "Files up to 10 MB", description: "Images, PDFs, videos — anything you drop." },
      { emoji: "🖼️", title: "Image preview", description: "Decoded images display inline with download button." },
      { emoji: "🔗", title: "URL-safe mode", description: "RFC 4648 base64url for JWT and URLs." },
      { emoji: "⚡", title: "Live output", description: "Result updates as you type — no button required." },
      { emoji: "🔒", title: "Zero uploads", description: "Nothing leaves your browser." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my data uploaded?", answer: "No. Everything happens in your browser using native TextEncoder, TextDecoder, btoa, and atob. Nothing is sent over the network." },
      { question: "What is Base64 used for?", answer: "Embedding images in HTML/CSS, sending binary through JSON APIs, HTTP Basic auth headers, data URLs, JWT tokens, email attachments (MIME), and anywhere text-only channels must carry binary data." },
      { question: "What's URL-safe Base64?", answer: "Standard Base64 uses + and /, which have special meaning in URLs. URL-safe Base64 (RFC 4648 §5) swaps them for - and _ and drops padding. Required for JWT, URLs, and filenames." },
      { question: "Why do non-English characters break normal Base64 encoders?", answer: "btoa only handles Latin1 (byte values 0–255). This tool encodes with TextEncoder first, so any Unicode character — Bangla, emoji, Chinese — works correctly." },
      { question: "Does Base64 make data larger?", answer: "Yes — Base64 inflates data by ~33% because it uses 4 characters to represent 3 bytes. The tool shows the exact byte delta after each conversion." },
      { question: "Can I decode a data URL?", answer: "Yes — the decoder accepts full data URLs (data:image/png;base64,...) or just the Base64 payload." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your data is processed entirely inside your browser using native JavaScript APIs. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "Base64 এনকোডার",
    heroSubtitle:
      "টেক্সট ও ফাইলের Base64 encode বা decode করুন — সম্পূর্ণ আপনার ব্রাউজারেই। Unicode-safe, URL-safe অপশন, image preview। কোনো আপলোড নেই।",
    heroStats: [
      { value: "Encode", label: "ও decode" },
      { value: "ফাইল", label: "ও টেক্সট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ডেটা কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🔄", title: "Encode ও decode", text: "দুই দিকই, লাইভ output।" },
      { emoji: "📄", title: "টেক্সট + ফাইল", text: "যেকোনো কিছু — টেক্সট থেকে ছবি।" },
      { emoji: "🌐", title: "Unicode নিরাপদ", text: "বাংলা, emoji, CJK — সব handle।" },
      { emoji: "🖼️", title: "Image preview", text: "Decoded ছবি সাথে সাথে দেখুন।" },
      { emoji: "🔗", title: "URL-safe অপশন", text: "দরকারে RFC 4648 base64url।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Base64 Encoder / Decoder raw data ও Base64-এর মধ্যে convert করে — যে standard text encoding 64 printable character দিয়ে binary data প্রকাশ করে। টেক্সট, ছবি, PDF বা যেকোনো ফাইল encode করুন, এবং আবার decode করুন। সবকিছু ব্রাউজারেই, কোনো আপলোড নেই।" },
      { emoji: "📄", title: "কখন দরকার", text: "আলাদা file ছাড়াই HTML/CSS-এ ছবি embed করা। JSON API দিয়ে binary data পাঠানো। HTTP Basic auth-এর credential encode করা। Data URL inspect করা। API response decode করা। Base64 সব জায়গায় — এই টুল দুই দিকই সহজ করে।" },
      { emoji: "⚡", title: "Unicode ও URL safety", text: "সাধারণ btoa non-Latin1 character-এ fail করে। এই টুল TextEncoder দিয়ে বাংলা, emoji, আরবি, চাইনিজ — যেকোনো Unicode সঠিকভাবে encode করে। URL-safe toggle (RFC 4648 §5) + ও / কে - ও _ দিয়ে replace করে padding বাদ দেয় — JWT, URL ও filename-এর জন্য প্রয়োজন।" },
      { emoji: "🔐", title: "আপনার ডেটা আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। সবকিছু native API দিয়ে আপনার ব্রাউজারেই। ট্যাব বন্ধ করলেই চলে যায়।" },
    ],
    howToTitle: "Base64 কীভাবে encode বা decode করবেন",
    howTo: [
      { step: 1, title: "Mode বাছুন", description: "Encode (Base64-এ) বা Decode (Base64 থেকে)।" },
      { step: 2, title: "Input ধরন বাছুন", description: "Typed input-এর জন্য Text, upload-এর জন্য File (ছবি, PDF ইত্যাদি)।" },
      { step: 3, title: "অপশন ঠিক করুন", description: "JWT, URL ও filename-এর জন্য URL-safe mode toggle করুন।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "Result কপি করুন বা file হিসেবে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত Base64 কাজের জন্য",
    features: [
      { emoji: "🌐", title: "Unicode-safe", description: "বাংলা, emoji, আরবি, CJK — TextEncoder দিয়ে সঠিকভাবে encode।" },
      { emoji: "📄", title: "১০ MB পর্যন্ত ফাইল", description: "ছবি, PDF, ভিডিও — যা drop করেন।" },
      { emoji: "🖼️", title: "Image preview", description: "Decoded ছবি inline display, download button সহ।" },
      { emoji: "🔗", title: "URL-safe mode", description: "JWT ও URL-এর জন্য RFC 4648 base64url।" },
      { emoji: "⚡", title: "লাইভ output", description: "Typing-এর সাথে result update।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "কিছুই ব্রাউজার ছাড়ে না।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ডেটা কি আপলোড হয়?", answer: "না। native TextEncoder, TextDecoder, btoa ও atob দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "Base64 কীসের জন্য?", answer: "HTML/CSS-এ ছবি embed, JSON API দিয়ে binary পাঠানো, HTTP Basic auth header, data URL, JWT token, email attachment (MIME) — যেখানে text-only channel-এ binary পাঠাতে হয়।" },
      { question: "URL-safe Base64 কী?", answer: "Standard Base64-এ + ও / ব্যবহার হয়, যাদের URL-এ বিশেষ অর্থ। URL-safe Base64 (RFC 4648 §5) এদের - ও _ দিয়ে replace করে padding বাদ দেয়। JWT, URL ও filename-এর জন্য প্রয়োজন।" },
      { question: "Non-English character সাধারণ Base64 encoder-এ break করে কেন?", answer: "btoa শুধু Latin1 (byte 0–255) handle করে। এই টুল প্রথমে TextEncoder দিয়ে encode করে, তাই যেকোনো Unicode character — বাংলা, emoji, চাইনিজ — সঠিকভাবে কাজ করে।" },
      { question: "Base64 ডেটা বড় করে?", answer: "হ্যাঁ — Base64 ~৩৩% বাড়ায় কারণ ৩ byte কে ৪ character দিয়ে represent করে। টুল প্রতিটি conversion-এর পর exact byte delta দেখায়।" },
      { question: "Data URL decode করা যায়?", answer: "হ্যাঁ — decoder full data URL (data:image/png;base64,...) বা শুধু Base64 payload দুটোই নেয়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ডেটা native JavaScript API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই process হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type Base64Content = typeof base64Content;
