export const uuidGeneratorContent = {
  en: {
    heroTag: "UUID Generator",
    heroSubtitle:
      "Generate UUID v4 (random) and v7 (time-ordered) identifiers in your browser. Batch up to 1000 at once, copy or download as text. Uses the Web Crypto API — cryptographically random, never uploaded.",
    heroStats: [
      { value: "v4 & v7", label: "Versions" },
      { value: "1000 max", label: "Per batch" },
      { value: "Crypto", label: "Random" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Generated locally, never uploaded." },
      { emoji: "🎲", title: "Crypto-random", text: "Web Crypto API, not Math.random." },
      { emoji: "📦", title: "Batch up to 1000", text: "Mass-generate and copy in one go." },
      { emoji: "🕐", title: "v4 & v7", text: "Random or time-ordered, your choice." },
      { emoji: "🔤", title: "Format options", text: "Uppercase, hyphens on/off." },
      { emoji: "📋", title: "Copy / download", text: "One-click clipboard or .txt file." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "UUID Generator produces RFC-compliant universally unique identifiers entirely in your browser. Choose UUID v4 (pure random) or v7 (time-ordered), generate up to 1000 at once, toggle uppercase or hyphen removal, and copy or download the batch. Nothing is sent over the network — you can generate with the Wi-Fi off." },
      { emoji: "📄", title: "v4 vs v7 — which to use", text: "UUID v4 is 122 random bits — perfect when you just need a globally unique ID with no ordering. UUID v7 embeds a 48-bit Unix-millisecond timestamp in the first bytes and random data after, so IDs are naturally sortable by creation time. Use v7 for database primary keys — indexes stay happy and pagination works better than with v4." },
      { emoji: "⚡", title: "How randomness works", text: "This tool uses the browser's Web Crypto API (crypto.randomUUID and crypto.getRandomValues). That's the same cryptographically secure randomness your browser uses for TLS keys — not Math.random, which is predictable. Version and variant bits are set exactly per RFC 4122 (v4) and RFC 9562 (v7)." },
      { emoji: "🔐", title: "Your IDs stay with you", text: "There is no server. No accounts. No analytics. Every UUID is generated locally in your browser. Because nothing ever leaves your device, this tool is safe for IDs used in production systems, tokens, or anywhere unpredictability matters." },
    ],
    howToTitle: "How to generate UUIDs",
    howTo: [
      { step: 1, title: "Pick a version", description: "v4 for pure random, v7 for time-ordered." },
      { step: 2, title: "Set the count", description: "Anywhere from 1 to 1000 per batch." },
      { step: 3, title: "Toggle format", description: "Uppercase or lowercase, hyphens on or off." },
      { step: 4, title: "Copy or download", description: "Copy the whole batch to clipboard or download as a .txt file." },
    ],
    featuresTitle: "Built for real UUID work",
    features: [
      { emoji: "🎲", title: "Crypto-random", description: "Uses Web Crypto API — the same source TLS uses." },
      { emoji: "🕐", title: "v4 & v7 support", description: "Random (v4) or sortable by time (v7) — RFC compliant." },
      { emoji: "📦", title: "Batch up to 1000", description: "Generate thousands per session without slowdown." },
      { emoji: "🔤", title: "Format control", description: "Uppercase, hyphens on/off — copy exactly what you need." },
      { emoji: "📋", title: "Copy or download", description: "One-click clipboard or export as .txt." },
      { emoji: "🔒", title: "Zero uploads", description: "Works offline. Nothing leaves your device." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Are UUIDs uploaded anywhere?", answer: "No. Everything is generated inside your browser using the Web Crypto API. You can disconnect Wi-Fi and it still works." },
      { question: "What's the difference between v4 and v7?", answer: "v4 is 122 random bits — no ordering, just uniqueness. v7 starts with a 48-bit Unix timestamp, so IDs sort by creation time. Use v7 for database primary keys." },
      { question: "How random is a v4 UUID?", answer: "122 bits of entropy — you'd need to generate roughly 2.7 × 10^18 UUIDs to have a 50% chance of a single collision. For practical purposes, they're unique forever." },
      { question: "Can I use v7 IDs as primary keys?", answer: "Yes — that's the main use case. Because the timestamp comes first, v7 keys insert in a roughly sequential order, which keeps database indexes efficient." },
      { question: "How many can I generate at once?", answer: "Up to 1000 per batch. Click Regenerate as many times as you like." },
      { question: "Can I remove the hyphens?", answer: "Yes — toggle hyphens off to get a 32-character hex string (often used for short IDs or URL slugs)." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "UUIDs are generated entirely inside your browser using the Web Crypto API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "UUID জেনারেটর",
    heroSubtitle:
      "UUID v4 (random) ও v7 (time-ordered) আইডেন্টিফায়ার তৈরি করুন — সম্পূর্ণ আপনার ব্রাউজারেই। একবারে ১০০০ পর্যন্ত, কপি বা .txt ডাউনলোড। Web Crypto API — ক্রিপ্টোগ্রাফিক randomness।",
    heroStats: [
      { value: "v4 ও v7", label: "ভার্সন" },
      { value: "১০০০ সর্বোচ্চ", label: "প্রতি ব্যাচ" },
      { value: "Crypto", label: "Random" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "লোকালি তৈরি, কখনো আপলোড হয় না।" },
      { emoji: "🎲", title: "Crypto-random", text: "Web Crypto API, Math.random নয়।" },
      { emoji: "📦", title: "১০০০ পর্যন্ত ব্যাচ", text: "একবারে অনেক তৈরি ও কপি।" },
      { emoji: "🕐", title: "v4 ও v7", text: "Random বা time-ordered — আপনার পছন্দ।" },
      { emoji: "🔤", title: "Format অপশন", text: "Uppercase, hyphen on/off।" },
      { emoji: "📋", title: "কপি / ডাউনলোড", text: "এক ক্লিকে clipboard বা .txt।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "UUID Generator RFC-সম্মত universally unique identifier তৈরি করে — সম্পূর্ণ আপনার ব্রাউজারেই। UUID v4 (pure random) বা v7 (time-ordered) বেছে নিন, একবারে ১০০০ পর্যন্ত তৈরি করুন, uppercase বা hyphen বাদ দিন, এবং batch কপি বা ডাউনলোড করুন। কিছুই নেটওয়ার্কে যায় না — Wi-Fi বন্ধ করেও generate করা যায়।" },
      { emoji: "📄", title: "v4 vs v7 — কোনটা কখন", text: "UUID v4-তে ১২২ random bit — শুধু globally unique ID দরকার হলে perfect। UUID v7-এ প্রথম bytes-এ ৪৮-bit Unix-millisecond timestamp থাকে — তাই ID creation time অনুযায়ী naturally sortable। Database primary key-র জন্য v7 ব্যবহার করুন — index ভালো থাকে এবং pagination v4-এর চেয়ে ভালো কাজ করে।" },
      { emoji: "⚡", title: "Randomness কীভাবে কাজ করে", text: "এই টুল browser-এর Web Crypto API (crypto.randomUUID ও crypto.getRandomValues) ব্যবহার করে। এটাই সেই cryptographically secure randomness যা browser TLS key-তে ব্যবহার করে — Math.random নয়, যেটা predictable। Version ও variant bit RFC 4122 (v4) ও RFC 9562 (v7) অনুযায়ী সেট করা।" },
      { emoji: "🔐", title: "আপনার ID আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। প্রতিটি UUID আপনার ব্রাউজারেই তৈরি হয়। কিছু কখনো ডিভাইস ছাড়ে না, তাই production system, token বা যেখানে unpredictability দরকার সেখানে নিরাপদ।" },
    ],
    howToTitle: "UUID কীভাবে তৈরি করবেন",
    howTo: [
      { step: 1, title: "Version বাছুন", description: "Pure random-এর জন্য v4, time-ordered-এর জন্য v7।" },
      { step: 2, title: "Count সেট করুন", description: "১ থেকে ১০০০ পর্যন্ত প্রতি ব্যাচে।" },
      { step: 3, title: "Format ঠিক করুন", description: "Uppercase বা lowercase, hyphen সহ বা ছাড়া।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "পুরো batch clipboard-এ কপি বা .txt file হিসেবে ডাউনলোড।" },
    ],
    featuresTitle: "প্রকৃত UUID কাজের জন্য",
    features: [
      { emoji: "🎲", title: "Crypto-random", description: "Web Crypto API ব্যবহার — TLS যেটা ব্যবহার করে।" },
      { emoji: "🕐", title: "v4 ও v7", description: "Random (v4) বা time-sortable (v7) — RFC সম্মত।" },
      { emoji: "📦", title: "১০০০ পর্যন্ত ব্যাচ", description: "Slowdown ছাড়াই হাজার হাজার generate করুন।" },
      { emoji: "🔤", title: "Format control", description: "Uppercase, hyphen on/off — যা দরকার তাই কপি।" },
      { emoji: "📋", title: "কপি বা ডাউনলোড", description: "এক ক্লিকে clipboard বা .txt export।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "Offline-ও কাজ করে।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "UUID কি কোথাও আপলোড হয়?", answer: "না। Web Crypto API দিয়ে সবকিছু আপনার ব্রাউজারেই তৈরি হয়। Wi-Fi বন্ধ করেও কাজ করে।" },
      { question: "v4 আর v7-এর পার্থক্য?", answer: "v4-তে ১২২ random bit — কোনো ordering নেই, শুধু uniqueness। v7-এ প্রথমে ৪৮-bit Unix timestamp, তাই ID creation time অনুযায়ী sort হয়। Database primary key-র জন্য v7।" },
      { question: "v4 কতটা random?", answer: "১২২ bit entropy — একটি collision-এর ৫০% সম্ভাবনার জন্য প্রায় ২.৭ × ১০^১৮ UUID লাগবে। কার্যত forever unique।" },
      { question: "v7 কি primary key হিসেবে ব্যবহার করা যায়?", answer: "হ্যাঁ — এটাই মূল use case। Timestamp প্রথমে থাকায় v7 key প্রায় sequential order-এ insert হয়, database index efficient থাকে।" },
      { question: "একবারে কত generate করা যায়?", answer: "প্রতি batch-এ ১০০০ পর্যন্ত। যতবার চান Regenerate চাপুন।" },
      { question: "Hyphen বাদ দেওয়া যায়?", answer: "হ্যাঁ — hyphens বন্ধ করলে ৩২-character hex string পাবেন (short ID বা URL slug-এ ব্যবহার হয়)।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "UUID Web Crypto API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই তৈরি হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type UuidGeneratorContent = typeof uuidGeneratorContent;
