export const pdfToTextContent = {
  en: {
    heroTag: "PDF to Text",
    heroSubtitle:
      "Extract plain text from any PDF — right in your browser. Pick pages, keep or collapse line breaks, download a .txt file or copy to clipboard. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Pure text", label: "Output" },
      { value: "100%", label: "Private" },
      { value: "Page ranges", label: "Supported" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "PDF never leaves your device." },
      { emoji: "📝", title: "Clean text", text: "Paragraph and line breaks preserved." },
      { emoji: "🎯", title: "Page ranges", text: "Extract only the pages you need." },
      { emoji: "📋", title: "Copy or download", text: "Get .txt file or clipboard." },
      { emoji: "💾", title: "No uploads", text: "Everything runs locally." },
      { emoji: "🌐", title: "UTF-8 output", text: "Bangla, English, Arabic — all supported." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "PDF to Text reads the text layer inside your PDF and extracts it as plain text. Every PDF that contains selectable text — reports, ebooks, contracts, invoices — has an invisible text layer behind the pixels. This tool pulls that text out, preserving paragraph and line structure where possible, and gives you a .txt file or clipboard copy." },
      { emoji: "📄", title: "When you need it", text: "Copy quotes from a research paper, translate an article, feed a PDF into a text-processing workflow, or index a document for search. Instead of opening the PDF, selecting by hand, and pasting into another app, this tool does the whole thing in one step." },
      { emoji: "⚡", title: "How the extraction works", text: "PDF.js parses the file, walks through each page's text items, and reconstructs a readable stream — inserting spaces between items and line breaks where the PDF signals the end of a line. Whitespace is cleaned, extra blank lines collapsed, and the result is written as UTF-8 plain text." },
      { emoji: "⚠️", title: "What it cannot do", text: "Scanned PDFs (images of pages) have no text layer, so this tool returns empty results for them. If you need to extract text from a scan, you need OCR — that's a different tool." },
    ],
    howToTitle: "How to extract text from PDF",
    howTo: [
      { step: 1, title: "Drop your PDF", description: "Drag a PDF file into the upload area, or click to browse. Up to 100 MB." },
      { step: 2, title: "Choose pages and options", description: "Pick specific page ranges (e.g. 1-3, 5) or all pages. Choose whether to keep line breaks and add page markers." },
      { step: 3, title: "Extract", description: "Click Extract. The text is pulled out in your browser and shown with per-page stats." },
      { step: 4, title: "Copy or download", description: "Copy the text to your clipboard or download it as a .txt file." },
    ],
    featuresTitle: "Built for real PDFs",
    features: [
      { emoji: "📝", title: "Structure aware", description: "Paragraphs and line breaks preserved when you want them." },
      { emoji: "🔒", title: "Zero uploads", description: "PDF parsing happens entirely in your browser." },
      { emoji: "🎯", title: "Page ranges", description: "Extract just what you need: 1-3, 5, 7-9 — or everything." },
      { emoji: "📋", title: "One-click copy", description: "Copy the full text to your clipboard instantly." },
      { emoji: "🌐", title: "UTF-8 safe", description: "Bangla, Arabic, Chinese, emoji — all preserved correctly." },
      { emoji: "📄", title: "Any size", description: "Up to 100 MB per PDF. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my PDF uploaded?", answer: "No. Everything happens inside your browser using pdf.js. Your file never leaves your device." },
      { question: "Why is the extracted text empty?", answer: "Your PDF is probably a scan — images of pages with no text layer. Use OCR software for that. This tool only extracts existing text." },
      { question: "What is 'preserve line breaks'?", answer: "When ON, the tool keeps the PDF's original line breaks (useful for poems, code, structured documents). When OFF, it collapses everything into flowing paragraphs." },
      { question: "What does 'page separators' do?", answer: "When ON, each page's text is preceded by a '--- Page N ---' marker, so you can see where pages begin. Useful for large documents." },
      { question: "Can I extract just a few pages?", answer: "Yes. Enter ranges like 1-3, 5, 7-9 in the page field, or leave it empty to extract every page." },
      { question: "Does it work with Bangla, Arabic, or Chinese?", answer: "Yes — as long as the PDF has a proper text layer. Output is UTF-8 plain text and preserves any script." },
      { question: "Does it work on mobile?", answer: "Yes. Large PDFs may take longer on phones, but the tool is fully responsive." },
    ],
    privacyNote: "Your PDF is parsed and its text is extracted entirely inside your browser using pdf.js. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF থেকে টেক্সট",
    heroSubtitle:
      "যেকোনো PDF থেকে প্লেন টেক্সট বের করুন — সম্পূর্ণ আপনার ব্রাউজারেই। পেজ বাছুন, লাইন ব্রেক রাখুন বা বাদ দিন, .txt ফাইল ডাউনলোড করুন বা ক্লিপবোর্ডে কপি করুন।",
    heroStats: [
      { value: "প্লেন টেক্সট", label: "আউটপুট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "পেজ রেঞ্জ", label: "সাপোর্টেড" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "PDF কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "📝", title: "পরিষ্কার টেক্সট", text: "অনুচ্ছেদ ও লাইন ব্রেক রাখা হয়।" },
      { emoji: "🎯", title: "পেজ রেঞ্জ", text: "যে পেজ দরকার শুধু তা বের করুন।" },
      { emoji: "📋", title: "কপি বা ডাউনলোড", text: ".txt ফাইল বা ক্লিপবোর্ড।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "🌐", title: "UTF-8 আউটপুট", text: "বাংলা, ইংরেজি, আরবি — সব সাপোর্টেড।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "PDF to Text আপনার PDF-এর ভেতরে থাকা text layer পড়ে প্লেন টেক্সট হিসেবে বের করে। যেকোনো PDF যাতে selectable text আছে — রিপোর্ট, ebook, চুক্তি, ইনভয়েস — তার পিক্সেলের পিছনে একটি অদৃশ্য text layer থাকে। এই টুল সেটি বের করে, যতটা সম্ভব paragraph ও line structure রাখে, এবং .txt ফাইল বা clipboard copy দেয়।" },
      { emoji: "📄", title: "কখন দরকার", text: "গবেষণা পত্র থেকে quote কপি করা, আর্টিকেল অনুবাদ করা, PDF-কে text-processing workflow-এ পাঠানো, বা সার্চের জন্য index করা। হাতে PDF খুলে text সিলেক্ট করে অন্য অ্যাপে paste করার বদলে এই টুল এক ধাপেই সব করে দেয়।" },
      { emoji: "⚡", title: "এক্সট্রাকশন কীভাবে কাজ করে", text: "PDF.js ফাইলটি parse করে, প্রতিটি পেজের text item-এ চলে, এবং একটি পাঠযোগ্য stream পুনর্গঠন করে — item-এর মাঝে space এবং যেখানে PDF line শেষ হওয়ার signal দেয় সেখানে newline দেয়। অতিরিক্ত whitespace পরিষ্কার করা হয়, অতিরিক্ত blank line সংকুচিত হয়, এবং ফলাফল UTF-8 plain text হিসেবে লেখা হয়।" },
      { emoji: "⚠️", title: "যা করতে পারে না", text: "স্ক্যান করা PDF (পেজের ছবি) তে text layer থাকে না, তাই এই টুল সেগুলোর জন্য খালি result দেয়। স্ক্যান থেকে text বের করতে OCR লাগবে — সেটা আলাদা টুল।" },
    ],
    howToTitle: "PDF থেকে টেক্সট কীভাবে বের করবেন",
    howTo: [
      { step: 1, title: "PDF দিন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ১০০ MB পর্যন্ত।" },
      { step: 2, title: "পেজ ও অপশন বাছুন", description: "নির্দিষ্ট পেজ রেঞ্জ (যেমন 1-3, 5) বা সব পেজ বেছে নিন। লাইন ব্রেক রাখবেন কি না, page marker যোগ করবেন কি না — সেটাও ঠিক করুন।" },
      { step: 3, title: "Extract করুন", description: "Extract চাপুন। আপনার ব্রাউজারেই text বের হয় ও per-page stats দেখানো হয়।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "Text clipboard-এ কপি করুন বা .txt ফাইল হিসেবে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত PDF-এর জন্য তৈরি",
    features: [
      { emoji: "📝", title: "Structure সচেতন", description: "চাইলে paragraph ও line break সংরক্ষিত থাকে।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "PDF parsing সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "🎯", title: "পেজ রেঞ্জ", description: "যা দরকার তাই: 1-3, 5, 7-9 — বা সব।" },
      { emoji: "📋", title: "এক ক্লিকে কপি", description: "পুরো text সাথে সাথে clipboard-এ।" },
      { emoji: "🌐", title: "UTF-8 নিরাপদ", description: "বাংলা, আরবি, চাইনিজ, emoji — সব ঠিকভাবে সংরক্ষিত।" },
      { emoji: "📄", title: "যেকোনো সাইজ", description: "প্রতি PDF-এ ১০০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf.js দিয়ে সবকিছু আপনার ব্রাউজারেই। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "Text খালি আসছে কেন?", answer: "আপনার PDF সম্ভবত স্ক্যান — পেজের ছবি, যাতে text layer নেই। এজন্য OCR দরকার। এই টুল শুধু বিদ্যমান text বের করে।" },
      { question: "‘লাইন ব্রেক রাখুন’ মানে কী?", answer: "ON থাকলে PDF-এর মূল line break রাখা হয় (কবিতা, কোড, structured ডকুমেন্টের জন্য কাজে লাগে)। OFF থাকলে সব flowing paragraph-এ পরিণত হয়।" },
      { question: "‘পেজ সেপারেটর’ কী করে?", answer: "ON থাকলে প্রতিটি পেজের আগে '--- Page N ---' marker বসে, যাতে পেজ কোথায় শুরু বোঝা যায়। বড় ডকুমেন্টের জন্য দরকারি।" },
      { question: "শুধু কয়েকটা পেজ করা যায়?", answer: "হ্যাঁ। Page field-এ 1-3, 5, 7-9 লিখুন, বা খালি রাখলে সব পেজ।" },
      { question: "বাংলা, আরবি বা চাইনিজে কাজ করে?", answer: "হ্যাঁ — যতক্ষণ PDF-এ সঠিক text layer আছে। আউটপুট UTF-8 plain text, সব script সংরক্ষিত।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। বড় PDF-এ ফোনে কিছুটা সময় লাগতে পারে, তবে fully responsive।" },
    ],
    privacyNote: "আপনার PDF pdf.js দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই parse ও text extract হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type PdfToTextContent = typeof pdfToTextContent;
