export const imageCropperContent = {
  en: {
    heroTag: "Image Cropper",
    heroSubtitle:
      "Crop JPG, PNG, and WebP images right in your browser. Drag the crop box, pick from aspect ratio presets (square, story, cover, thumbnail), and download — all without a single upload.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Live", label: "Preview" },
      { value: "8", label: "Presets" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Live crop preview", text: "See exactly what you'll get." },
      { emoji: "📐", title: "8 aspect presets", text: "Square, story, cover, thumbnail, and more." },
      { emoji: "🎯", title: "Pixel-precise", text: "Type exact crop coordinates if you want." },
      { emoji: "🎨", title: "Lossless formats", text: "PNG and WebP keep transparency." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Image Cropper lets you trim any JPG, PNG, or WebP image to the exact area you want. Upload a photo, drag or type the crop rectangle, choose an optional aspect ratio, and export the crop as a new image. Everything happens locally in your browser using the HTML5 Canvas API — no uploads, no servers, no accounts." },
      { emoji: "📐", icon: "target", title: "Why aspect presets matter", text: "Social platforms and print shops require specific dimensions — a square for Instagram feeds, a 9:16 rectangle for Stories and Reels, 16:9 for YouTube thumbnails, 4:3 for classic photos. This tool ships eight common aspect presets so you can frame your crop correctly without leaving the page." },
      { emoji: "⚡", icon: "printer", title: "How the crop works", text: "The tool reads your image into an off-screen canvas at full resolution, then redraws only the crop rectangle onto a new canvas. Because everything happens at native pixel resolution, the resulting image has no quality loss from the crop operation itself. PNG and WebP crops keep transparency; JPG crops fill any transparent areas with white." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your files is gone from memory." },
    ],
    howToTitle: "How to crop an image",
    howTo: [
      { step: 1, title: "Drop your image", description: "Drag JPG, PNG, or WebP files into the upload area, or click to browse. Up to 50 MB per file." },
      { step: 2, title: "Adjust the crop box", description: "Drag the crop rectangle on the preview. Use the corner handles to resize, or type exact X, Y, W, H in the fields." },
      { step: 3, title: "Pick an aspect ratio (optional)", description: "Choose Free, 1:1, 4:3, 16:9, or any other preset. The crop box snaps to that ratio." },
      { step: 4, title: "Download the crop", description: "Click Download to save the cropped image as a new file in the original format." },
    ],
    featuresTitle: "Built for real cropping",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "The image is read and processed entirely in your browser. Nothing travels over the network." },
      { emoji: "⚡", title: "Live preview", description: "Every drag or typed coordinate updates the crop rectangle in real time." },
      { emoji: "📐", title: "8 aspect presets", description: "Square, 4:3, 3:4, 16:9, 9:16 Story, 3:2, 2:3, and Free." },
      { emoji: "🎯", title: "Type exact values", description: "For pixel-perfect control, type X, Y, W, and H directly into the number fields." },
      { emoji: "🎨", title: "Format preserved", description: "JPG stays JPG, PNG stays PNG, WebP stays WebP — with transparency preserved." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser using the Canvas API. Your files never leave your device." },
      { question: "Can I crop multiple images at once?", answer: "Not in this version. The cropper works on one image at a time — but you can crop as many images as you want by re-running the tool." },
      { question: "What aspect ratios are available?", answer: "Free, 1:1 Square, 4:3, 3:4, 16:9, 9:16 Story, 3:2, and 2:3. You can also type any custom crop rectangle." },
      { question: "Will the quality drop?", answer: "No. The crop is a pure pixel copy — every pixel in the new image comes from the original at full resolution, with no re-sampling." },
      { question: "Does it work on transparent PNGs?", answer: "Yes. Transparency is preserved for PNG and WebP. JPG crops fill any transparent areas with white, since JPG has no alpha channel." },
      { question: "Can I undo a crop?", answer: "Click the Reset button to return the crop rectangle to the full image. The original file is never modified." },
      { question: "What image formats are supported?", answer: "JPG, JPEG, PNG, and WebP. Output stays in the same format as the input." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ ক্রপার",
    heroSubtitle:
      "JPG, PNG এবং WebP ছবি সম্পূর্ণ আপনার ব্রাউজারেই ক্রপ করুন। ক্রপ বক্স ড্র্যাগ করুন, aspect ratio প্রিসেট (স্কয়ার, স্টোরি, কভার, থাম্বনেইল) বেছে নিন, এবং ডাউনলোড করুন।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "লাইভ", label: "প্রিভিউ" },
      { value: "৮", label: "প্রিসেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "লাইভ ক্রপ প্রিভিউ", text: "ঠিক কী পাবেন তা দেখুন।" },
      { emoji: "📐", title: "৮টি aspect প্রিসেট", text: "স্কয়ার, স্টোরি, কভার, থাম্বনেইল।" },
      { emoji: "🎯", title: "পিক্সেল-সঠিক", text: "চাইলে সঠিক কোঅর্ডিনেট টাইপ করুন।" },
      { emoji: "🎨", title: "লসলেস ফরম্যাট", text: "PNG ও WebP স্বচ্ছতা রাখে।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি হয়।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "ইমেজ ক্রপার যেকোনো JPG, PNG বা WebP ছবি ঠিক যে অংশ চান সেখানে কাটতে দেয়। ছবি আপলোড করুন, ক্রপ রেক্ট্যাঙ্গল ড্র্যাগ বা টাইপ করুন, ঐচ্ছিক aspect ratio বেছে নিন, এবং নতুন ছবি হিসেবে এক্সপোর্ট করুন। সবকিছু HTML5 Canvas API দিয়ে ব্রাউজারেই হয়।" },
      { emoji: "📐", icon: "target", title: "কেন aspect প্রিসেট দরকার", text: "সোশ্যাল প্ল্যাটফর্ম ও প্রিন্ট শপ নির্দিষ্ট মাপ চায় — Instagram-এ স্কয়ার, Stories/Reels-এ 9:16, YouTube থাম্বনেইলে 16:9, ক্লাসিক ছবিতে 4:3। এই টুলে ৮টি কমন aspect প্রিসেট আছে।" },
      { emoji: "⚡", icon: "printer", title: "ক্রপ কীভাবে কাজ করে", text: "টুলটি আপনার ছবিটি full resolution-এ off-screen canvas-এ পড়ে, তারপর কেবল ক্রপ রেক্ট্যাঙ্গল নতুন canvas-এ আঁকে। native pixel resolution-এ হওয়ায় ক্রপ থেকে কোনো কোয়ালিটি লস হয় না।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "ছবি কীভাবে ক্রপ করবেন",
    howTo: [
      { step: 1, title: "আপনার ছবি দিন", description: "JPG, PNG বা WebP ফাইল ড্র্যাগ করুন বা ক্লিক করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "ক্রপ বক্স ঠিক করুন", description: "প্রিভিউতে ক্রপ রেক্ট্যাঙ্গল ড্র্যাগ করুন। কোণার হ্যান্ডেল দিয়ে রিসাইজ করুন, বা সঠিক X, Y, W, H টাইপ করুন।" },
      { step: 3, title: "Aspect ratio বেছে নিন (ঐচ্ছিক)", description: "Free, 1:1, 4:3, 16:9 বা অন্য প্রিসেট বেছে নিন। ক্রপ বক্স সেই অনুপাতে স্ন্যাপ করবে।" },
      { step: 4, title: "ক্রপ ডাউনলোড করুন", description: "Download চাপুন ক্রপ করা ছবি মূল ফরম্যাটে সেভ করতে।" },
    ],
    featuresTitle: "প্রকৃত ক্রপিংয়ের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ছবি সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও প্রসেস করা হয়।" },
      { emoji: "⚡", title: "লাইভ প্রিভিউ", description: "প্রতিটি ড্র্যাগ বা টাইপ করা কোঅর্ডিনেট রিয়েল-টাইমে আপডেট হয়।" },
      { emoji: "📐", title: "৮টি aspect প্রিসেট", description: "Square, 4:3, 3:4, 16:9, 9:16 Story, 3:2, 2:3, এবং Free।" },
      { emoji: "🎯", title: "সঠিক মান টাইপ করুন", description: "পিক্সেল-পারফেক্ট কন্ট্রোলের জন্য সরাসরি X, Y, W, H টাইপ করুন।" },
      { emoji: "🎨", title: "ফরম্যাট সংরক্ষিত", description: "JPG JPG থাকে, PNG PNG থাকে, WebP WebP থাকে — স্বচ্ছতা সহ।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ফাইল কি আপলোড হয়?", answer: "না। Canvas API দিয়ে সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "একসাথে একাধিক ছবি ক্রপ করা যায়?", answer: "এই সংস্করণে একটা করে। তবে টুল পুনরায় চালিয়ে যত চান ক্রপ করতে পারেন।" },
      { question: "কোন aspect ratio পাওয়া যায়?", answer: "Free, 1:1 স্কয়ার, 4:3, 3:4, 16:9, 9:16 Story, 3:2, 2:3।" },
      { question: "কোয়ালিটি কমবে?", answer: "না। ক্রপ একটি পিক্সেল কপি — প্রতিটি পিক্সেল full resolution-এ আসে।" },
      { question: "স্বচ্ছ PNG-এ কাজ করে?", answer: "হ্যাঁ। PNG ও WebP স্বচ্ছতা সংরক্ষিত। JPG-এ স্বচ্ছ অংশ সাদা হয়।" },
      { question: "ক্রপ undo করা যায়?", answer: "Reset চাপলে ক্রপ বক্স পুরো ছবিতে ফিরে যায়। মূল ফাইল কখনো পরিবর্তিত হয় না।" },
      { question: "কোন ফরম্যাট সাপোর্টেড?", answer: "JPG, JPEG, PNG এবং WebP।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারে প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageCropperContent = typeof imageCropperContent;
