export const imageToSketchContent = {
  en: {
    heroTag: "Image to Sketch",
    heroSubtitle:
      "Turn any photo into a hand-drawn pencil sketch — right in your browser. Two sliders control stroke darkness and line thickness. Download as PNG. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Pencil", label: "Effect" },
      { value: "100%", label: "Private" },
      { value: "Live", label: "Preview" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Photos never leave your device." },
      { emoji: "✏️", title: "Real pencil look", text: "Classic color-dodge sketch algorithm." },
      { emoji: "🎚️", title: "Live sliders", text: "Adjust intensity & detail in real time." },
      { emoji: "⚡", title: "Instant", text: "Renders in under a second." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
      { emoji: "🖼️", title: "PNG export", text: "High-res, ready to share." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Image to Sketch converts a photo into a graphite-pencil drawing. It grayscales the source, inverts it, blurs the inverse, then color-dodges the two together — producing dark lines wherever the original had edges and clean white paper everywhere else. Two sliders let you fine-tune how dark and how thick the strokes look." },
      { emoji: "📄", title: "When you need it", text: "Turn a portrait into an art print. Generate a sketch-style illustration for a blog header. Give a client a soft preview of a photo before retouching. Create a hand-drawn look for social media without opening Photoshop. It's a one-click filter — perfect for quick creative experiments." },
      { emoji: "⚡", title: "How it works", text: "Everything is done with the Canvas API. First the image is drawn onto a canvas and pixel data is read. Grayscale + inversion convert each pixel to its negative luminance. A sliding-window box blur (an O(n) approximation of a Gaussian) softens the inverse. Finally, the color-dodge blend divides grayscale by the inverse of the blurred image, clipping at 255 — the same math Photoshop's sketch filters use." },
      { emoji: "🔐", title: "Your photos stay with you", text: "There is no server. No accounts. No analytics. Your photos — portraits, IDs, private shots — stay entirely inside your browser. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to turn a photo into a sketch",
    howTo: [
      { step: 1, title: "Drop your photo", description: "Drag a JPG, PNG, or WebP into the upload area, or click to browse. Up to 25 MB." },
      { step: 2, title: "Adjust the sliders", description: "Intensity controls how dark the strokes are; Detail controls line thickness." },
      { step: 3, title: "Watch the preview", description: "The sketch updates live as you move the sliders — no button required." },
      { step: 4, title: "Download PNG", description: "Click Download to save the sketch as a PNG image." },
    ],
    featuresTitle: "Built for real sketch output",
    features: [
      { emoji: "✏️", title: "Authentic pencil look", description: "Color-dodge algorithm produces soft graphite strokes, not hard edges." },
      { emoji: "🎚️", title: "Live sliders", description: "Intensity and detail adjust in real time — see the result as you tune." },
      { emoji: "🔒", title: "Zero uploads", description: "Every pixel stays inside your browser." },
      { emoji: "⚡", title: "Fast", description: "Optimized blur runs in under a second on most photos." },
      { emoji: "📐", title: "Up to 2000px", description: "Large photos auto-downscale to keep processing smooth." },
      { emoji: "💾", title: "Any size", description: "Uploads up to 25 MB. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my photo uploaded?", answer: "No. Everything happens in your browser using the Canvas API. Your photo never leaves your device." },
      { question: "What does the Intensity slider do?", answer: "It controls how dark the pencil strokes are. Lower values produce a light, subtle sketch; higher values produce dark, bold lines." },
      { question: "What does the Detail slider do?", answer: "It controls the blur radius of the inverted layer, which determines line thickness. Lower values give fine, thin lines; higher values give thicker, softer strokes." },
      { question: "Why does my photo look less like a sketch?", answer: "Photos with strong contrast, clear subjects, and simple backgrounds work best. Very busy scenes can produce a noisy result — try adjusting Detail to smooth it out." },
      { question: "Will the sketch be in color?", answer: "No — this tool outputs a grayscale pencil sketch by design. That's what gives it the graphite look." },
      { question: "What's the maximum image size?", answer: "Uploads up to 25 MB. Images larger than 2000px on their long edge are automatically downscaled before processing to keep things fast." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your photo is processed entirely inside your browser using the Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ থেকে স্কেচ",
    heroSubtitle:
      "যেকোনো ছবিকে হাতে-আঁকা পেন্সিল স্কেচে পরিণত করুন — সম্পূর্ণ আপনার ব্রাউজারেই। দুইটি স্লাইডার দিয়ে stroke-এর গাঢ়তা ও লাইন-মোটা নিয়ন্ত্রণ করুন। PNG ডাউনলোড।",
    heroStats: [
      { value: "পেন্সিল", label: "ইফেক্ট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "লাইভ", label: "Preview" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ছবি কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "✏️", title: "প্রকৃত পেন্সিল look", text: "ক্লাসিক color-dodge স্কেচ অ্যালগরিদম।" },
      { emoji: "🎚️", title: "লাইভ স্লাইডার", text: "Intensity ও detail রিয়েল-টাইমে ঠিক করুন।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", text: "সেকেন্ডের কমে render হয়।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "🖼️", title: "PNG export", text: "হাই-রেজ, শেয়ার করার জন্য ready।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Image to Sketch একটি ছবিকে গ্রাফাইট-পেন্সিল ড্রয়িংয়ে রূপান্তর করে। এটি ছবিকে grayscale করে, invert করে, inverse-কে blur করে, তারপর দুটোকে color-dodge করে — যেখানে মূল ছবিতে edge ছিল সেখানে গাঢ় লাইন, আর বাকি জায়গায় পরিষ্কার সাদা কাগজ তৈরি করে। দুইটি স্লাইডার দিয়ে stroke-এর গাঢ়তা ও মোটা নিয়ন্ত্রণ করা যায়।" },
      { emoji: "📄", title: "কখন দরকার", text: "একটি পোর্ট্রেটকে art print-এ পরিণত করা। ব্লগ হেডারের জন্য sketch-style illustration তৈরি করা। retouch করার আগে ক্লায়েন্টকে soft preview দেওয়া। Photoshop খোলা ছাড়াই সোশ্যাল মিডিয়ার জন্য hand-drawn look বানানো। এক-ক্লিকের filter — দ্রুত creative experiment-এর জন্য perfect।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "সবকিছু Canvas API দিয়ে করা হয়। প্রথমে ছবিকে canvas-এ এঁকে pixel data পড়া হয়। Grayscale + inversion প্রতিটি pixel-কে তার negative luminance-এ রূপান্তর করে। Sliding-window box blur (Gaussian-এর O(n) approximation) inverse-কে soft করে। শেষে color-dodge blend grayscale-কে blurred inverse দিয়ে ভাগ করে, 255-এ clip করে — Photoshop-এর sketch filter-এর মতো একই গণিত।" },
      { emoji: "🔐", title: "আপনার ছবি আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। আপনার ছবি — পোর্ট্রেট, আইডি, ব্যক্তিগত ছবি — সম্পূর্ণ আপনার ব্রাউজারেই থাকে।" },
    ],
    howToTitle: "ছবিকে স্কেচে কীভাবে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "ছবি দিন", description: "JPG, PNG বা WebP ড্র্যাগ করুন বা ক্লিক করুন। ২৫ MB পর্যন্ত।" },
      { step: 2, title: "স্লাইডার ঠিক করুন", description: "Intensity stroke-এর গাঢ়তা নিয়ন্ত্রণ করে; Detail লাইনের মোটা নিয়ন্ত্রণ করে।" },
      { step: 3, title: "Preview দেখুন", description: "স্লাইডার সরানোর সাথে সাথে sketch লাইভ আপডেট হয়।" },
      { step: 4, title: "PNG ডাউনলোড", description: "Download চেপে sketch PNG হিসেবে সেভ করুন।" },
    ],
    featuresTitle: "প্রকৃত স্কেচ আউটপুটের জন্য",
    features: [
      { emoji: "✏️", title: "আসল পেন্সিল look", description: "Color-dodge অ্যালগরিদম নরম গ্রাফাইট stroke দেয়, কঠিন edge নয়।" },
      { emoji: "🎚️", title: "লাইভ স্লাইডার", description: "Intensity ও detail রিয়েল-টাইমে ঠিক হয়।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "প্রতিটি pixel আপনার ব্রাউজারেই থাকে।" },
      { emoji: "⚡", title: "দ্রুত", description: "Optimized blur বেশিরভাগ ছবিতে সেকেন্ডের কমে।" },
      { emoji: "📐", title: "২০০০px পর্যন্ত", description: "বড় ছবি automatically downscale হয় যাতে processing smooth থাকে।" },
      { emoji: "💾", title: "যেকোনো সাইজ", description: "২৫ MB পর্যন্ত upload।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ছবি কি আপলোড হয়?", answer: "না। Canvas API দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "Intensity স্লাইডার কী করে?", answer: "Pencil stroke-এর গাঢ়তা নিয়ন্ত্রণ করে। কম মান = হালকা, subtle sketch; বেশি মান = গাঢ়, bold লাইন।" },
      { question: "Detail স্লাইডার কী করে?", answer: "Inverted layer-এর blur radius নিয়ন্ত্রণ করে — যা লাইনের মোটা নির্ধারণ করে। কম মান = সরু, thin লাইন; বেশি মান = মোটা, নরম stroke।" },
      { question: "আমার ছবি কম sketch দেখায় কেন?", answer: "Strong contrast, পরিষ্কার subject ও simple background সহ ছবি সবচেয়ে ভালো কাজ করে। খুব busy scene noisy হতে পারে — Detail কমান।" },
      { question: "Sketch কি রঙিন হবে?", answer: "না — এই টুল শুধু grayscale পেন্সিল sketch দেয়, যেটাই graphite look দেয়।" },
      { question: "সর্বোচ্চ ছবি সাইজ কত?", answer: "২৫ MB পর্যন্ত। ২০০০px-এর বড় ছবি automatically downscale হয়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageToSketchContent = typeof imageToSketchContent;
