export const passwordGenContent = {
  en: {
    heroTag: "Password Generator",
    heroSubtitle:
      "Generate strong, cryptographically random passwords in your browser. Control length, character sets, ambiguity, and batch size. See live strength and crack-time estimates. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Crypto", label: "Random" },
      { value: "128 max", label: "Length" },
      { value: "100%", label: "Private" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Passwords never leave your device." },
      { emoji: "🎲", title: "Crypto-random", text: "Web Crypto API, not Math.random." },
      { emoji: "🎚️", title: "Full control", text: "Length, sets, ambiguity, batch." },
      { emoji: "💪", title: "Live strength", text: "Entropy + crack-time estimate." },
      { emoji: "📦", title: "Batch up to 50", text: "Generate many, copy or download." },
      { emoji: "📋", title: "Copy / download", text: "One-click clipboard or .txt." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Password Generator creates strong, random passwords using the browser's cryptographic random number generator — the same source TLS uses, not the predictable Math.random. Choose length (4–128), toggle character sets (lowercase, uppercase, numbers, symbols), optionally exclude ambiguous characters like 0/O and 1/l/I, and generate up to 50 at once." },
      { emoji: "📄", title: "When you need it", text: "Signing up for a new service. Rotating credentials after a breach. Creating API keys. Generating database passwords. Testing password strength. Anywhere you need a value that can't be guessed — this tool has you covered without uploading a single character." },
      { emoji: "⚡", title: "How randomness works", text: "Every character is picked via crypto.getRandomValues with rejection sampling — a technique that removes modulo bias, so all outcomes are exactly equally likely. If 'require each' is on, the generator guarantees at least one character from each selected set, then Fisher-Yates shuffles the result using the same secure source." },
      { emoji: "🔐", title: "Your passwords stay with you", text: "There is no server. No accounts. No analytics. Every password is generated entirely in your browser — never transmitted, never logged, never stored. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to generate a strong password",
    howTo: [
      { step: 1, title: "Set the length", description: "Pick from 4 to 128 characters. 16+ is recommended for accounts that matter." },
      { step: 2, title: "Toggle character sets", description: "Lowercase, uppercase, numbers, symbols. Use all four for maximum strength." },
      { step: 3, title: "Fine-tune options", description: "Exclude ambiguous characters (0/O, 1/l/I) or require at least one from each set." },
      { step: 4, title: "Copy or download", description: "Copy individual passwords or download the whole batch as a .txt file." },
    ],
    featuresTitle: "Built for real password work",
    features: [
      { emoji: "🎲", title: "Cryptographically secure", description: "Uses Web Crypto API with rejection sampling — no modulo bias." },
      { emoji: "🎚️", title: "Full control", description: "Length, character sets, ambiguous exclusion, require-each rule." },
      { emoji: "💪", title: "Strength analysis", description: "Entropy in bits plus estimated offline crack time." },
      { emoji: "📦", title: "Batch up to 50", description: "Generate many at once — perfect for credential rotation." },
      { emoji: "👁️", title: "Show/hide toggle", description: "Reveal passwords with one click to verify visually." },
      { emoji: "🔒", title: "Zero uploads", description: "Everything happens in your browser — works offline." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Are passwords sent anywhere?", answer: "No. Every password is generated inside your browser using the Web Crypto API. You can disconnect Wi-Fi and it still works." },
      { question: "How secure are the generated passwords?", answer: "The random source is crypto.getRandomValues — the same cryptographically secure RNG that browsers use for TLS keys. Unlike Math.random (predictable), this is safe for real-world use." },
      { question: "What length should I use?", answer: "16+ characters for important accounts. 20+ for password managers, API keys, or anything long-lived. 12 is the acceptable minimum; below that, offline attacks become feasible." },
      { question: "Should I include symbols?", answer: "Yes — adding symbols increases the pool size, which increases entropy per character. A 16-char password with all four sets has ~105 bits of entropy; without symbols it's ~92 bits." },
      { question: "What does 'exclude ambiguous' do?", answer: "It removes characters that look similar in certain fonts — 0 (zero) vs O (letter), 1 (one) vs l (lowercase L) vs I (uppercase i). Useful when you must type the password by hand." },
      { question: "What does 'require each' do?", answer: "Guarantees at least one character from every enabled set. Some services require this explicitly; others don't care." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Passwords are generated entirely inside your browser using the Web Crypto API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "পাসওয়ার্ড জেনারেটর",
    heroSubtitle:
      "ব্রাউজারেই শক্তিশালী, ক্রিপ্টোগ্রাফিক্যালি র‍্যান্ডম পাসওয়ার্ড তৈরি করুন। দৈর্ঘ্য, character set, ambiguity ও batch size নিয়ন্ত্রণ করুন। লাইভ strength ও crack-time। কোনো আপলোড নেই।",
    heroStats: [
      { value: "Crypto", label: "Random" },
      { value: "১২৮ সর্বোচ্চ", label: "দৈর্ঘ্য" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "পাসওয়ার্ড কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎲", title: "Crypto-random", text: "Web Crypto API, Math.random নয়।" },
      { emoji: "🎚️", title: "সম্পূর্ণ নিয়ন্ত্রণ", text: "Length, set, ambiguity, batch।" },
      { emoji: "💪", title: "লাইভ strength", text: "Entropy + crack-time estimate।" },
      { emoji: "📦", title: "৫০ পর্যন্ত ব্যাচ", text: "অনেক একসাথে, copy বা download।" },
      { emoji: "📋", title: "কপি / ডাউনলোড", text: "এক ক্লিকে clipboard বা .txt।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Password Generator browser-এর cryptographic random number generator দিয়ে শক্তিশালী, random password তৈরি করে — যেটা TLS ব্যবহার করে, predictable Math.random নয়। Length (৪–১২৮), character set (lowercase, uppercase, numbers, symbols), ambiguity বাদ (0/O, 1/l/I) — সব ঠিক করুন, একবারে ৫০টা পর্যন্ত generate করুন।" },
      { emoji: "📄", title: "কখন দরকার", text: "নতুন service-এ sign-up। Breach-এর পর credential rotate। API key তৈরি। Database password। Password strength test। যেখানে unguessable মান দরকার — এই টুল এক character-ও upload না করে কাজ করে।" },
      { emoji: "⚡", title: "Randomness কীভাবে কাজ করে", text: "প্রতিটি character crypto.getRandomValues + rejection sampling দিয়ে নেওয়া — যেটা modulo bias বাদ দেয়, তাই সব outcome exactly সমান সম্ভাব্য। ‘Require each’ চালু থাকলে generator প্রতিটি set থেকে অন্তত একটা character guarantee করে, তারপর Fisher-Yates সেই একই secure source দিয়ে shuffle করে।" },
      { emoji: "🔐", title: "আপনার পাসওয়ার্ড আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। প্রতিটি password সম্পূর্ণ আপনার ব্রাউজারেই তৈরি — কখনো transmitted, logged বা stored নয়।" },
    ],
    howToTitle: "শক্তিশালী পাসওয়ার্ড কীভাবে তৈরি করবেন",
    howTo: [
      { step: 1, title: "দৈর্ঘ্য সেট করুন", description: "৪ থেকে ১২৮ character। গুরুত্বপূর্ণ account-এর জন্য ১৬+ recommended।" },
      { step: 2, title: "Character set টগল করুন", description: "Lowercase, uppercase, numbers, symbols। Maximum strength-এর জন্য চারটাই।" },
      { step: 3, title: "Fine-tune করুন", description: "Ambiguous character (0/O, 1/l/I) বাদ দিন বা require-each rule চালু করুন।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "আলাদা password কপি করুন বা পুরো batch .txt হিসেবে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত পাসওয়ার্ড কাজের জন্য",
    features: [
      { emoji: "🎲", title: "Cryptographically secure", description: "Web Crypto API + rejection sampling — কোনো modulo bias নেই।" },
      { emoji: "🎚️", title: "সম্পূর্ণ নিয়ন্ত্রণ", description: "Length, character set, ambiguity exclusion, require-each rule।" },
      { emoji: "💪", title: "Strength analysis", description: "Entropy (bit) + estimated offline crack time।" },
      { emoji: "📦", title: "৫০ পর্যন্ত ব্যাচ", description: "একসাথে অনেক — credential rotation-এর জন্য perfect।" },
      { emoji: "👁️", title: "Show/hide toggle", description: "এক ক্লিকে password reveal করে visually verify করুন।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "সবকিছু ব্রাউজারেই — offline-ও কাজ করে।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "Password কি কোথাও পাঠানো হয়?", answer: "না। Web Crypto API দিয়ে প্রতিটি password আপনার ব্রাউজারেই তৈরি। Wi-Fi বন্ধ করেও কাজ করে।" },
      { question: "Password কতটা secure?", answer: "Random source হলো crypto.getRandomValues — browser TLS key-তে যেটা ব্যবহার করে। Math.random (predictable) নয়, তাই real-world use-এ safe।" },
      { question: "কত length নেব?", answer: "গুরুত্বপূর্ণ account-এর জন্য ১৬+। Password manager, API key বা long-lived-এর জন্য ২০+। ১২ সর্বনিম্ন; তার নিচে offline attack সম্ভব।" },
      { question: "Symbol রাখবো?", answer: "হ্যাঁ — symbol যোগ করলে pool size বাড়ে, ফলে প্রতি character-এ entropy বাড়ে। সব চার set সহ ১৬-char password-এ ~১০৫ bit entropy; symbol ছাড়া ~৯২ bit।" },
      { question: "‘Exclude ambiguous’ কী করে?", answer: "এমন character বাদ দেয় যেগুলো কিছু font-এ দেখতে একই রকম — 0 (শূন্য) vs O, 1 vs l vs I। হাতে type করতে হলে useful।" },
      { question: "‘Require each’ কী করে?", answer: "প্রতিটি enabled set থেকে অন্তত একটি character guarantee করে। কিছু service এটা explicitly চায়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "Password Web Crypto API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই তৈরি হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type PasswordGenContent = typeof passwordGenContent;
