export const splitPdfContent = {
  en: {
    heroTag: "Split PDF",
    heroSubtitle:
      "Extract pages from any PDF or split it page-by-page — right in your browser. Enter ranges like 1-3, 5, 7-9 or split every page into separate files. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Range", label: "Support" },
      { value: "Local", label: "Processing" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Instant split", text: "Runs in your browser." },
      { emoji: "📄", title: "Custom ranges", text: "Enter 1-3, 5, 7-9 — anything you want." },
      { emoji: "🔀", title: "Two modes", text: "Extract selected pages, or split every page." },
      { emoji: "🎯", title: "Page-exact copy", text: "Pages copied byte-for-byte." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Split PDF extracts specific pages from a PDF file — or breaks every page into its own separate PDF. Type ranges like 1-3, 5, 7-9 and click Extract; each page is copied byte-for-byte into a new PDF. Perfect for pulling a chapter out of a book, isolating a signed page, or slicing a scan into per-page files." },
      { emoji: "📄", icon: "target", title: "When you need it", text: "Extract a signature page to email separately, pull chapter 3 out of a 200-page report, split a scanned batch into one file per page, or remove the cover page from a PDF. Any workflow that needs 'some of these pages' or 'each page separately' is handled here." },
      { emoji: "⚡", icon: "printer", title: "How the split works", text: "The tool uses pdf-lib — a pure-JavaScript PDF library. The source PDF is read into memory, the selected pages are copied into a brand-new PDF document, and the result is written to a Blob for download. No compression, no re-rendering, no network traffic at any point." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your PDF is gone from memory." },
    ],
    howToTitle: "How to split a PDF",
    howTo: [
      { step: 1, title: "Drop your PDF", description: "Drag a PDF file into the upload area, or click to browse. Up to 100 MB." },
      { step: 2, title: "Choose a mode", description: "Extract selected pages (enter ranges like 1-3, 5, 7-9) or split every page into separate files." },
      { step: 3, title: "Enter ranges (if extracting)", description: "Use commas and dashes: '1-3, 5, 7-9' means pages 1 through 3, plus page 5, plus pages 7 through 9." },
      { step: 4, title: "Download", description: "Click Extract (or Split every page). The new PDF(s) build in your browser and download automatically." },
    ],
    featuresTitle: "Built for real splitting",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Files are read and split entirely in your browser." },
      { emoji: "📄", title: "Range parsing", description: "Type '1-3, 5, 7-9' and the tool figures out the exact pages." },
      { emoji: "🔀", title: "Two modes", description: "Extract selected pages into one PDF, or split each page into its own file." },
      { emoji: "🎯", title: "Page-exact copy", description: "Every page is copied byte-for-byte with no re-rendering or quality loss." },
      { emoji: "⚡", title: "Fast processing", description: "Splitting a 200-page PDF typically completes in a few seconds." },
      { emoji: "💾", title: "No size limits", description: "Files up to 100 MB. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my PDFs get uploaded to a server?", answer: "No. Everything happens inside your browser using pdf-lib. Your files never leave your device." },
      { question: "What syntax do I use for page ranges?", answer: "Use commas to separate items and dashes for ranges. '1-3, 5, 7-9' extracts pages 1, 2, 3, 5, 7, 8, 9 (in that order)." },
      { question: "Can I split every page into separate files?", answer: "Yes. Choose 'Split every page' and each page downloads as its own PDF, numbered sequentially." },
      { question: "Can I extract non-contiguous pages?", answer: "Yes. Just list them: '1, 5, 10, 15' extracts exactly those four pages." },
      { question: "Will the PDF quality drop?", answer: "No. Pages are copied byte-for-byte without re-rendering — the split PDFs are identical to the originals." },
      { question: "Can I split an encrypted PDF?", answer: "Encrypted PDFs will fail to load. Decrypt them first with the owner's password before splitting." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your PDF is read and split entirely inside your browser using pdf-lib. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF স্প্লিট",
    heroSubtitle:
      "যেকোনো PDF থেকে পেজ এক্সট্রাক্ট করুন বা পেজ-by-পেজ ভাগ করুন — সম্পূর্ণ আপনার ব্রাউজারেই। '1-3, 5, 7-9' এভাবে রেঞ্জ দিন বা প্রতিটি পেজ আলাদা ফাইলে ভাগ করুন।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "রেঞ্জ", label: "সাপোর্ট" },
      { value: "লোকাল", label: "প্রসেসিং" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক স্প্লিট", text: "ব্রাউজারেই চলে।" },
      { emoji: "📄", title: "কাস্টম রেঞ্জ", text: "1-3, 5, 7-9 — যা চান লিখুন।" },
      { emoji: "🔀", title: "দুই মোড", text: "নির্বাচিত পেজ এক্সট্রাক্ট, বা প্রতিটি আলাদা।" },
      { emoji: "🎯", title: "পেজ-সঠিক কপি", text: "পেজ byte-for-byte কপি হয়।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি হয়।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "Split PDF একটি PDF থেকে নির্দিষ্ট পেজ এক্সট্রাক্ট করে — অথবা প্রতিটি পেজ আলাদা PDF-এ ভাগ করে। '1-3, 5, 7-9' এভাবে রেঞ্জ দিন, Extract চাপুন; প্রতিটি পেজ byte-for-byte নতুন PDF-এ কপি হয়।" },
      { emoji: "📄", icon: "target", title: "কখন দরকার", text: "সিগনেচার পেজ আলাদা ইমেইল করতে, ২০০ পেজের রিপোর্ট থেকে চ্যাপ্টার ৩ বের করতে, স্ক্যান করা ব্যাচ এক পেজে এক ফাইল করতে, বা কভার পেজ বাদ দিতে।" },
      { emoji: "⚡", icon: "printer", title: "স্প্লিট কীভাবে কাজ করে", text: "টুলটি pdf-lib ব্যবহার করে। সোর্স PDF মেমরিতে পড়া হয়, নির্বাচিত পেজ নতুন PDF-এ কপি হয়, এবং ফলাফল Blob হিসেবে সেভ হয়।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "PDF কীভাবে স্প্লিট করবেন",
    howTo: [
      { step: 1, title: "PDF ড্রপ করুন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ১০০ MB পর্যন্ত।" },
      { step: 2, title: "মোড বেছে নিন", description: "নির্বাচিত পেজ এক্সট্রাক্ট (রেঞ্জ লিখুন) বা প্রতিটি পেজ আলাদা ভাগ।" },
      { step: 3, title: "রেঞ্জ লিখুন (এক্সট্রাক্টে)", description: "কমা ও ড্যাশ ব্যবহার করুন: '1-3, 5, 7-9' মানে পেজ ১–৩, প্লাস ৫, প্লাস ৭–৯।" },
      { step: 4, title: "ডাউনলোড", description: "Extract (বা Split every page) চাপুন। নতুন PDF আপনার ব্রাউজারে তৈরি হয়ে ডাউনলোড হয়।" },
    ],
    featuresTitle: "প্রকৃত স্প্লিটের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও স্প্লিট করা হয়।" },
      { emoji: "📄", title: "রেঞ্জ পার্সিং", description: "'1-3, 5, 7-9' লিখুন, টুল সঠিক পেজ বের করে।" },
      { emoji: "🔀", title: "দুই মোড", description: "নির্বাচিত পেজ এক PDF-এ, বা প্রতিটি আলাদা ফাইলে।" },
      { emoji: "🎯", title: "পেজ-সঠিক কপি", description: "প্রতিটি পেজ byte-for-byte কপি হয়।" },
      { emoji: "⚡", title: "দ্রুত প্রসেসিং", description: "২০০ পেজের PDF সাধারণত কয়েক সেকেন্ডে।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "১০০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "রেঞ্জ সিনট্যাক্স কী?", answer: "কমা দিয়ে আলাদা, ড্যাশ দিয়ে রেঞ্জ। '1-3, 5, 7-9' = পেজ ১, ২, ৩, ৫, ৭, ৮, ৯।" },
      { question: "প্রতিটি পেজ আলাদা করা যায়?", answer: "হ্যাঁ। 'Split every page' বেছে নিন — প্রতিটি পেজ আলাদা PDF হিসেবে ডাউনলোড হবে।" },
      { question: "অসমন্বিত পেজ এক্সট্রাক্ট করা যায়?", answer: "হ্যাঁ। '1, 5, 10, 15' এভাবে দিন।" },
      { question: "PDF কোয়ালিটি কমবে?", answer: "না। পেজ byte-for-byte কপি হয়।" },
      { question: "Encrypted PDF স্প্লিট করা যায়?", answer: "না। আগে owner password দিয়ে decrypt করুন।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার PDF pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও স্প্লিট করা হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type SplitPdfContent = typeof splitPdfContent;
