export const webpToJpgContent = {
  en: {
    heroTag: "Image Converter",
    heroSubtitle:
      "Convert WebP images to JPG format instantly in your browser. Get universal compatibility — JPG opens in every app, device, and program. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "Universal", label: "Format" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device. Zero uploads." },
      { emoji: "⚡", title: "Instant conversion", text: "Runs in your browser — no server wait." },
      { emoji: "📦", title: "Batch support", text: "Convert multiple WebP files at once." },
      { emoji: "🌐", title: "Universal format", text: "JPG opens literally everywhere." },
      { emoji: "🎨", title: "High quality", text: "92% quality for near-lossless results." },
      { emoji: "💾", title: "Download anytime", text: "Individual or bulk download with one click." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "WebP to JPG Converter takes your WebP images and re-encodes them as standard JPG files at 92% quality. It reads the WebP locally in your browser, draws it onto an off-screen canvas with a white background (because JPG does not support transparency), and exports the result as a JPEG blob. No byte leaves your device." },
      { emoji: "🌐", icon: "target", title: "Why convert to JPG?", text: "WebP is a modern format supported by every major browser, but not every application, operating system, or older device handles it equally well. Older versions of Windows, legacy photo editors, some email clients, and many print shops still expect JPG. Converting to JPG gives you universal compatibility — the file will open in literally any program on any platform." },
      { emoji: "⚡", icon: "printer", title: "How the conversion works", text: "The tool uses the browser's built-in HTML5 Canvas API. When you drop a WebP file, the browser decodes it into raw pixel data. The canvas re-draws those pixels on a white background, then exports the result as a JPEG blob at 92% quality. Both decoding and encoding happen inside your browser — no network traffic is involved." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript inside the page you are looking at. When you close the tab, every trace of your files is gone from memory. This makes the tool suitable for confidential images, client work, and anything you would not want a third party to see." },
    ],
    howToTitle: "How to convert WebP to JPG",
    howTo: [
      { step: 1, title: "Drop your WebP files", description: "Drag and drop one or more WebP files into the upload area, or click to browse. Files up to 50 MB each are supported." },
      { step: 2, title: "Wait a moment", description: "The tool converts each file in sequence. Conversion happens on your device, so it usually takes less than a second per file." },
      { step: 3, title: "Review the results", description: "Each converted file appears with the original name, original size, and the new JPG size. Transparency is filled with white." },
      { step: 4, title: "Download individually or all at once", description: "Click Download on any single file, or use Download All to grab every converted JPG in one go." },
    ],
    featuresTitle: "Built for real conversions",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "The file is decoded and re-encoded entirely in your browser. Nothing travels over the network." },
      { emoji: "⚡", title: "Instant results", description: "No queue, no waiting for a server. Every file converts in under a second on modern hardware." },
      { emoji: "📦", title: "Batch processing", description: "Drop multiple WebP files at once and convert them all in a single session." },
      { emoji: "🌐", title: "Universal compatibility", description: "JPG opens in every browser, every photo app, every device, every OS — no exceptions." },
      { emoji: "🎨", title: "High quality (92%)", description: "Converted JPGs use 92% quality — visually identical to the original for most images." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each are accepted. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything — decoding, canvas rendering, and JPEG encoding — happens inside your browser. Your files never leave your device." },
      { question: "Will the quality drop?", answer: "At 92% quality, the visual difference from the original WebP is usually impossible to spot. The JPG will look identical in normal viewing." },
      { question: "What happens to transparent backgrounds?", answer: "JPG does not support transparency. Any transparent areas in your WebP will be filled with white in the converted JPG." },
      { question: "Can I convert multiple files at once?", answer: "Yes. Drop as many WebP files as you want and they will all be converted. Use Download All to save every file in one click." },
      { question: "Is there a file size limit?", answer: "Each file can be up to 50 MB. There is no limit on the number of files you convert in one session." },
      { question: "Why would I convert WebP back to JPG?", answer: "Older software, print shops, and some email clients don't support WebP. JPG is the safest choice for universal compatibility." },
      { question: "Can I convert JPG to WebP?", answer: "Yes — we also have a JPG to WebP converter. It works the same way in reverse." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ কনভার্টার",
    heroSubtitle:
      "WebP ছবি JPG ফরম্যাটে সাথে সাথে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। সার্বজনীন সাপোর্ট — JPG সব অ্যাপ, ডিভাইস এবং প্রোগ্রামে খোলে।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "সার্বজনীন", label: "ফরম্যাট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক রূপান্তর", text: "ব্রাউজারেই চলে — সার্ভারের অপেক্ষা নেই।" },
      { emoji: "📦", title: "ব্যাচ সাপোর্ট", text: "একাধিক WebP একসাথে রূপান্তর করুন।" },
      { emoji: "🌐", title: "সার্বজনীন ফরম্যাট", text: "JPG সত্যিই সব জায়গায় খোলে।" },
      { emoji: "🎨", title: "উচ্চ কোয়ালিটি", text: "৯২% কোয়ালিটিতে প্রায় lossless।" },
      { emoji: "💾", title: "যেকোনো সময় ডাউনলোড", text: "এক ক্লিকে আলাদা বা সব একসাথে।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "WebP থেকে JPG কনভার্টার আপনার WebP ছবিগুলোকে ৯২% কোয়ালিটিতে স্ট্যান্ডার্ড JPG ফাইলে রূপান্তর করে। এটি WebP ফাইলটি আপনার ব্রাউজারেই পড়ে, সাদা ব্যাকগ্রাউন্ডে একটি off-screen ক্যানভাসে আঁকে (কারণ JPG স্বচ্ছতা সাপোর্ট করে না), এবং JPEG হিসেবে এক্সপোর্ট করে। একটি বাইটও ডিভাইস ছাড়ে না।" },
      { emoji: "🌐", icon: "target", title: "কেন JPG-তে কনভার্ট করবেন?", text: "WebP একটি আধুনিক ফরম্যাট, সব বড় ব্রাউজারে সাপোর্টেড, কিন্তু সব অ্যাপ্লিকেশন, OS বা পুরনো ডিভাইস সমানভাবে সাপোর্ট করে না। পুরনো Windows, লিগ্যাসি ফটো এডিটর, কিছু ইমেইল ক্লায়েন্ট এবং অনেক প্রিন্ট শপ JPG আশা করে। JPG-তে কনভার্ট করলে সার্বজনীন সাপোর্ট পাবেন।" },
      { emoji: "⚡", icon: "printer", title: "কনভার্সন কীভাবে কাজ করে", text: "টুলটি ব্রাউজারের HTML5 Canvas API ব্যবহার করে। WebP ড্রপ করলে ব্রাউজার সেটি raw pixel data-তে ডিকোড করে। ক্যানভাস সাদা ব্যাকগ্রাউন্ডে পিক্সেলগুলো আঁকে, তারপর ৯২% কোয়ালিটিতে JPEG হিসেবে এক্সপোর্ট করে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই আপনার ফাইলের সব চিহ্ন মেমরি থেকে মুছে যায়।" },
    ],
    howToTitle: "WebP কীভাবে JPG-তে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "আপনার WebP ফাইল দিন", description: "এক বা একাধিক WebP ফাইল upload এলাকায় ড্র্যাগ করে আনুন, বা ক্লিক করে ব্রাউজ করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "একটু অপেক্ষা করুন", description: "টুলটি একটার পর একটা ফাইল কনভার্ট করে। সাধারণত প্রতি ফাইল এক সেকেন্ডেরও কম সময় লাগে।" },
      { step: 3, title: "ফলাফল দেখুন", description: "প্রতিটি কনভার্টেড ফাইল তালিকায় দেখা যায় — মূল সাইজ ও নতুন JPG সাইজ সহ। স্বচ্ছ অংশ সাদা হয়ে যায়।" },
      { step: 4, title: "আলাদা বা সব একসাথে ডাউনলোড", description: "যেকোনো ফাইলে Download চাপুন, বা Download All দিয়ে সব JPG একবারে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত কনভার্সনের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল ডিকোড ও রি-এনকোড সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "তাৎক্ষণিক ফলাফল", description: "আধুনিক হার্ডওয়্যারে প্রতি ফাইল এক সেকেন্ডেরও কমে।" },
      { emoji: "📦", title: "ব্যাচ প্রসেসিং", description: "একাধিক WebP একবারে দিন এবং একটি সেশনেই সব কনভার্ট করুন।" },
      { emoji: "🌐", title: "সার্বজনীন সাপোর্ট", description: "JPG সব ব্রাউজার, ফটো অ্যাপ, ডিভাইস, OS-এ খোলে।" },
      { emoji: "🎨", title: "উচ্চ কোয়ালিটি (৯২%)", description: "কনভার্টেড JPG ৯২% কোয়ালিটি ব্যবহার করে — বেশিরভাগ ছবিতে মূলের সাথে অভিন্ন।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত। কোনো signup নেই, ওয়াটারমার্ক নেই।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই, লুকানো সাইজ লিমিট নেই।" },
      { question: "আমার ফাইল কি সার্ভারে আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই হয়। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "কোয়ালিটি কমে যাবে?", answer: "৯২% কোয়ালিটিতে মূল WebP থেকে ভিজ্যুয়াল পার্থক্য সাধারণত চোখে পড়ে না।" },
      { question: "স্বচ্ছ ব্যাকগ্রাউন্ডের কী হবে?", answer: "JPG স্বচ্ছতা সাপোর্ট করে না। আপনার WebP-এর স্বচ্ছ অংশ সাদা হয়ে যাবে।" },
      { question: "একসাথে একাধিক ফাইল কনভার্ট করা যায়?", answer: "হ্যাঁ। যত চান WebP ফাইল ড্রপ করুন, সব কনভার্ট হবে।" },
      { question: "ফাইল সাইজের লিমিট আছে?", answer: "প্রতি ফাইল ৫০ MB পর্যন্ত। এক সেশনে ফাইল সংখ্যার সীমা নেই।" },
      { question: "কেন WebP থেকে JPG-তে ফিরব?", answer: "পুরনো সফটওয়্যার, প্রিন্ট শপ এবং কিছু ইমেইল ক্লায়েন্ট WebP সাপোর্ট করে না। JPG সার্বজনীন সাপোর্টের জন্য নিরাপদ পছন্দ।" },
      { question: "JPG থেকে WebP-তে কনভার্ট করা যায়?", answer: "হ্যাঁ — আমাদের JPG to WebP কনভার্টারও আছে। উল্টো পথে একইভাবে কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type WebpToJpgContent = typeof webpToJpgContent;
