export const barcodeContent = {
  en: {
    heroTag: "Barcode Generator",
    heroSubtitle:
      "Generate 1D barcodes in 9 formats — CODE128, CODE39, EAN-13, EAN-8, UPC-A, ITF-14, MSI, Pharmacode, and Codabar. Live preview, custom colors, PNG or SVG export. Everything runs in your browser.",
    heroStats: [
      { value: "9 formats", label: "CODE128 · EAN · UPC..." },
      { value: "PNG+SVG", label: "Export" },
      { value: "100%", label: "Private" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Data never leaves your device." },
      { emoji: "🏷️", title: "9 barcode formats", text: "CODE128, EAN, UPC, and more." },
      { emoji: "🎨", title: "Custom colors", text: "Line color and background picker." },
      { emoji: "📐", title: "Pixel control", text: "Bar width, height, font size, margin." },
      { emoji: "💾", title: "PNG & SVG", text: "Raster for screens, vector for print." },
      { emoji: "⚡", title: "Live preview", text: "Updates as you type — no button." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Barcode Generator creates standard 1D barcodes from your text or number input. Pick from nine widely-used formats — CODE128 for general use, CODE39 for industrial labels, EAN-13 and UPC-A for retail products, ITF-14 for cartons and shipping, and more. Customize colors, dimensions, and font, then export as PNG or SVG." },
      { emoji: "📄", title: "When you need it", text: "Labeling products for retail. Printing inventory tags for a warehouse. Creating shipping cartons with ITF-14 codes. Making asset tags for internal tracking. Encoding prescription numbers with Pharmacode. All common barcode workflows, without uploading a single byte." },
      { emoji: "⚡", title: "How it works", text: "The jsbarcode library encodes your value using the format's specification, then renders bars as SVG paths. EAN-13, EAN-8, UPC-A, and ITF-14 automatically compute the trailing check digit if you enter the shorter form. SVG output is vector — infinitely scalable for print — while PNG export renders the SVG to a canvas at 3× scale for crisp screen output." },
      { emoji: "🔐", title: "Your data stays with you", text: "There is no server. No accounts. No analytics. Every barcode is generated entirely in your browser using JavaScript. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to generate a barcode",
    howTo: [
      { step: 1, title: "Pick a format", description: "CODE128 for general text, EAN-13 for retail, UPC-A for US products, and more." },
      { step: 2, title: "Enter your value", description: "Type the text or number. The hint shows what the selected format accepts." },
      { step: 3, title: "Customize", description: "Adjust bar width, height, font size, margin, and colors." },
      { step: 4, title: "Download", description: "Export as PNG for screen or SVG for print." },
    ],
    featuresTitle: "Built for real barcode work",
    features: [
      { emoji: "🏷️", title: "9 formats", description: "CODE128, CODE39, EAN-13, EAN-8, UPC-A, ITF-14, MSI, Pharmacode, Codabar." },
      { emoji: "🎨", title: "Custom colors", description: "Line color and background pickers, plus hex input." },
      { emoji: "📐", title: "Full control", description: "Bar width 1-6, height 40-300, font size, text margin, outer margin." },
      { emoji: "✅", title: "Auto checksum", description: "EAN/UPC/ITF-14 compute the check digit automatically." },
      { emoji: "💾", title: "PNG & SVG", description: "PNG at 3× scale for screens, SVG for infinite print scaling." },
      { emoji: "🔒", title: "Zero uploads", description: "Every barcode is rendered in your browser." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no expiration on generated barcodes." },
      { question: "Is my data uploaded?", answer: "No. Everything is rendered in your browser using the jsbarcode library. Nothing is sent over the network." },
      { question: "Which format should I use?", answer: "CODE128 for most text/URLs (widest support). EAN-13 for retail products sold internationally. UPC-A for products sold in the US/Canada. CODE39 for industrial/warehouse labels. ITF-14 for shipping cartons." },
      { question: "Do EAN/UPC need a check digit?", answer: "No — enter 12 digits for EAN-13 (or 13 with a valid checksum), 7 for EAN-8, 11 for UPC-A, 13 for ITF-14. The tool computes and appends the check digit automatically." },
      { question: "Should I use PNG or SVG?", answer: "SVG for print, packaging, and labels — it scales infinitely without blur. PNG for websites, emails, and anywhere SVG isn't supported. PNG exports at 3× resolution for retina displays." },
      { question: "Can I use custom colors?", answer: "Yes. Pick any line and background color. Keep contrast high (dark bars on light background) so scanners can read it reliably." },
      { question: "Why won't my barcode scan?", answer: "Common causes: wrong format for your scanner, low print contrast, bars too thin (increase width), or quiet-zone margin too small (increase margin). Test with the format your scanner expects." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your barcode is generated entirely inside your browser using the jsbarcode library. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "বারকোড জেনারেটর",
    heroSubtitle:
      "৯টি ফরম্যাটে ১D বারকোড তৈরি করুন — CODE128, CODE39, EAN-13, EAN-8, UPC-A, ITF-14, MSI, Pharmacode, Codabar। লাইভ প্রিভিউ, কাস্টম রঙ, PNG বা SVG export। সম্পূর্ণ ব্রাউজারেই।",
    heroStats: [
      { value: "৯ ফরম্যাট", label: "CODE128 · EAN · UPC..." },
      { value: "PNG+SVG", label: "Export" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ডেটা কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🏷️", title: "৯টি ফরম্যাট", text: "CODE128, EAN, UPC ইত্যাদি।" },
      { emoji: "🎨", title: "কাস্টম রঙ", text: "Line color ও background picker।" },
      { emoji: "📐", title: "Pixel নিয়ন্ত্রণ", text: "Bar width, height, font, margin।" },
      { emoji: "💾", title: "PNG ও SVG", text: "Screen-এর জন্য raster, print-এর জন্য vector।" },
      { emoji: "⚡", title: "লাইভ preview", text: "Typing-এর সাথে update।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Barcode Generator আপনার text বা number থেকে standard 1D barcode তৈরি করে। নয়টি widely-used format থেকে বেছে নিন — general use-এ CODE128, industrial label-এ CODE39, retail product-এ EAN-13 ও UPC-A, carton/shipping-এ ITF-14 ইত্যাদি। রঙ, dimension ও font কাস্টমাইজ করে PNG বা SVG export করুন।" },
      { emoji: "📄", title: "কখন দরকার", text: "Retail-এ product label করা। Warehouse-এ inventory tag print। ITF-14 code দিয়ে shipping carton। Internal tracking-এর জন্য asset tag। Pharmacode দিয়ে prescription number encode। সব সাধারণ barcode workflow — এক byte-ও upload না করে।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "jsbarcode library আপনার value-কে format-এর specification অনুযায়ী encode করে, তারপর bar-গুলো SVG path হিসেবে render করে। EAN-13, EAN-8, UPC-A ও ITF-14 ছোট form দিলে trailing check digit automatically compute করে। SVG output vector — print-এ infinite scalable। PNG export 3× scale-এ SVG-কে canvas-এ render করে।" },
      { emoji: "🔐", title: "আপনার ডেটা আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। প্রতিটি barcode সম্পূর্ণ আপনার ব্রাউজারেই JavaScript দিয়ে তৈরি।" },
    ],
    howToTitle: "বারকোড কীভাবে তৈরি করবেন",
    howTo: [
      { step: 1, title: "Format বাছুন", description: "সাধারণ text-এ CODE128, retail-এ EAN-13, US product-এ UPC-A, ইত্যাদি।" },
      { step: 2, title: "Value লিখুন", description: "Text বা number type করুন। Hint দেখায় নির্বাচিত format কী নেয়।" },
      { step: 3, title: "কাস্টমাইজ করুন", description: "Bar width, height, font size, margin ও রঙ ঠিক করুন।" },
      { step: 4, title: "ডাউনলোড", description: "Screen-এর জন্য PNG বা print-এর জন্য SVG export করুন।" },
    ],
    featuresTitle: "প্রকৃত বারকোড কাজের জন্য",
    features: [
      { emoji: "🏷️", title: "৯টি format", description: "CODE128, CODE39, EAN-13, EAN-8, UPC-A, ITF-14, MSI, Pharmacode, Codabar।" },
      { emoji: "🎨", title: "কাস্টম রঙ", description: "Line ও background color picker, hex input সহ।" },
      { emoji: "📐", title: "সম্পূর্ণ নিয়ন্ত্রণ", description: "Bar width 1-6, height 40-300, font size, margin।" },
      { emoji: "✅", title: "Auto checksum", description: "EAN/UPC/ITF-14 check digit স্বয়ংক্রিয়ভাবে compute করে।" },
      { emoji: "💾", title: "PNG ও SVG", description: "Screen-এ PNG (3×), print-এ infinite scaling-এর SVG।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "প্রতিটি barcode ব্রাউজারেই render হয়।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই, barcode-এর কোনো expiration নেই।" },
      { question: "আমার ডেটা কি আপলোড হয়?", answer: "না। jsbarcode library দিয়ে সবকিছু আপনার ব্রাউজারেই। কিছুই নেটওয়ার্কে যায় না।" },
      { question: "কোন format নেব?", answer: "বেশিরভাগ text/URL-এ CODE128 (বিস্তৃত support)। আন্তর্জাতিক retail product-এ EAN-13। US/Canada product-এ UPC-A। Industrial/warehouse label-এ CODE39। Shipping carton-এ ITF-14।" },
      { question: "EAN/UPC-এ check digit লাগবে?", answer: "না — EAN-13-এর জন্য ১২ digit (বা valid checksum সহ ১৩), EAN-8-এর জন্য ৭, UPC-A-এর জন্য ১১, ITF-14-এর জন্য ১৩ দিন। টুল check digit automatically compute করে।" },
      { question: "PNG না SVG?", answer: "Print, packaging ও label-এ SVG — infinite scale, blur নেই। Website, email ও SVG unsupported জায়গায় PNG। PNG 3× resolution-এ export হয়।" },
      { question: "কাস্টম রঙ ব্যবহার করা যায়?", answer: "হ্যাঁ। যেকোনো line ও background রঙ নিন। High contrast রাখুন (গাঢ় bar, হালকা bg)।" },
      { question: "বারকোড scan হয় না কেন?", answer: "সাধারণ কারণ: scanner-এর format-এর সাথে mismatch, print contrast কম, bar খুব পাতলা (width বাড়ান), বা quiet-zone margin কম (margin বাড়ান)।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari ও Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার barcode jsbarcode library দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই তৈরি হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type BarcodeContent = typeof barcodeContent;
