export const qrCodeContent = {
  en: {
    heroTag: "QR Code Generator",
    heroSubtitle:
      "Create high-quality QR codes for text, URLs, Wi-Fi, email, phone, SMS, vCard contacts, and locations. Custom colors, size up to 1024px, PNG or SVG export. Everything runs in your browser — nothing is uploaded.",
    heroStats: [
      { value: "8 types", label: "Text · URL · WiFi..." },
      { value: "1024px", label: "Max size" },
      { value: "PNG+SVG", label: "Export" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Data never leaves your device." },
      { emoji: "🎨", title: "Custom colors", text: "Foreground & background picker." },
      { emoji: "📐", title: "Up to 1024px", text: "Retina and print-quality output." },
      { emoji: "📱", title: "8 QR types", text: "Text, URL, WiFi, email, phone, SMS, vCard, location." },
      { emoji: "🎯", title: "4 error levels", text: "L, M, Q, H — you choose." },
      { emoji: "💾", title: "PNG or SVG", text: "Raster or vector, your choice." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "QR Code Generator creates scannable QR codes from eight different content types. Pick a type, fill in the fields, tweak colors and size, and download a PNG or SVG. Every QR is generated locally using the qrcode library — nothing is sent to a server." },
      { emoji: "📄", title: "When you need it", text: "Share Wi-Fi credentials without typing a password. Put a vCard on a business card. Link to a menu, portfolio, or event page. Add a phone or email shortcut to a flyer. Encode a GPS location for a treasure hunt or a landmark sign. All common QR use cases, no account required." },
      { emoji: "⚡", title: "How it works", text: "The qrcode library encodes your payload into a QR matrix using Reed-Solomon error correction, then renders it as a PNG (via canvas) or SVG (as vector paths). Error correction level H keeps QR codes readable even when up to 30% is damaged — perfect for logo embedding or print wear." },
      { emoji: "🔐", title: "Your data stays with you", text: "There is no server. No accounts. No analytics. Wi-Fi passwords, phone numbers, contact details — everything stays inside your browser. Close the tab and it's gone." },
    ],
    howToTitle: "How to generate a QR code",
    howTo: [
      { step: 1, title: "Choose a QR type", description: "Text, URL, Wi-Fi, email, phone, SMS, vCard, or location." },
      { step: 2, title: "Fill in the fields", description: "Enter the content — text, URL, credentials, or contact details." },
      { step: 3, title: "Customize", description: "Pick error level (L/M/Q/H), size (128–1024px), and colors." },
      { step: 4, title: "Download", description: "Get a PNG for screens or SVG for print — one click." },
    ],
    featuresTitle: "Built for real QR codes",
    features: [
      { emoji: "📱", title: "8 QR types", description: "Text, URL, Wi-Fi, email, phone, SMS, vCard, and geo location." },
      { emoji: "🎨", title: "Custom colors", description: "Foreground and background color pickers with hex input." },
      { emoji: "📐", title: "High resolution", description: "Up to 1024×1024 px — crisp on retina and print-ready." },
      { emoji: "🛡️", title: "Error correction", description: "Four levels (L/M/Q/H) — H survives up to 30% damage." },
      { emoji: "💾", title: "PNG & SVG", description: "Download the format you need — raster or vector." },
      { emoji: "🔒", title: "Zero uploads", description: "Every QR is generated in your browser." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits, no expiration on generated QR codes." },
      { question: "Is my data uploaded?", answer: "No. Everything happens inside your browser using the qrcode library. Your Wi-Fi password, contact details, or message never leave your device." },
      { question: "Do QR codes expire?", answer: "No. QR codes generated here are static — the data is baked into the image. They work forever as long as the target still exists." },
      { question: "What does the error correction level mean?", answer: "Error correction determines how much of the QR code can be damaged while still scannable. L ≈ 7%, M ≈ 15%, Q ≈ 25%, H ≈ 30%. Use H if you plan to print small or embed a logo." },
      { question: "Should I use PNG or SVG?", answer: "PNG for screens, websites, and social media. SVG for printing, packaging, and anywhere you need infinite scaling without pixelation." },
      { question: "Can I use custom colors?", answer: "Yes. Pick any foreground and background colors. Keep contrast high (dark on light) so scanners can read it reliably." },
      { question: "How do I make a Wi-Fi QR code?", answer: "Select the Wi-Fi type, enter the network name and password, pick the encryption (WPA/WEP/None), and download. Phones connected to that network will join automatically when scanned." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your QR code is generated entirely inside your browser using the qrcode library. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "QR কোড জেনারেটর",
    heroSubtitle:
      "টেক্সট, URL, Wi-Fi, email, ফোন, SMS, vCard যোগাযোগ ও location-এর জন্য উচ্চ-মানের QR কোড তৈরি করুন। কাস্টম রঙ, ১০২৪px পর্যন্ত, PNG বা SVG export। সম্পূর্ণ ব্রাউজারেই।",
    heroStats: [
      { value: "৮ ধরন", label: "টেক্সট · URL · WiFi..." },
      { value: "১০২৪px", label: "সর্বোচ্চ" },
      { value: "PNG+SVG", label: "Export" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ডেটা কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "কাস্টম রঙ", text: "Foreground ও background picker।" },
      { emoji: "📐", title: "১০২৪px পর্যন্ত", text: "Retina ও print-quality।" },
      { emoji: "📱", title: "৮ ধরনের QR", text: "Text, URL, WiFi, email, phone, SMS, vCard, location।" },
      { emoji: "🎯", title: "৪ error level", text: "L, M, Q, H — আপনার পছন্দ।" },
      { emoji: "💾", title: "PNG বা SVG", text: "Raster বা vector, যেটা দরকার।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "QR Code Generator আট ধরনের content থেকে স্ক্যানযোগ্য QR তৈরি করে। ধরন বেছে নিন, field পূরণ করুন, রঙ ও সাইজ ঠিক করুন, PNG বা SVG ডাউনলোড করুন। প্রতিটি QR qrcode library দিয়ে লোকালি generate হয় — কোনো কিছু সার্ভারে যায় না।" },
      { emoji: "📄", title: "কখন দরকার", text: "পাসওয়ার্ড টাইপ না করে Wi-Fi share করা। Business card-এ vCard বসানো। Menu, portfolio বা event page-এ link। Flyer-এ phone বা email shortcut। GPS location encode করা। সব সাধারণ QR use case — account ছাড়াই।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "qrcode library আপনার payload-কে Reed-Solomon error correction দিয়ে QR matrix-এ encode করে, তারপর PNG (canvas-এ) বা SVG (vector path হিসেবে) render করে। Error correction level H QR-কে ৩০% পর্যন্ত ক্ষতিতেও readable রাখে — logo embed বা print wear-এর জন্য perfect।" },
      { emoji: "🔐", title: "আপনার ডেটা আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। Wi-Fi password, phone number, contact details — সব আপনার ব্রাউজারেই থাকে। ট্যাব বন্ধ করলেই চলে যায়।" },
    ],
    howToTitle: "QR কোড কীভাবে তৈরি করবেন",
    howTo: [
      { step: 1, title: "QR ধরন বাছুন", description: "Text, URL, Wi-Fi, email, phone, SMS, vCard বা location।" },
      { step: 2, title: "Field পূরণ করুন", description: "Content লিখুন — text, URL, credential বা contact details।" },
      { step: 3, title: "কাস্টমাইজ করুন", description: "Error level (L/M/Q/H), size (128–1024px), এবং রঙ বেছে নিন।" },
      { step: 4, title: "ডাউনলোড", description: "Screen-এর জন্য PNG, print-এর জন্য SVG — এক ক্লিকে।" },
    ],
    featuresTitle: "প্রকৃত QR-এর জন্য তৈরি",
    features: [
      { emoji: "📱", title: "৮ QR ধরন", description: "Text, URL, Wi-Fi, email, phone, SMS, vCard ও geo location।" },
      { emoji: "🎨", title: "কাস্টম রঙ", description: "Foreground ও background color picker, hex input সহ।" },
      { emoji: "📐", title: "উচ্চ রেজোলিউশন", description: "১০২৪×১০২৪ px পর্যন্ত — retina ও print-ready।" },
      { emoji: "🛡️", title: "Error correction", description: "চারটি level (L/M/Q/H) — H ৩০% পর্যন্ত ক্ষতি সহ্য করে।" },
      { emoji: "💾", title: "PNG ও SVG", description: "যে format দরকার — raster বা vector।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "প্রতিটি QR আপনার ব্রাউজারেই তৈরি।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই, QR-এর কোনো expiration নেই।" },
      { question: "আমার ডেটা কি আপলোড হয়?", answer: "না। qrcode library দিয়ে সবকিছু আপনার ব্রাউজারেই। Wi-Fi password, contact details বা message কখনো ডিভাইস ছাড়ে না।" },
      { question: "QR কি expire হয়?", answer: "না। এখানে তৈরি QR static — ডেটা image-এর ভেতরে baked। Target যতদিন থাকবে, QR ততদিন কাজ করবে।" },
      { question: "Error correction level মানে কী?", answer: "QR কতটা ক্ষতিগ্রস্ত হলেও স্ক্যানযোগ্য থাকবে তা নির্ধারণ করে। L ≈ ৭%, M ≈ ১৫%, Q ≈ ২৫%, H ≈ ৩০%। ছোট size-এ print বা logo embed করতে চাইলে H ব্যবহার করুন।" },
      { question: "PNG না SVG?", answer: "Screen, website ও social media-র জন্য PNG। Print, packaging ও infinite scaling-এর জন্য SVG।" },
      { question: "কাস্টম রঙ ব্যবহার করা যায়?", answer: "হ্যাঁ। যেকোনো foreground ও background রঙ বেছে নিন। Scanner-এ readable থাকতে contrast বেশি রাখুন (গাঢ় on হালকা)।" },
      { question: "Wi-Fi QR কীভাবে বানাবো?", answer: "Wi-Fi type select করুন, network name ও password লিখুন, encryption (WPA/WEP/None) বেছে নিন, এবং ডাউনলোড করুন।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার QR কোড qrcode library দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই তৈরি হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type QrCodeContent = typeof qrCodeContent;
