export const imageCompressorContent = {
  en: {
    heroTag: "Image Compressor",
    heroSubtitle:
      "Compress JPG, PNG, and WebP images right in your browser. Adjust quality and max width, see the savings instantly, and download compressed files — all without a single byte leaving your device.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "Adjustable", label: "Quality" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Instant compression", text: "Runs in your browser." },
      { emoji: "🎚️", title: "Quality slider", text: "Control the tradeoff." },
      { emoji: "📐", title: "Max width limit", text: "Downscale large photos." },
      { emoji: "📦", title: "Batch support", text: "Compress multiple files at once." },
      { emoji: "💾", title: "See savings", text: "Before/after size shown live." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Image Compressor shrinks JPG, PNG, and WebP files using the browser's native image encoder. It reads your image locally, optionally downscales it to a maximum width you choose, and re-encodes it at a quality level you control. You see the original size, the compressed size, and the percentage saved — instantly, per file." },
      { emoji: "🎚️", icon: "target", title: "Why the tradeoff matters", text: "Compression is always a tradeoff between file size and visual fidelity. A quality of 80% often reduces file size by 60-80% with almost no visible difference. A quality of 60% is more aggressive but still fine for thumbnails. This tool lets you tune that balance with a slider." },
      { emoji: "⚡", icon: "printer", title: "How the compression works", text: "The tool uses the browser's built-in HTML5 Canvas API. When you drop an image, the browser decodes it into raw pixels. The canvas optionally downscales it to your maximum width using high-quality interpolation, then re-encodes the result using the WebP, JPG, or PNG encoder built into every modern browser." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your files is gone from memory." },
    ],
    howToTitle: "How to compress images",
    howTo: [
      { step: 1, title: "Drop your image files", description: "Drag JPG, PNG, or WebP files into the upload area, or click to browse. Up to 50 MB per file." },
      { step: 2, title: "Adjust quality and max width", description: "Use the quality slider to control the tradeoff. Lower = smaller file, less quality. Use Max Width to cap dimensions." },
      { step: 3, title: "Review the results", description: "Each compressed file appears with original size, new size, and percentage saved — usually 50-80% smaller." },
      { step: 4, title: "Download individually or all at once", description: "Click Download on any file, or use Download All to grab every compressed image in one go." },
    ],
    featuresTitle: "Built for real compression",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Files are decoded and re-encoded entirely in your browser." },
      { emoji: "🎚️", title: "Adjustable quality", description: "Tune the compression from 10% to 100% — see the tradeoff in real time." },
      { emoji: "📐", title: "Max width control", description: "Downscale huge photos to web-friendly sizes with no visible loss." },
      { emoji: "📦", title: "Batch processing", description: "Drop multiple images at once and compress them all in a single session." },
      { emoji: "📉", title: "See the savings", description: "Before/after sizes and percentage reduction displayed live per file." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser. Your files never leave your device." },
      { question: "How much smaller will the file be?", answer: "At quality 80 with max width 1920, most photos shrink by 60-80%. PNGs and WebPs compress less dramatically but still save 30-60%." },
      { question: "What quality should I use?", answer: "For web uploads, 75-85% is a good default. For previews and thumbnails, 50-65% is fine. For archival, 90-95%." },
      { question: "Will transparency be preserved?", answer: "PNG and WebP keep transparency. JPG does not — transparent areas become white." },
      { question: "Can I compress multiple files at once?", answer: "Yes. Drop as many as you want; the current settings apply to all." },
      { question: "Is there a file size limit?", answer: "Each file can be up to 50 MB. No limit on the number of files." },
      { question: "What output format is used?", answer: "JPG stays JPG, WebP stays WebP. PNG is re-encoded as WebP (which supports transparency and compresses better)." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ কমপ্রেসর",
    heroSubtitle:
      "JPG, PNG এবং WebP ছবি সম্পূর্ণ আপনার ব্রাউজারেই কমপ্রেস করুন। কোয়ালিটি ও সর্বোচ্চ প্রস্থ নিয়ন্ত্রণ করুন, সাথে সাথে সাইজ সাশ্রয় দেখুন, এবং কমপ্রেসড ফাইল ডাউনলোড করুন।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "সমন্বয়যোগ্য", label: "কোয়ালিটি" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক কমপ্রেশন", text: "ব্রাউজারেই চলে।" },
      { emoji: "🎚️", title: "কোয়ালিটি স্লাইডার", text: "ট্রেডঅফ নিয়ন্ত্রণ করুন।" },
      { emoji: "📐", title: "সর্বোচ্চ প্রস্থ", text: "বড় ছবি ছোট করুন।" },
      { emoji: "📦", title: "ব্যাচ সাপোর্ট", text: "একাধিক ফাইল একসাথে।" },
      { emoji: "💾", title: "সাশ্রয় দেখুন", text: "আগে-পরে সাইজ লাইভ।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "ইমেজ কমপ্রেসর ব্রাউজারের নেটিভ ইমেজ এনকোডার ব্যবহার করে JPG, PNG এবং WebP ফাইল ছোট করে। আপনি মূল সাইজ, কমপ্রেসড সাইজ এবং শতকরা সাশ্রয় সাথে সাথে দেখেন।" },
      { emoji: "🎚️", icon: "target", title: "কেন ট্রেডঅফ গুরুত্বপূর্ণ", text: "কমপ্রেশন সর্বদা ফাইল সাইজ ও ভিজ্যুয়াল ফিডেলিটির মধ্যে ট্রেডঅফ। ৮০% কোয়ালিটিতে প্রায়ই ফাইল সাইজ ৬০-৮০% কমে যায়।" },
      { emoji: "⚡", icon: "printer", title: "কমপ্রেশন কীভাবে কাজ করে", text: "টুলটি ব্রাউজারের HTML5 Canvas API ব্যবহার করে। ছবি ড্রপ করলে ব্রাউজার সেটি raw pixel-এ ডিকোড করে, তারপর প্রতিটি আধুনিক ব্রাউজারের এনকোডার দিয়ে রি-এনকোড করে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "ছবি কীভাবে কমপ্রেস করবেন",
    howTo: [
      { step: 1, title: "আপনার ছবি দিন", description: "JPG, PNG বা WebP ফাইল ড্র্যাগ করে আনুন বা ক্লিক করে ব্রাউজ করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "কোয়ালিটি ও প্রস্থ ঠিক করুন", description: "কোয়ালিটি স্লাইডার দিয়ে ট্রেডঅফ নিয়ন্ত্রণ করুন। Max Width দিয়ে বড় ছবি সীমাবদ্ধ করুন।" },
      { step: 3, title: "ফলাফল দেখুন", description: "প্রতিটি কমপ্রেসড ফাইল মূল সাইজ, নতুন সাইজ ও শতকরা সাশ্রয় সহ দেখা যায়।" },
      { step: 4, title: "ডাউনলোড করুন", description: "যেকোনো ফাইলে Download চাপুন, বা Download All দিয়ে সব একবারে।" },
    ],
    featuresTitle: "প্রকৃত কমপ্রেশনের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল সম্পূর্ণ আপনার ব্রাউজারেই ডিকোড ও রি-এনকোড হয়।" },
      { emoji: "🎚️", title: "সমন্বয়যোগ্য কোয়ালিটি", description: "১০% থেকে ১০০% পর্যন্ত কমপ্রেশন টিউন করুন।" },
      { emoji: "📐", title: "সর্বোচ্চ প্রস্থ নিয়ন্ত্রণ", description: "বড় ছবি ওয়েব-বান্ধব সাইজে নামান।" },
      { emoji: "📦", title: "ব্যাচ প্রসেসিং", description: "একাধিক ছবি একবারে দিন, সব কমপ্রেস করুন।" },
      { emoji: "📉", title: "সাশ্রয় দেখুন", description: "আগে-পরে সাইজ ও শতকরা হ্রাস লাইভ দেখানো হয়।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ফাইল কি সার্ভারে আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "ফাইল কতটা ছোট হবে?", answer: "কোয়ালিটি ৮০ ও সর্বোচ্চ প্রস্থ ১৯২০-এ বেশিরভাগ ছবি ৬০-৮০% ছোট হয়।" },
      { question: "কোন কোয়ালিটি ব্যবহার করব?", answer: "ওয়েব আপলোডের জন্য ৭৫-৮৫%। থাম্বনেইলের জন্য ৫০-৬৫%। আর্কাইভের জন্য ৯০-৯৫%।" },
      { question: "স্বচ্ছতা কি সংরক্ষিত থাকবে?", answer: "PNG ও WebP স্বচ্ছতা রাখে। JPG রাখে না।" },
      { question: "একসাথে একাধিক ফাইল করা যায়?", answer: "হ্যাঁ। যত চান ড্রপ করুন।" },
      { question: "সাইজ লিমিট আছে?", answer: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { question: "কোন আউটপুট ফরম্যাট?", answer: "JPG ও WebP অপরিবর্তিত। PNG WebP-তে রি-এনকোড হয়।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageCompressorContent = typeof imageCompressorContent;
