export const imageResizerContent = {
  en: {
    heroTag: "Image Resizer",
    heroSubtitle:
      "Resize JPG, PNG, and WebP images to any dimension in your browser. Lock aspect ratio, choose exact width and height, and download resized files — all without a single upload.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "Any", label: "Dimension" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Instant resize", text: "Runs in your browser." },
      { emoji: "📐", title: "Any dimension", text: "Set exact width and height." },
      { emoji: "🔗", title: "Lock aspect", text: "Preserve proportions automatically." },
      { emoji: "📦", title: "Batch support", text: "Resize multiple files at once." },
      { emoji: "💾", title: "See the result", text: "Before/after dimensions live." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Image Resizer changes the pixel dimensions of your JPG, PNG, and WebP files. Type in the width and height you want, optionally lock the aspect ratio to prevent stretching, and the tool re-renders your image at exactly that size using high-quality interpolation. Everything happens locally in your browser, so no upload is needed." },
      { emoji: "📐", icon: "target", title: "When you need it", text: "Social media platforms often enforce specific dimensions (Instagram: 1080×1080, Facebook cover: 820×312). Print shops need specific sizes. Websites load faster with smaller images. This tool lets you hit those exact numbers without opening Photoshop or any other heavy editor." },
      { emoji: "⚡", icon: "printer", title: "How the resizing works", text: "The tool uses the browser's HTML5 Canvas API. When you drop an image, the browser decodes it into raw pixels. The canvas redraws those pixels at your target width and height using high-quality interpolation, then re-encodes the result using the same format (or WebP for PNG). Both steps happen locally — no network traffic involved." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your files is gone from memory." },
    ],
    howToTitle: "How to resize an image",
    howTo: [
      { step: 1, title: "Drop your image files", description: "Drag JPG, PNG, or WebP files into the upload area, or click to browse. Up to 50 MB per file." },
      { step: 2, title: "Enter target dimensions", description: "Type the width and height you want, or adjust the sliders. Toggle Lock Aspect to preserve proportions." },
      { step: 3, title: "Review the results", description: "Each resized file appears with original and new dimensions, plus the resulting file size." },
      { step: 4, title: "Download individually or all at once", description: "Click Download on any file, or use Download All to grab every resized image in one go." },
    ],
    featuresTitle: "Built for real resizing",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Files are decoded and re-encoded entirely in your browser." },
      { emoji: "📐", title: "Any dimension", description: "Set width and height in pixels — from thumbnails to 4K+" },
      { emoji: "🔗", title: "Lock aspect ratio", description: "Toggle on to prevent stretching — dimensions scale proportionally." },
      { emoji: "📦", title: "Batch processing", description: "Drop multiple images at once and resize them all in a single session." },
      { emoji: "🎚️", title: "Quality control", description: "Adjust the output quality for lossy formats (JPG, WebP)." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser. Your files never leave your device." },
      { question: "Will resizing stretch my image?", answer: "Only if you turn off Lock Aspect Ratio. With it on, the tool preserves the original proportions and adjusts the other dimension automatically." },
      { question: "What image formats are supported?", answer: "JPG, JPEG, PNG, and WebP. Output stays in the same format (PNG stays PNG, JPG stays JPG, WebP stays WebP)." },
      { question: "Can I upscale as well as downscale?", answer: "Yes — type any width and height. Upscaling works, though very large upscales may look soft because the browser cannot invent detail that isn't there." },
      { question: "Can I resize multiple files at once?", answer: "Yes. Drop as many as you want; the current width/height settings apply to all." },
      { question: "Is there a file size limit?", answer: "Each file can be up to 50 MB. No limit on the number of files." },
      { question: "Will transparency be preserved?", answer: "PNG and WebP keep transparency. JPG does not — transparent areas become white." },
    ],
    privacyNote: "Your images are processed entirely inside your browser using the HTML5 Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ রিসাইজার",
    heroSubtitle:
      "JPG, PNG এবং WebP ছবি সম্পূর্ণ আপনার ব্রাউজারেই যেকোনো মাপে রিসাইজ করুন। Aspect ratio লক করুন, সঠিক প্রস্থ-উচ্চতা বেছে নিন, এবং রিসাইজড ফাইল ডাউনলোড করুন — শূন্য আপলোড।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "যেকোনো", label: "মাপ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক রিসাইজ", text: "ব্রাউজারেই চলে।" },
      { emoji: "📐", title: "যেকোনো মাপ", text: "সঠিক প্রস্থ ও উচ্চতা দিন।" },
      { emoji: "🔗", title: "Aspect lock", text: "অনুপাত স্বয়ংক্রিয়ভাবে রাখুন।" },
      { emoji: "📦", title: "ব্যাচ সাপোর্ট", text: "একাধিক ফাইল একসাথে।" },
      { emoji: "💾", title: "ফলাফল দেখুন", text: "আগে-পরে মাপ লাইভ।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "ইমেজ রিসাইজার আপনার JPG, PNG এবং WebP ফাইলের পিক্সেল মাপ পরিবর্তন করে। আপনি যে প্রস্থ ও উচ্চতা চান টাইপ করুন, ঐচ্ছিকভাবে aspect ratio লক করুন যাতে ছবি প্রসারিত না হয়, এবং টুলটি high-quality interpolation দিয়ে ঠিক সেই মাপে আপনার ছবি রেন্ডার করে।" },
      { emoji: "📐", icon: "target", title: "কখন দরকার", text: "সোশ্যাল মিডিয়া প্ল্যাটফর্ম প্রায়ই নির্দিষ্ট মাপ চায় (Instagram: 1080×1080, Facebook cover: 820×312)। প্রিন্ট শপ নির্দিষ্ট সাইজ চায়। ওয়েবসাইট ছোট ছবিতে দ্রুত লোড হয়। এই টুল সেই সঠিক সংখ্যা হিট করতে দেয়।" },
      { emoji: "⚡", icon: "printer", title: "রিসাইজ কীভাবে কাজ করে", text: "টুলটি ব্রাউজারের HTML5 Canvas API ব্যবহার করে। ছবি ড্রপ করলে ব্রাউজার সেটি raw pixel-এ ডিকোড করে। ক্যানভাস high-quality interpolation দিয়ে আপনার টার্গেট মাপে পিক্সেল পুনরায় আঁকে, তারপর একই ফরম্যাটে রি-এনকোড করে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "ছবি কীভাবে রিসাইজ করবেন",
    howTo: [
      { step: 1, title: "আপনার ছবি দিন", description: "JPG, PNG বা WebP ফাইল ড্র্যাগ করে আনুন বা ক্লিক করে ব্রাউজ করুন। প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { step: 2, title: "টার্গেট মাপ দিন", description: "প্রস্থ ও উচ্চতা টাইপ করুন, বা স্লাইডার দিয়ে ঠিক করুন। অনুপাত রাখতে Lock Aspect টগল করুন।" },
      { step: 3, title: "ফলাফল দেখুন", description: "প্রতিটি রিসাইজড ফাইল মূল ও নতুন মাপ এবং নতুন ফাইল সাইজ সহ দেখা যায়।" },
      { step: 4, title: "ডাউনলোড করুন", description: "যেকোনো ফাইলে Download চাপুন, বা Download All দিয়ে সব একবারে।" },
    ],
    featuresTitle: "প্রকৃত রিসাইজের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল সম্পূর্ণ আপনার ব্রাউজারেই ডিকোড ও রি-এনকোড হয়।" },
      { emoji: "📐", title: "যেকোনো মাপ", description: "পিক্সেলে প্রস্থ ও উচ্চতা দিন — থাম্বনেইল থেকে 4K+ পর্যন্ত।" },
      { emoji: "🔗", title: "Aspect ratio লক", description: "টগল করুন ছবি প্রসারিত হওয়া রোধ করতে।" },
      { emoji: "📦", title: "ব্যাচ প্রসেসিং", description: "একাধিক ছবি একবারে দিন, সব রিসাইজ করুন।" },
      { emoji: "🎚️", title: "কোয়ালিটি নিয়ন্ত্রণ", description: "lossy ফরম্যাটের জন্য আউটপুট কোয়ালিটি ঠিক করুন।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ফাইল কি সার্ভারে আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "রিসাইজ কি ছবি প্রসারিত করবে?", answer: "শুধু যদি Lock Aspect Ratio বন্ধ করেন। চালু থাকলে টুল মূল অনুপাত রাখে।" },
      { question: "কোন ফরম্যাট সাপোর্টেড?", answer: "JPG, JPEG, PNG এবং WebP। আউটপুট একই ফরম্যাটে থাকে।" },
      { question: "বড়ও করা যায়?", answer: "হ্যাঁ — যেকোনো মাপ দিন। খুব বড় মাপে ছবি নরম লাগতে পারে কারণ ব্রাউজার নতুন ডিটেইল বানাতে পারে না।" },
      { question: "একসাথে একাধিক ফাইল?", answer: "হ্যাঁ। যত চান ড্রপ করুন।" },
      { question: "সাইজ লিমিট আছে?", answer: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
      { question: "স্বচ্ছতা থাকবে?", answer: "PNG ও WebP স্বচ্ছতা রাখে। JPG রাখে না।" },
    ],
    privacyNote: "আপনার ছবি HTML5 Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই প্রসেস হয়। কোনো কিছু আপলোড, ট্র্যাক বা সার্ভারে সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageResizerContent = typeof imageResizerContent;
