export const svgToPngContent = {
  en: {
    heroTag: "SVG to PNG",
    heroSubtitle:
      "Convert SVG vector files into high-resolution PNG images — right in your browser. Choose 1×, 2×, 4×, or 8× scale, transparent or solid background. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Up to 8×", label: "Scale" },
      { value: "100%", label: "Private" },
      { value: "Transparent", label: "Background" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "SVG never leaves your device." },
      { emoji: "🎨", title: "Up to 8× scale", text: "Retina-sharp PNG output." },
      { emoji: "🫥", title: "Transparent bg", text: "Or white/black — your choice." },
      { emoji: "⚡", title: "Instant", text: "Renders in milliseconds." },
      { emoji: "💾", title: "No uploads", text: "Everything runs locally." },
      { emoji: "🖼️", title: "Universal PNG", text: "Opens on every device and app." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "SVG to PNG renders your SVG vector file onto a canvas at your chosen scale and encodes the result as a PNG image. Unlike SVG — which some apps, email clients, and platforms don't support — PNG opens everywhere. Choose 1× for screen-size, 2× for retina displays, 4× or 8× for print and high-DPI output." },
      { emoji: "📄", title: "When you need it", text: "Social media platforms don't accept SVG uploads — you need PNG. Design tools, PowerPoint, and many CMS editors ignore SVG or render it inconsistently. Emails almost always block SVG. Converting to PNG fixes all of this in one step while preserving full quality thanks to vector scaling." },
      { emoji: "⚡", title: "How the conversion works", text: "The tool reads the SVG file as text, parses its dimensions (or falls back to the viewBox), and creates a temporary Image from a Blob URL. That image is drawn onto a canvas at your chosen scale, and the canvas is encoded as a lossless PNG. Everything happens in your browser — no network requests." },
      { emoji: "🔐", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. Your SVGs — icons, logos, illustrations, brand assets — stay entirely inside your browser. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to convert SVG to PNG",
    howTo: [
      { step: 1, title: "Drop your SVG", description: "Drag an SVG file into the upload area, or click to browse. Up to 20 MB." },
      { step: 2, title: "Pick a scale", description: "Choose 1×, 2×, 4×, or 8×. Higher scale = sharper output, larger file." },
      { step: 3, title: "Choose background", description: "Transparent (default), white, or black — for any destination." },
      { step: 4, title: "Download PNG", description: "Click Convert. Your PNG is generated and downloaded instantly." },
    ],
    featuresTitle: "Built for real design work",
    features: [
      { emoji: "🎨", title: "Up to 8× scale", description: "Retina-ready and print-quality output — up to 4096×4096 px." },
      { emoji: "🫥", title: "Transparent output", description: "Preserves SVG transparency by default — perfect for logos and icons." },
      { emoji: "🔒", title: "Zero uploads", description: "SVG parsing and rendering happen entirely in your browser." },
      { emoji: "⚡", title: "Instant", description: "Canvas rendering is fast — even 8× takes under a second." },
      { emoji: "📐", title: "Auto dimensions", description: "Reads width/height or falls back to viewBox automatically." },
      { emoji: "📄", title: "Any size", description: "SVG files up to 20 MB. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my SVG uploaded?", answer: "No. Everything happens inside your browser using the Canvas API. Your file never leaves your device." },
      { question: "What scale should I choose?", answer: "1× for icons at their natural size, 2× for retina displays, 4× for print thumbnails, and 8× for high-DPI print (up to 4096px)." },
      { question: "Will transparency be preserved?", answer: "Yes — by default the background is transparent, matching the SVG. You can switch to white or black if you need a solid background." },
      { question: "Why does the SVG look different from the original?", answer: "Some SVGs use external fonts, embedded images, or CSS classes that need extra files. This tool renders only what's inside the SVG itself — inline everything before converting for best results." },
      { question: "What's the maximum output size?", answer: "4096 × 4096 pixels. Beyond that, canvas rendering varies by browser and may fail or slow down." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
      { question: "Can I convert multiple SVGs at once?", answer: "This tool converts one SVG per session. Run it again for the next file — it's fast enough that batch conversion isn't necessary." },
    ],
    privacyNote: "Your SVG is read and rendered entirely inside your browser using the Canvas API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "SVG থেকে PNG",
    heroSubtitle:
      "SVG ভেক্টর ফাইলকে উচ্চ-রেজোলিউশন PNG ছবিতে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। ১×, ২×, ৪×, বা ৮× স্কেল, স্বচ্ছ বা সলিড ব্যাকগ্রাউন্ড — সব অপশন।",
    heroStats: [
      { value: "৮× পর্যন্ত", label: "স্কেল" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "স্বচ্ছ", label: "ব্যাকগ্রাউন্ড" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "SVG কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "৮× পর্যন্ত স্কেল", text: "Retina-শার্প PNG।" },
      { emoji: "🫥", title: "স্বচ্ছ bg", text: "বা সাদা/কালো — আপনার পছন্দ।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", text: "মিলিসেকেন্ডে রেন্ডার।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "🖼️", title: "সার্বজনীন PNG", text: "সব ডিভাইস ও অ্যাপে খোলে।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "SVG to PNG আপনার SVG ভেক্টর ফাইলকে নির্বাচিত স্কেলে canvas-এ রেন্ডার করে এবং PNG হিসেবে encode করে। কিছু অ্যাপ, email client এবং platform SVG সাপোর্ট করে না — সেখানে PNG কাজ করে। 1× screen-এর জন্য, 2× retina-র জন্য, 4× বা 8× print ও high-DPI-র জন্য।" },
      { emoji: "📄", title: "কখন দরকার", text: "সোশ্যাল মিডিয়া SVG নেয় না — PNG লাগে। Design tool, PowerPoint, banyak CMS editor SVG ignore করে বা inconsistent দেখায়। Email প্রায় সবসময় SVG block করে। Vector scaling-এর সুবিধায় quality ঠিক রেখে PNG-তে convert করা এক ধাপেই সব সমাধান করে।" },
      { emoji: "⚡", title: "কনভার্সন কীভাবে কাজ করে", text: "টুলটি SVG ফাইলকে text হিসেবে পড়ে, তার dimension parse করে (নাহলে viewBox থেকে নেয়), এবং Blob URL থেকে temporary Image বানায়। সেই image আপনার নির্বাচিত scale-এ canvas-এ আঁকা হয়, এবং canvas lossless PNG হিসেবে encode করা হয়। সবকিছু ব্রাউজারেই।" },
      { emoji: "🔐", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। আপনার SVG — icon, logo, illustration, brand asset — সম্পূর্ণ আপনার ব্রাউজারেই থাকে।" },
    ],
    howToTitle: "SVG কীভাবে PNG-তে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "SVG দিন", description: "SVG ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ২০ MB পর্যন্ত।" },
      { step: 2, title: "Scale বাছুন", description: "1×, 2×, 4×, বা 8×। বড় scale = শার্প output, বড় file।" },
      { step: 3, title: "Background বাছুন", description: "Transparent (ডিফল্ট), সাদা, বা কালো।" },
      { step: 4, title: "PNG ডাউনলোড", description: "Convert চাপুন। PNG সাথে সাথে তৈরি ও ডাউনলোড হবে।" },
    ],
    featuresTitle: "প্রকৃত ডিজাইন কাজের জন্য",
    features: [
      { emoji: "🎨", title: "৮× পর্যন্ত স্কেল", description: "Retina ও print-quality output — ৪০৯৬×৪০৯৬ px পর্যন্ত।" },
      { emoji: "🫥", title: "স্বচ্ছ output", description: "SVG-এর transparency ডিফল্টেই সংরক্ষিত — logo ও icon-এর জন্য perfect।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "SVG parse ও render সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", description: "Canvas rendering দ্রুত — ৮×-ও সেকেন্ডের কম সময়ে।" },
      { emoji: "📐", title: "Auto dimension", description: "width/height পড়ে, নাহলে viewBox থেকে নেয়।" },
      { emoji: "📄", title: "যেকোনো সাইজ", description: "SVG ২০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার SVG কি আপলোড হয়?", answer: "না। Canvas API দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "কোন scale নেব?", answer: "1× icon-এর natural size-এ, 2× retina-র জন্য, 4× print thumbnail-এ, 8× high-DPI print (৪০৯৬px পর্যন্ত)।" },
      { question: "Transparency থাকবে?", answer: "হ্যাঁ — ডিফল্ট background transparent, SVG-এর মতো। চাইলে সাদা বা কালোতে switch করা যায়।" },
      { question: "SVG আলাদা দেখাচ্ছে কেন?", answer: "কিছু SVG external font, embedded image, বা CSS class ব্যবহার করে যা আলাদা file দরকার। এই টুল শুধু SVG-এর ভেতরের সব render করে।" },
      { question: "সর্বোচ্চ output কত?", answer: "৪০৯৬ × ৪০৯৬ পিক্সেল। এর বেশি হলে browser-এ slow হতে পারে।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
      { question: "একসাথে একাধিক SVG?", answer: "এই টুল এক SVG করে কাজ করে। পরেরটার জন্য আবার চালান।" },
    ],
    privacyNote: "আপনার SVG Canvas API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও render হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type SvgToPngContent = typeof svgToPngContent;
