export const wordCounterContent = {
  en: {
    heroTag: "Word Counter",
    heroSubtitle:
      "Count words, characters, sentences, and paragraphs in real time — right in your browser. See reading time, speaking time, keyword density, and average word length as you type. No accounts, no tracking, nothing uploaded.",
    heroStats: [
      { value: "Live", label: "Update" },
      { value: "100%", label: "Private" },
      { value: "8+", label: "Metrics" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Text never leaves your browser." },
      { emoji: "⚡", title: "Live counters", text: "Updates with every keystroke." },
      { emoji: "📊", title: "8+ metrics", text: "Words, chars, sentences, paragraphs, and more." },
      { emoji: "⏱️", title: "Reading time", text: "See how long your text takes to read." },
      { emoji: "🔑", title: "Keyword density", text: "Top keywords at a glance." },
      { emoji: "💾", title: "Nothing stored", text: "No accounts, no logs." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Word Counter reads whatever you paste or type and instantly counts words, characters with and without spaces, sentences, paragraphs, and lines. It also estimates reading time (at 225 words per minute) and speaking time (at 150 wpm), finds your longest word, computes average word length, and shows the top keywords by density — ignoring common stop words." },
      { emoji: "⚡", icon: "target", title: "Why it's useful", text: "Writers, students, marketers, and translators use word counts every day. Tweets have character limits. Essays have word targets. SEO descriptions have meta length caps. Blog posts need reading-time estimates for the reader. Having all of these in one live panel saves you from opening a separate app or counting manually." },
      { emoji: "🎯", icon: "printer", title: "How it works", text: "The tool uses JavaScript's Unicode-aware regular expressions to split your text into words — so it correctly counts English, Bangla, Arabic, and mixed-script text. Every metric is computed on the fly inside your browser using memoized pure functions. No network requests, no server, and no analytics anywhere." },
      { emoji: "🔐", icon: "lock", title: "Your text stays with you", text: "There is no server. No accounts. No analytics. Whatever you paste — a novel draft, a client email, medical notes — stays entirely inside your browser. Close the tab and it's gone from memory." },
    ],
    howToTitle: "How to count words",
    howTo: [
      { step: 1, title: "Paste or type your text", description: "Drop text into the editor area — every keystroke updates the counters instantly." },
      { step: 2, title: "Watch the metrics", description: "Words, characters, sentences, paragraphs, reading time, and speaking time update live on the right." },
      { step: 3, title: "Check keyword density", description: "The top keywords appear below the counters, showing how often each word appears and its percentage of total words." },
      { step: 4, title: "Clear or copy", description: "Use Clear to reset, or copy the text back out — nothing was ever saved." },
    ],
    featuresTitle: "Built for real writing",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Text is read and analyzed entirely in your browser." },
      { emoji: "⚡", title: "Live updating", description: "Every keystroke recalculates all counters with no perceptible delay." },
      { emoji: "📊", title: "8+ metrics", description: "Words, characters, characters without spaces, sentences, paragraphs, lines, reading time, speaking time." },
      { emoji: "🔑", title: "Keyword density", description: "Top 8 keywords by frequency, with stop-word filtering." },
      { emoji: "🌐", title: "Unicode-aware", description: "Counts English, Bangla, Arabic, and mixed-script text correctly." },
      { emoji: "💾", title: "No size limits", description: "Up to 1 million characters. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my text uploaded anywhere?", answer: "No. All counting happens inside your browser using pure JavaScript. Nothing is sent over the network." },
      { question: "How are words counted?", answer: "A 'word' is a sequence of Unicode letters, numbers, apostrophes, or hyphens — so mixed-script text, contractions like 'don't', and hyphenated terms like 'state-of-the-art' all count as single words." },
      { question: "How is reading time calculated?", answer: "Reading time uses 225 words per minute, the standard average for silent adult reading. Speaking time uses 150 wpm, close to a natural conversational pace." },
      { question: "What is keyword density?", answer: "It shows how often each significant word appears as a percentage of the total word count. Common stop words like 'the', 'and', 'of' are excluded so the list is more useful." },
      { question: "Does it work with Bangla, Arabic, or other scripts?", answer: "Yes. The counting uses Unicode-aware regular expressions, so any alphabetic script is handled correctly." },
      { question: "Is there a character limit?", answer: "Yes — 1 million characters per session, which is well beyond most practical writing tasks. There is no line or paragraph limit." },
      { question: "Does it save my text between visits?", answer: "No. Reload the page and the editor is empty. Nothing is stored on any server or in your browser's storage." },
    ],
    privacyNote: "Your text is analyzed entirely inside your browser using pure JavaScript. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "শব্দ গণনা",
    heroSubtitle:
      "শব্দ, অক্ষর, বাক্য এবং অনুচ্ছেদ রিয়েল-টাইমে গণনা করুন — সম্পূর্ণ আপনার ব্রাউজারেই। পড়ার সময়, বলার সময়, কীওয়ার্ড ঘনত্ব এবং গড় শব্দ-দৈর্ঘ্য দেখুন। কোনো অ্যাকাউন্ট নেই, কোনো ট্র্যাকিং নেই।",
    heroStats: [
      { value: "লাইভ", label: "আপডেট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "৮+", label: "মেট্রিক" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "টেক্সট কখনো ব্রাউজার ছাড়ে না।" },
      { emoji: "⚡", title: "লাইভ কাউন্টার", text: "প্রতিটি কীস্ট্রোকেই আপডেট।" },
      { emoji: "📊", title: "৮+ মেট্রিক", text: "শব্দ, অক্ষর, বাক্য, অনুচ্ছেদ ইত্যাদি।" },
      { emoji: "⏱️", title: "পড়ার সময়", text: "আপনার টেক্সট পড়তে কত লাগবে।" },
      { emoji: "🔑", title: "কীওয়ার্ড ঘনত্ব", text: "শীর্ষ কীওয়ার্ড এক নজরে।" },
      { emoji: "💾", title: "কিছু সংরক্ষিত হয় না", text: "কোনো অ্যাকাউন্ট বা লগ নেই।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "Word Counter আপনি যা পেস্ট বা টাইপ করছেন তা পড়ে সাথে সাথে শব্দ, অক্ষর (স্পেস সহ/ছাড়া), বাক্য, অনুচ্ছেদ এবং লাইন গণনা করে। এটি পড়ার সময় (২২৫ শব্দ/মিনিটে) এবং বলার সময় (১৫০ শব্দ/মিনিটে) অনুমান করে, দীর্ঘতম শব্দ খুঁজে, গড় শব্দ-দৈর্ঘ্য হিসাব করে, এবং সাধারণ stop word বাদ দিয়ে শীর্ষ কীওয়ার্ড ঘনত্ব দেখায়।" },
      { emoji: "⚡", icon: "target", title: "কেন কাজে লাগে", text: "লেখক, ছাত্র, মার্কেটার এবং অনুবাদক প্রতিদিন word count ব্যবহার করেন। Tweet-এ character limit আছে। Essay-এর word target আছে। SEO meta description-এর দৈর্ঘ্য সীমা আছে। ব্লগ পোস্টের reading-time লাগে। সব একটি লাইভ প্যানেলে থাকলে আলাদা অ্যাপ খুলতে হয় না।" },
      { emoji: "🎯", icon: "printer", title: "কীভাবে কাজ করে", text: "টুলটি JavaScript-এর Unicode-aware regular expression দিয়ে আপনার টেক্সটকে শব্দে ভাগ করে — তাই বাংলা, ইংরেজি, আরবি এবং মিশ্র স্ক্রিপ্ট সঠিকভাবে গণনা করা হয়। প্রতিটি মেট্রিক মেমোইজড pure function দিয়ে আপনার ব্রাউজারেই হিসাব করা হয়।" },
      { emoji: "🔐", icon: "lock", title: "আপনার টেক্সট আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। আপনি যা পেস্ট করেন — উপন্যাসের খসড়া, ক্লায়েন্টের ইমেইল, মেডিক্যাল নোট — সব আপনার ব্রাউজারেই থাকে। ট্যাব বন্ধ করলেই চলে যায়।" },
    ],
    howToTitle: "শব্দ কীভাবে গণনা করবেন",
    howTo: [
      { step: 1, title: "টেক্সট পেস্ট বা টাইপ করুন", description: "এডিটর এলাকায় টেক্সট দিন — প্রতিটি কীস্ট্রোকে কাউন্টার সাথে সাথে আপডেট হয়।" },
      { step: 2, title: "মেট্রিক দেখুন", description: "শব্দ, অক্ষর, বাক্য, অনুচ্ছেদ, পড়ার সময় এবং বলার সময় ডান দিকে লাইভ আপডেট হয়।" },
      { step: 3, title: "কীওয়ার্ড ঘনত্ব দেখুন", description: "কাউন্টারের নিচে শীর্ষ কীওয়ার্ড দেখা যায় — প্রতিটি শব্দ কতবার এসেছে এবং মোট শব্দের কত শতাংশ।" },
      { step: 4, title: "মুছুন বা কপি করুন", description: "Clear দিয়ে রিসেট করুন, বা টেক্সট কপি করুন — কিছুই সংরক্ষিত হয়নি।" },
    ],
    featuresTitle: "প্রকৃত লেখার জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "টেক্সট সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও বিশ্লেষণ করা হয়।" },
      { emoji: "⚡", title: "লাইভ আপডেট", description: "প্রতিটি কীস্ট্রোকে সব কাউন্টার আপডেট।" },
      { emoji: "📊", title: "৮+ মেট্রিক", description: "শব্দ, অক্ষর, স্পেস-ছাড়া অক্ষর, বাক্য, অনুচ্ছেদ, লাইন, পড়ার সময়, বলার সময়।" },
      { emoji: "🔑", title: "কীওয়ার্ড ঘনত্ব", description: "Stop word বাদ দিয়ে শীর্ষ ৮টি কীওয়ার্ড।" },
      { emoji: "🌐", title: "Unicode-সচেতন", description: "বাংলা, ইংরেজি, আরবি, মিশ্র স্ক্রিপ্ট সবই সঠিক।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "১০ লাখ অক্ষর পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার টেক্সট কি আপলোড হয়?", answer: "না। সবকিছু আপনার ব্রাউজারেই pure JavaScript দিয়ে হয়।" },
      { question: "শব্দ কীভাবে গণনা হয়?", answer: "Unicode অক্ষর, সংখ্যা, apostrophe বা hyphen-এর ধারা একটি 'শব্দ' — তাই 'don't' ও 'state-of-the-art' এক শব্দ হিসেবে গণনা হয়।" },
      { question: "পড়ার সময় কীভাবে হিসাব হয়?", answer: "পড়ার সময় ২২৫ শব্দ/মিনিট, বলার সময় ১৫০ শব্দ/মিনিট।" },
      { question: "কীওয়ার্ড ঘনত্ব কী?", answer: "প্রতিটি গুরুত্বপূর্ণ শব্দ কতবার এসেছে এবং মোট শব্দের শতাংশ কত — common stop word বাদ দিয়ে।" },
      { question: "বাংলা, আরবি বা অন্য স্ক্রিপ্টে কাজ করে?", answer: "হ্যাঁ। Unicode-aware regular expression সব স্ক্রিপ্ট হ্যান্ডেল করে।" },
      { question: "Character limit আছে?", answer: "প্রতি সেশনে ১০ লাখ অক্ষর — সাধারণ কাজের জন্য যথেষ্ট।" },
      { question: "টেক্সট কি সেভ হয়?", answer: "না। পেজ রিলোড করলে এডিটর খালি।" },
    ],
    privacyNote: "আপনার টেক্সট সম্পূর্ণ আপনার ব্রাউজারেই pure JavaScript দিয়ে বিশ্লেষণ করা হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type WordCounterContent = typeof wordCounterContent;
