export const urlEncoderContent = {
  en: {
    heroTag: "URL Encoder",
    heroSubtitle:
      "Encode or decode URLs and URI components in your browser. Handles Unicode, emoji, and special characters. Two scopes: encodeURIComponent for query values, encodeURI for full URLs. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Encode", label: "& decode" },
      { value: "100%", label: "Private" },
      { value: "Unicode", label: "Safe" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "URLs never leave your device." },
      { emoji: "🔄", title: "Encode & decode", text: "Both directions, one click." },
      { emoji: "🎯", title: "Two scopes", text: "Component or full URI." },
      { emoji: "🌐", title: "Unicode safe", text: "Bangla, emoji, CJK — all handled." },
      { emoji: "⚡", title: "Instant", text: "Live preview as you type." },
      { emoji: "📋", title: "Copy & paste", text: "One-click clipboard." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "URL Encoder / Decoder converts between raw text and percent-encoded (URL-safe) format. Use it to encode query-string values that contain spaces, ampersands, Bangla characters, or emoji — and to decode back when reading URLs from logs, browsers, or API responses." },
      { emoji: "📄", title: "When you need it", text: "Building API requests with dynamic query parameters. Debugging a URL that has %20, %E0%A6%AC, or other escapes. Reading a search string from a browser address bar. Embedding URLs inside other URLs. All common tasks — no more guessing what a string like %E2%9C%93 means." },
      { emoji: "⚡", title: "Component vs full URL", text: "encodeURIComponent escapes every character except A-Z a-z 0-9 - _ . ! ~ * ' ( ). Use it for a single query value. encodeURI leaves reserved URL characters (: / ? # [ ] @ ! $ & ' ( ) * + , ; =) intact — it's for encoding an entire URL without breaking its structure." },
      { emoji: "🔐", title: "Your data stays with you", text: "There is no server. No accounts. No analytics. URLs often contain API keys, session tokens, or user data. This tool processes everything locally so nothing sensitive ever touches a network." },
    ],
    howToTitle: "How to encode or decode a URL",
    howTo: [
      { step: 1, title: "Paste your input", description: "Paste a raw URL, a URL-encoded string, or just the text you want to encode." },
      { step: 2, title: "Choose mode", description: "Encode (to URL-safe) or Decode (from URL-safe back to plain text)." },
      { step: 3, title: "Pick scope", description: "Component for query values, full URI for entire URLs." },
      { step: 4, title: "Copy the result", description: "Click copy — the output is ready to paste anywhere." },
    ],
    featuresTitle: "Built for real URL work",
    features: [
      { emoji: "🔄", title: "Both directions", description: "Encode and decode in one panel — no toggling pages." },
      { emoji: "🎯", title: "Two scopes", description: "Component (aggressive) or full URI (structure-preserving)." },
      { emoji: "🌐", title: "Unicode aware", description: "Bangla, Arabic, Chinese, emoji — all encoded correctly." },
      { emoji: "⚡", title: "Live preview", description: "Output updates with every keystroke — no button needed." },
      { emoji: "📊", title: "Byte stats", description: "See how many bytes encoding adds or removes." },
      { emoji: "💾", title: "Up to 5 MB", description: "Huge inputs handled fine. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my URL uploaded?", answer: "No. Everything happens in your browser using native encodeURIComponent, encodeURI, decodeURIComponent, and decodeURI. Nothing is sent over the network." },
      { question: "Component vs full URI — which do I need?", answer: "Use Component when you're encoding one piece of a URL, like a search query value. Use Full URI when you're encoding an entire URL and want to keep ://, ?, &, and other separators intact." },
      { question: "Why does a space become %20 and not +?", answer: "encodeURIComponent produces %20. The + convention comes from application/x-www-form-urlencoded (HTML form submissions), not from URL encoding itself. If you need +, encode with %20 then replace — this tool follows the modern standard." },
      { question: "Why does decoding fail sometimes?", answer: "decodeURIComponent throws a URIError when it sees a malformed escape — like a lone % or an incomplete %E sequence. That's expected; fix the input and try again." },
      { question: "Does it handle emoji?", answer: "Yes. Emoji and other non-BMP characters are UTF-8 encoded before percent-encoding, producing multi-byte sequences like %F0%9F%98%80." },
      { question: "Can I decode URLs with Bangla characters?", answer: "Yes — decodeURIComponent reconstructs multi-byte UTF-8 correctly, so Bangla, Arabic, and any other script comes out readable." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your URLs are processed entirely inside your browser using native JavaScript APIs. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "URL এনকোডার",
    heroSubtitle:
      "URL এবং URI component এনকোড বা ডিকোড করুন — সম্পূর্ণ আপনার ব্রাউজারেই। Unicode, emoji ও special character হ্যান্ডেল করে। Component (query value) বা full URI — দুই scope।",
    heroStats: [
      { value: "Encode", label: "ও decode" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "Unicode", label: "নিরাপদ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "URL কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🔄", title: "Encode ও decode", text: "দুই দিকই, এক ক্লিকে।" },
      { emoji: "🎯", title: "দুই scope", text: "Component বা full URI।" },
      { emoji: "🌐", title: "Unicode নিরাপদ", text: "বাংলা, emoji, CJK — সব হ্যান্ডেল।" },
      { emoji: "⚡", title: "তাৎক্ষণিক", text: "Typing-এর সাথে live preview।" },
      { emoji: "📋", title: "কপি ও paste", text: "এক ক্লিকে clipboard।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "URL Encoder / Decoder raw text ও percent-encoded (URL-safe) format-এর মধ্যে convert করে। Space, ampersand, বাংলা অক্ষর বা emoji সহ query value encode করতে — এবং log, browser বা API response থেকে URL পড়ার সময় decode করতে ব্যবহার করুন।" },
      { emoji: "📄", title: "কখন দরকার", text: "Dynamic query parameter দিয়ে API request বানানো। %20, %E0%A6%AC বা অন্য escape সহ URL debug করা। Browser address bar থেকে search string পড়া। URL-এর ভেতরে URL embed করা। সব সাধারণ কাজ — আর guess করতে হবে না %E2%9C%93 মানে কী।" },
      { emoji: "⚡", title: "Component vs full URL", text: "encodeURIComponent A-Z a-z 0-9 - _ . ! ~ * ' ( ) ছাড়া সব escape করে। একটি query value-র জন্য। encodeURI reserved URL character (: / ? # [ ] @ ! $ & ' ( ) * + , ; =) অপরিবর্তিত রাখে — সম্পূর্ণ URL structure ভাঙা ছাড়াই encode করার জন্য।" },
      { emoji: "🔐", title: "আপনার ডেটা আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। URL-এ প্রায়ই API key, session token বা user data থাকে। এই টুল সবকিছু লোকালি process করে।" },
    ],
    howToTitle: "URL কীভাবে encode বা decode করবেন",
    howTo: [
      { step: 1, title: "Input দিন", description: "Raw URL, URL-encoded string, বা encode করার টেক্সট paste করুন।" },
      { step: 2, title: "Mode বাছুন", description: "Encode (URL-safe করতে) বা Decode (URL-safe থেকে plain টেক্সটে)।" },
      { step: 3, title: "Scope বাছুন", description: "Query value-র জন্য Component, সম্পূর্ণ URL-এর জন্য Full URI।" },
      { step: 4, title: "Result কপি করুন", description: "Copy চাপুন — output যেকোনো জায়গায় paste করার জন্য ready।" },
    ],
    featuresTitle: "প্রকৃত URL কাজের জন্য",
    features: [
      { emoji: "🔄", title: "দুই দিকই", description: "এক panel-এ encode ও decode — page toggle নেই।" },
      { emoji: "🎯", title: "দুই scope", description: "Component (aggressive) বা full URI (structure-preserving)।" },
      { emoji: "🌐", title: "Unicode সচেতন", description: "বাংলা, আরবি, চাইনিজ, emoji — সব সঠিকভাবে encode।" },
      { emoji: "⚡", title: "লাইভ preview", description: "প্রতিটি keypress-এ output update — button ছাড়াই।" },
      { emoji: "📊", title: "Byte stats", description: "Encoding কত byte যোগ বা বাদ করল দেখুন।" },
      { emoji: "💾", title: "৫ MB পর্যন্ত", description: "বড় input-ও handle করে।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার URL কি আপলোড হয়?", answer: "না। native encodeURIComponent, encodeURI, decodeURIComponent ও decodeURI দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "Component না full URI — কোনটা লাগবে?", answer: "URL-এর এক টুকরো (যেমন search query value) encode করতে Component। সম্পূর্ণ URL-এর ://, ?, & separator অটুট রেখে encode করতে Full URI।" },
      { question: "Space %20 হয় কেন, + নয়?", answer: "encodeURIComponent %20 দেয়। + convention HTML form submission (application/x-www-form-urlencoded) থেকে এসেছে, URL encoding নিজে থেকে নয়। এই টুল modern standard মানে।" },
      { question: "Decoding fail করে কেন?", answer: "Malformed escape — একা % বা অসম্পূর্ণ %E sequence — দেখলে decodeURIComponent URIError throw করে। Input ঠিক করে আবার চেষ্টা করুন।" },
      { question: "Emoji হ্যান্ডেল করে?", answer: "হ্যাঁ। Emoji ও অন্যান্য non-BMP character UTF-8 encode হয়ে multi-byte sequence দেয়, যেমন %F0%9F%98%80।" },
      { question: "বাংলা character সহ URL decode করা যায়?", answer: "হ্যাঁ — decodeURIComponent multi-byte UTF-8 সঠিকভাবে reconstruct করে, তাই বাংলা, আরবি ও অন্যান্য script পড়া যায়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার URL native JavaScript API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই process হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type UrlEncoderContent = typeof urlEncoderContent;
