export const textCaseContent = {
  en: {
    heroTag: "Text Case Converter",
    heroSubtitle:
      "Convert text between 12 case styles — UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case, and more. Everything runs in your browser. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "12+", label: "Case styles" },
      { value: "100%", label: "Private" },
      { value: "Live", label: "Preview" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Text never leaves your device." },
      { emoji: "🎨", title: "12 case styles", text: "UPPER, lower, Title, camel, snake, and more." },
      { emoji: "⚡", title: "Live preview", text: "Output updates as you type." },
      { emoji: "📋", title: "One-click copy", text: "Copy the result instantly." },
      { emoji: "🌐", title: "Unicode safe", text: "Bangla, Arabic, emoji — all handled." },
      { emoji: "💾", title: "Nothing stored", text: "No accounts, no logs." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Text Case Converter rewrites your text in any of 12 different case styles — from simple UPPERCASE and lowercase to programming conventions like camelCase, snake_case, and kebab-case. Paste once, click a style, copy the result. No retyping, no external tools." },
      { emoji: "📄", title: "When you need it", text: "Bloggers fixing title-case for headlines. Developers converting variable names between naming conventions. Designers preparing tab labels. Anyone who pasted something accidentally with Caps Lock on. Case conversion shows up everywhere — and doing it by hand is slow." },
      { emoji: "⚡", title: "How the conversion works", text: "The tool splits your text into words using Unicode-aware rules that recognize camelCase, PascalCase, snake_case, and kebab-case boundaries. It then reassembles the words according to the chosen style — no dictionaries, no guesswork, deterministic output." },
      { emoji: "🔐", title: "Your text stays with you", text: "There is no server. No accounts. No analytics. Whatever you paste — draft headlines, code snippets, client copy — stays entirely inside your browser. Close the tab and it's gone from memory." },
    ],
    howToTitle: "How to convert text case",
    howTo: [
      { step: 1, title: "Paste your text", description: "Drop text into the editor area — every keystroke updates the preview." },
      { step: 2, title: "Pick a case style", description: "Click UPPER, lower, Title, camel, snake, kebab, or any of the other 12 options." },
      { step: 3, title: "Preview the output", description: "The converted result appears instantly below the input." },
      { step: 4, title: "Copy the result", description: "Click Copy to send the converted text to your clipboard." },
    ],
    featuresTitle: "Built for real text work",
    features: [
      { emoji: "🎨", title: "12+ case styles", description: "UPPER, lower, Title, Sentence, camel, Pascal, snake, kebab, CONSTANT, dot, alternating, inverse." },
      { emoji: "⚡", title: "Live preview", description: "Output recalculates as you type — no button required." },
      { emoji: "🔒", title: "Zero uploads", description: "Text is analyzed entirely in your browser." },
      { emoji: "🌐", title: "Unicode aware", description: "Handles non-ASCII letters, Bangla, Arabic, and emoji correctly." },
      { emoji: "📋", title: "One-click copy", description: "Copy the converted output to your clipboard instantly." },
      { emoji: "💾", title: "No size limits", description: "Up to 500k characters. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my text uploaded?", answer: "No. Everything happens inside your browser using JavaScript. Nothing is sent over the network." },
      { question: "What's the difference between Title Case and Sentence case?", answer: "Title Case capitalizes every significant word (small words like 'the', 'and', 'of' stay lowercase). Sentence case only capitalizes the first letter of each sentence." },
      { question: "How does camelCase know where words start?", answer: "The tool detects word boundaries from existing camelCase (lowercase → uppercase transitions), PascalCase, snake_case, kebab-case, spaces, and other separators. Then it rebuilds the words in your chosen style." },
      { question: "What does 'alternating' do?", answer: "It alternates between upper and lowercase letters: aLtErNaTiNg. Non-letter characters (numbers, spaces, punctuation) don't count toward the alternation." },
      { question: "What does 'inverse' do?", answer: "It flips the case of every letter: 'Hello World' → 'hELLO wORLD'. Useful when you pasted with Caps Lock on." },
      { question: "Does it work with Bangla or Arabic text?", answer: "Yes — the casing functions only affect letters that have a case (English, Greek, Cyrillic). Bangla, Arabic, and other caseless scripts pass through unchanged. Camel, snake, and kebab modes still split words on whitespace and punctuation." },
      { question: "Is there a character limit?", answer: "Yes — 500,000 characters per session, which is well beyond most practical tasks." },
    ],
    privacyNote: "Your text is processed entirely inside your browser using pure JavaScript. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "টেক্সট কেস কনভার্টার",
    heroSubtitle:
      "টেক্সট ১২টি case style-এর মধ্যে convert করুন — UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case ইত্যাদি। সম্পূর্ণ আপনার ব্রাউজারেই।",
    heroStats: [
      { value: "১২+", label: "Case style" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "লাইভ", label: "Preview" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "টেক্সট কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "১২ case style", text: "UPPER, lower, Title, camel, snake ইত্যাদি।" },
      { emoji: "⚡", title: "লাইভ preview", text: "Typing-এর সাথে output update।" },
      { emoji: "📋", title: "এক ক্লিকে কপি", text: "Result সাথে সাথে কপি।" },
      { emoji: "🌐", title: "Unicode নিরাপদ", text: "বাংলা, আরবি, emoji — সব হ্যান্ডেল।" },
      { emoji: "💾", title: "কিছুই সংরক্ষিত নয়", text: "কোনো অ্যাকাউন্ট বা লগ নেই।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Text Case Converter আপনার টেক্সট ১২টি আলাদা case style-এ rewrite করে — সহজ UPPERCASE ও lowercase থেকে শুরু করে programming convention যেমন camelCase, snake_case ও kebab-case পর্যন্ত। একবার paste, একটা style click, result কপি। কোনো retyping নেই, বাইরের tool নেই।" },
      { emoji: "📄", title: "কখন দরকার", text: "ব্লগার headline-এর title-case ঠিক করতে। Developer variable name naming convention-এর মধ্যে convert করতে। Designer tab label বানাতে। যে Caps Lock চালু রেখে paste করে ফেলেছে। Case conversion সব জায়গায় — হাতে করতে slow।" },
      { emoji: "⚡", title: "কনভার্সন কীভাবে কাজ করে", text: "টুলটি Unicode-aware rule দিয়ে আপনার টেক্সট word-এ ভাগ করে — camelCase, PascalCase, snake_case ও kebab-case boundary চিনতে পারে। তারপর নির্বাচিত style অনুযায়ী শব্দ পুনর্গঠন করে — কোনো dictionary নেই, কোনো guess নেই, deterministic output।" },
      { emoji: "🔐", title: "আপনার টেক্সট আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। আপনি যা paste করেন — draft headline, code snippet, client copy — সব আপনার ব্রাউজারেই থাকে।" },
    ],
    howToTitle: "টেক্সট case কীভাবে convert করবেন",
    howTo: [
      { step: 1, title: "টেক্সট paste করুন", description: "Editor area-তে টেক্সট দিন — প্রতিটি keypress-এ preview update হয়।" },
      { step: 2, title: "Case style বাছুন", description: "UPPER, lower, Title, camel, snake, kebab বা বাকি option-এর যেকোনোটা click করুন।" },
      { step: 3, title: "Output দেখুন", description: "Converted result input-এর নিচে সাথে সাথে দেখা যায়।" },
      { step: 4, title: "Result কপি করুন", description: "Copy চেপে converted টেক্সট clipboard-এ পাঠান।" },
    ],
    featuresTitle: "প্রকৃত টেক্সট কাজের জন্য",
    features: [
      { emoji: "🎨", title: "১২+ case style", description: "UPPER, lower, Title, Sentence, camel, Pascal, snake, kebab, CONSTANT, dot, alternating, inverse।" },
      { emoji: "⚡", title: "লাইভ preview", description: "Typing-এর সাথে output recalculate — button ছাড়াই।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "টেক্সট সম্পূর্ণ আপনার ব্রাউজারেই analyze করা হয়।" },
      { emoji: "🌐", title: "Unicode সচেতন", description: "Non-ASCII letter, বাংলা, আরবি ও emoji সঠিকভাবে handle করে।" },
      { emoji: "📋", title: "এক ক্লিকে কপি", description: "Converted output সাথে সাথে clipboard-এ।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "৫ লাখ character পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার টেক্সট কি আপলোড হয়?", answer: "না। JavaScript দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "Title Case আর Sentence case-এর পার্থক্য?", answer: "Title Case প্রতিটি গুরুত্বপূর্ণ word capitalize করে ('the', 'and', 'of' ছোট word lowercase থাকে)। Sentence case শুধু প্রতিটি বাক্যের প্রথম অক্ষর capitalize করে।" },
      { question: "camelCase কীভাবে জানে word কোথায় শুরু?", answer: "টুলটি camelCase (lowercase → uppercase transition), PascalCase, snake_case, kebab-case, space ও অন্য separator থেকে word boundary detect করে। তারপর আপনার নির্বাচিত style-এ শব্দ পুনর্গঠন করে।" },
      { question: "‘Alternating’ কী করে?", answer: "Upper ও lowercase অক্ষর পর্যায়ক্রমে করে: aLtErNaTiNg। সংখ্যা, space, punctuation alternation-এ count হয় না।" },
      { question: "‘Inverse’ কী করে?", answer: "প্রতিটি letter-এর case উল্টে দেয়: 'Hello World' → 'hELLO wORLD'। Caps Lock চালু রেখে paste করলে useful।" },
      { question: "বাংলা বা আরবি টেক্সটে কাজ করে?", answer: "হ্যাঁ — casing function শুধু সেই letter-এ কাজ করে যাদের case আছে (ইংরেজি, গ্রিক, সিরিলিক)। বাংলা, আরবি ও অন্যান্য caseless script অপরিবর্তিত থাকে। camel, snake, kebab mode এখনো whitespace ও punctuation-এ word ভাগ করে।" },
      { question: "Character limit আছে?", answer: "প্রতি সেশনে ৫ লাখ character — সাধারণ কাজের জন্য যথেষ্ট।" },
    ],
    privacyNote: "আপনার টেক্সট pure JavaScript দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই process হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type TextCaseContent = typeof textCaseContent;
