export const jsonFormatterContent = {
  en: {
    heroTag: "JSON Formatter",
    heroSubtitle:
      "Format, validate, and minify JSON in your browser. Paste raw JSON, pick 2/4-space or tab indentation, sort keys, and copy or download the result. Live error messages pinpoint syntax problems. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "Live", label: "Validation" },
      { value: "100%", label: "Private" },
      { value: "Sort keys", label: "Optional" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "JSON never leaves your device." },
      { emoji: "✅", title: "Live validation", text: "Errors shown with line/column." },
      { emoji: "🎨", title: "Pretty print", text: "2/4-space or tab indent." },
      { emoji: "📦", title: "Minify", text: "One-click compact output." },
      { emoji: "🔤", title: "Sort keys", text: "Alphabetical order option." },
      { emoji: "📊", title: "Stats", text: "Keys, arrays, depth, size." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "JSON Formatter takes raw or minified JSON and gives you clean, readable output. It validates the input, shows precise error locations if something's broken, and lets you pretty-print with 2 or 4 spaces (or tabs), sort keys alphabetically, or minify into the smallest possible string. It also reports structural stats — total keys, arrays, and max nesting depth." },
      { emoji: "📄", title: "When you need it", text: "API responses arrive minified and unreadable. Config files get edited by hand and break. Log payloads need inspection. Whatever the source, running it through a formatter turns a wall of text into a navigable tree and catches typos before you ship them." },
      { emoji: "⚡", title: "How it works", text: "The tool uses the browser's native JSON.parse to validate and JSON.stringify to format. Everything runs synchronously in your browser — no network requests. Errors are decoded from native messages and mapped back to line and column numbers so you can jump straight to the problem." },
      { emoji: "🔐", title: "Your data stays with you", text: "There is no server. No accounts. No analytics. JSON often contains secrets — API keys, tokens, user data. This tool processes everything locally so nothing sensitive ever touches a network." },
    ],
    howToTitle: "How to format JSON",
    howTo: [
      { step: 1, title: "Paste your JSON", description: "Paste raw, minified, or pretty-printed JSON into the input panel. Up to 10 MB." },
      { step: 2, title: "Pick indentation", description: "Choose 2-space, 4-space, or tab indentation. Toggle sort keys for alphabetical output." },
      { step: 3, title: "Fix errors if shown", description: "If the JSON is invalid, the error message shows the exact line and column." },
      { step: 4, title: "Copy or download", description: "Copy the formatted result to clipboard or download it as a .json file." },
    ],
    featuresTitle: "Built for real JSON work",
    features: [
      { emoji: "✅", title: "Live validation", description: "Errors appear as you type with line and column numbers." },
      { emoji: "🎨", title: "3 indent styles", description: "2 spaces, 4 spaces, or a real tab — your choice." },
      { emoji: "🔤", title: "Sort keys", description: "Alphabetical ordering for deterministic, diff-friendly output." },
      { emoji: "📦", title: "Minify mode", description: "Shrink JSON to its smallest valid form." },
      { emoji: "📊", title: "Structure stats", description: "Total keys, arrays, and maximum nesting depth." },
      { emoji: "📄", title: "Up to 10 MB", description: "Large payloads handled fine. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my JSON uploaded?", answer: "No. Everything happens in your browser using native JSON.parse and JSON.stringify. Nothing is sent over the network." },
      { question: "What counts as valid JSON?", answer: "Strict JSON per RFC 8259 — double-quoted keys/strings, no trailing commas, no comments, no NaN/Infinity. If your input has those, it will show an error." },
      { question: "What does 'sort keys' do?", answer: "It rearranges object keys alphabetically before formatting. Array order is preserved. Useful when you want deterministic output for version control or diffing." },
      { question: "What's the difference between format and minify?", answer: "Formatted output adds newlines and indentation for readability. Minified output strips all unnecessary whitespace to produce the smallest valid JSON string." },
      { question: "Why does it say my JSON is invalid when it looks fine?", answer: "Common gotchas: single quotes instead of double, trailing commas, comments (// or /* */), unquoted keys, or NaN/Infinity. JSON is stricter than JavaScript object syntax." },
      { question: "Can I paste JSON with a BOM or Windows line endings?", answer: "Yes — BOM and CRLF are handled. If you see unexpected errors, try retyping the first character (BOM can be invisible)." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your JSON is parsed and formatted entirely inside your browser using native JavaScript APIs. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "JSON ফরম্যাটার",
    heroSubtitle:
      "JSON ফরম্যাট, ভ্যালিডেট এবং মিনিফাই করুন — সম্পূর্ণ আপনার ব্রাউজারেই। 2/4 space বা tab indentation, sort keys, কপি বা ডাউনলোড। লাইভ error message সঠিক line ও column দেখায়।",
    heroStats: [
      { value: "লাইভ", label: "ভ্যালিডেশন" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "Sort keys", label: "ঐচ্ছিক" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "JSON কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "✅", title: "লাইভ ভ্যালিডেশন", text: "Error line/column সহ দেখায়।" },
      { emoji: "🎨", title: "Pretty print", text: "2/4 space বা tab indent।" },
      { emoji: "📦", title: "Minify", text: "এক ক্লিকে compact output।" },
      { emoji: "🔤", title: "Sort keys", text: "Alphabetical order option।" },
      { emoji: "📊", title: "Stats", text: "Keys, arrays, depth, size।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "JSON Formatter raw বা minified JSON নিয়ে পরিষ্কার, পাঠযোগ্য output দেয়। Input validate করে, ভুল থাকলে সঠিক line ও column দেখায়, এবং 2 বা 4 space (বা tab) দিয়ে pretty-print করা, keys alphabetically sort করা, বা সবচেয়ে ছোট string-এ minify করার সুবিধা দেয়। সাথে structural stats — total keys, arrays, max nesting depth।" },
      { emoji: "📄", title: "কখন দরকার", text: "API response minified ও অপাঠ্য আসে। Config file হাতে edit করে break হয়। Log payload inspect করতে হয়। যে source-ই হোক, formatter দিয়ে চালালে text-এর দেয়াল navigable tree-তে বদলায় এবং ship করার আগে typo ধরা পড়ে।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "টুলটি browser-এর native JSON.parse দিয়ে validate এবং JSON.stringify দিয়ে format করে। সবকিছু synchronously আপনার ব্রাউজারেই — কোনো network request নেই। Error message decode করে line ও column number-এ map করা হয়, যাতে সরাসরি সমস্যায় jump করা যায়।" },
      { emoji: "🔐", title: "আপনার ডেটা আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। JSON-এ প্রায়ই secret থাকে — API key, token, user data। এই টুল সবকিছু লোকালি process করে, তাই sensitive কিছু কখনো নেটওয়ার্ক ছোঁয় না।" },
    ],
    howToTitle: "JSON কীভাবে ফরম্যাট করবেন",
    howTo: [
      { step: 1, title: "JSON দিন", description: "Raw, minified, বা pretty JSON input panel-এ paste করুন। ১০ MB পর্যন্ত।" },
      { step: 2, title: "Indentation বাছুন", description: "2-space, 4-space, বা tab। Sort keys toggle করলে alphabetical।" },
      { step: 3, title: "Error ঠিক করুন", description: "JSON invalid হলে error message exact line ও column দেখাবে।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "Result clipboard-এ কপি করুন বা .json file হিসেবে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত JSON কাজের জন্য",
    features: [
      { emoji: "✅", title: "লাইভ ভ্যালিডেশন", description: "Typing-এর সময়ই error সহ line ও column number।" },
      { emoji: "🎨", title: "৩ indentation", description: "2 space, 4 space, বা real tab — আপনার পছন্দ।" },
      { emoji: "🔤", title: "Sort keys", description: "Deterministic, diff-friendly output-এর জন্য alphabetical।" },
      { emoji: "📦", title: "Minify mode", description: "JSON-কে smallest valid form-এ সংকুচিত করুন।" },
      { emoji: "📊", title: "Structure stats", description: "Total keys, arrays, এবং max nesting depth।" },
      { emoji: "📄", title: "১০ MB পর্যন্ত", description: "বড় payload-ও handle করে।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার JSON কি আপলোড হয়?", answer: "না। native JSON.parse ও JSON.stringify দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "কী valid JSON?", answer: "RFC 8259 অনুযায়ী strict JSON — double-quoted key/string, trailing comma নেই, comment নেই, NaN/Infinity নেই।" },
      { question: "‘Sort keys’ কী করে?", answer: "Format করার আগে object key alphabetically সাজায়। Array order অপরিবর্তিত। Version control বা diff-এর জন্য useful।" },
      { question: "Format আর Minify-এর পার্থক্য?", answer: "Formatted output readability-র জন্য newline ও indentation যোগ করে। Minified সব অপ্রয়োজনীয় whitespace সরিয়ে smallest valid JSON string তৈরি করে।" },
      { question: "ঠিক দেখাচ্ছে কিন্তু invalid বলছে কেন?", answer: "সাধারণ কারণ: single quotes, trailing comma, comment (// বা /* */), unquoted key, বা NaN/Infinity। JSON JavaScript object syntax-এর থেকে কঠিন।" },
      { question: "BOM বা Windows line ending সহ কাজ করে?", answer: "হ্যাঁ — BOM ও CRLF handle হয়।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার JSON native JavaScript API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই parse ও format হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type JsonFormatterContent = typeof jsonFormatterContent;
