/* ============================================================
 * Tool Meta Generator
 * ------------------------------------------------------------
 * Reads:  src/data/tools.ts
 * Writes: functions/_data.ts (compact meta map for middleware)
 *
 * Run:  npm run tool:meta
 * Auto: runs before `npm run build` and in Cloudflare
 * ============================================================ */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { tools } from "../src/data/tools";

const OUT_DIR = resolve(process.cwd(), "functions");
const OUT_FILE = resolve(OUT_DIR, "_data.ts");

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const entries = tools
  .map((t) => {
    const slug = t.path.replace(/^\/tools\//, "");
    const title = t.seo?.title || `${t.name} — Free | AHADEX Tools`;
    const description = t.seo?.description || t.description;
    const ogImage = t.seo?.ogImage || "/images/og/default-og.svg";
    return `  ${JSON.stringify(slug)}: {
    name: ${JSON.stringify(t.name)},
    path: ${JSON.stringify(t.path)},
    title: ${JSON.stringify(title)},
    description: ${JSON.stringify(description)},
    ogImage: ${JSON.stringify(ogImage)},
  },`;
  })
  .join("\n");

const file = `/* ============================================================
 * AUTO-GENERATED — do not edit by hand
 * Generated by scripts/generate-tool-meta.ts
 * Source: src/data/tools.ts
 * ============================================================ */

export interface ToolMeta {
  name: string;
  path: string;
  title: string;
  description: string;
  ogImage: string;
}

export const TOOL_META: Record<string, ToolMeta> = {
${entries}
};
`;

writeFileSync(OUT_FILE, file, "utf-8");
console.log(`✅ Generated ${tools.length} tool meta entries → ${OUT_FILE}`);
