export const imageMetadataContent = {
  en: {
    heroTag: "Image Metadata",
    heroSubtitle:
      "View EXIF, GPS, camera, and file metadata hidden inside your photos — right in your browser. See the camera model, exposure, timestamp, GPS coordinates, and more. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "EXIF", label: "Camera data" },
      { value: "GPS", label: "Location" },
      { value: "100%", label: "Private" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "📷", title: "Camera info", text: "Make, model, lens, and software." },
      { emoji: "⚡", title: "Exposure", text: "Shutter, aperture, ISO, focal length." },
      { emoji: "📍", title: "GPS location", text: "Coordinates with a map link." },
      { emoji: "🕐", title: "Timestamps", text: "When the photo was taken." },
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "🌐", title: "Broad support", text: "JPG, PNG, WebP, HEIC, TIFF." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Image Metadata Viewer reads the hidden metadata inside your photos and displays it in clean, grouped sections. Every modern camera and phone writes EXIF data into photos — camera make and model, lens, shutter speed, aperture, ISO, focal length, GPS coordinates, timestamps, and more. This tool extracts all of it and shows it in one place." },
      { emoji: "📍", title: "Why it matters", text: "Metadata tells the full story of a photo. It can help you verify a camera's settings, prove when a photo was taken, find the exact location of a shoot, or check whether a social-media site stripped your metadata before publishing. It's also the first step before removing sensitive data before sharing." },
      { emoji: "⚡", title: "How it works", text: "The tool uses exifr, a fast JavaScript library, to parse the EXIF, TIFF, and GPS blocks of your image file. All parsing happens locally inside your browser using the File API. Basic info like dimensions is read directly from the decoded image. No network requests are involved." },
      { emoji: "🔐", title: "Your privacy is intact", text: "There is no server. No accounts. No analytics. Your photos — including any GPS coordinates — stay entirely inside your browser. Close the tab and everything is gone from memory." },
    ],
    howToTitle: "How to view image metadata",
    howTo: [
      { step: 1, title: "Drop your image", description: "Drag a JPG, PNG, WebP, HEIC, or TIFF file into the upload area, or click to browse." },
      { step: 2, title: "See preview and basic info", description: "The image appears with its filename, size, type, and pixel dimensions." },
      { step: 3, title: "Read the metadata groups", description: "Camera, exposure, date & time, GPS location, and image details appear in grouped sections." },
      { step: 4, title: "Open GPS on a map", description: "If the photo has coordinates, click the map link to see the location on OpenStreetMap." },
    ],
    featuresTitle: "Built for real metadata",
    features: [
      { emoji: "📷", title: "Full EXIF", description: "Camera, lens, exposure, ISO, focal length, flash, and more." },
      { emoji: "📍", title: "GPS with map", description: "Decimal coordinates plus a one-click map link." },
      { emoji: "🕐", title: "Timestamps", description: "Date taken, created, modified — with timezone when present." },
      { emoji: "🔒", title: "Zero uploads", description: "All parsing happens in your browser. Nothing leaves your device." },
      { emoji: "🌐", title: "Multi-format", description: "JPG, PNG, WebP, HEIC, and TIFF are all supported." },
      { emoji: "💾", title: "No size limits", description: "Up to 50 MB per file. No signup, no quota, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Are my photos uploaded?", answer: "No. Everything runs inside your browser using the File API and exifr. Your files never leave your device." },
      { question: "What metadata can I see?", answer: "Camera make and model, lens, exposure time, aperture, ISO, focal length, flash, white balance, metering mode, timestamps, GPS coordinates, altitude, orientation, and more — whatever the file contains." },
      { question: "Why does my image show no EXIF data?", answer: "Many sources strip metadata — screenshots, images saved from social media, and many PNGs have no EXIF at all. If your file has none, only basic file info will be shown." },
      { question: "Does it work with HEIC files?", answer: "Yes, on browsers that can decode HEIC (mostly Safari). Other browsers may fail to preview the image but still read its metadata." },
      { question: "Can I see the GPS location on a map?", answer: "Yes. When the file contains GPS coordinates, a one-click OpenStreetMap link appears in the Location group." },
      { question: "Does it remove metadata?", answer: "No — this tool only reads. If you need to strip metadata, use a dedicated metadata remover (coming soon)." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your images and their metadata are read entirely inside your browser using exifr and the File API. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ইমেজ মেটাডেটা",
    heroSubtitle:
      "আপনার ছবির ভেতরে লুকানো EXIF, GPS, ক্যামেরা ও ফাইলের তথ্য দেখুন — সম্পূর্ণ আপনার ব্রাউজারেই। ক্যামেরার মডেল, exposure, সময়, GPS location — সব দেখুন। কোনো আপলোড নেই, কোনো সার্ভার নেই।",
    heroStats: [
      { value: "EXIF", label: "ক্যামেরা ডেটা" },
      { value: "GPS", label: "লোকেশন" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "📷", title: "ক্যামেরার তথ্য", text: "Make, model, lens, software।" },
      { emoji: "⚡", title: "Exposure", text: "Shutter, aperture, ISO, focal length।" },
      { emoji: "📍", title: "GPS লোকেশন", text: "Coordinate ও map link সহ।" },
      { emoji: "🕐", title: "টাইমস্ট্যাম্প", text: "ছবি কখন তোলা হয়েছে।" },
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🌐", title: "ব্রড সাপোর্ট", text: "JPG, PNG, WebP, HEIC, TIFF।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Image Metadata Viewer আপনার ছবির ভেতরে লুকানো metadata পড়ে পরিষ্কারভাবে দেখায়। প্রতিটি আধুনিক ক্যামেরা ও ফোন ছবিতে EXIF data লেখে — ক্যামেরার make, model, lens, shutter speed, aperture, ISO, focal length, GPS coordinate, timestamp ইত্যাদি। এই টুল সব বের করে এক জায়গায় দেখায়।" },
      { emoji: "📍", title: "কেন দরকার", text: "Metadata একটি ছবির পুরো গল্প বলে। এটি ক্যামেরার সেটিং verify করতে, ছবি কখন তোলা হয়েছে প্রমাণ করতে, শুটের সঠিক location জানতে, বা কোনো সোশ্যাল মিডিয়া সাইট আপনার metadata মুছে দিয়েছে কি না দেখতে সাহায্য করে।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "টুলটি exifr নামক দ্রুত JavaScript library দিয়ে আপনার ছবির EXIF, TIFF ও GPS block parse করে। সবকিছু File API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই। কোনো network request নেই।" },
      { emoji: "🔐", title: "আপনার প্রাইভেসি অটুট", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। আপনার ছবি — যেকোনো GPS coordinate সহ — সম্পূর্ণ আপনার ব্রাউজারেই থাকে। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "ছবির metadata কীভাবে দেখবেন",
    howTo: [
      { step: 1, title: "ছবি দিন", description: "JPG, PNG, WebP, HEIC বা TIFF ফাইল ড্র্যাগ করুন বা ক্লিক করুন।" },
      { step: 2, title: "প্রিভিউ ও বেসিক তথ্য", description: "ছবিটি filename, size, type ও pixel dimension সহ দেখা যায়।" },
      { step: 3, title: "Metadata group পড়ুন", description: "Camera, exposure, date & time, GPS location, image details — গুছানো section-এ দেখা যায়।" },
      { step: 4, title: "Map-এ GPS দেখুন", description: "Coordinate থাকলে map link ক্লিক করে OpenStreetMap-এ location দেখুন।" },
    ],
    featuresTitle: "প্রকৃত metadata-র জন্য তৈরি",
    features: [
      { emoji: "📷", title: "সম্পূর্ণ EXIF", description: "ক্যামেরা, lens, exposure, ISO, focal length, flash এবং আরও।" },
      { emoji: "📍", title: "Map সহ GPS", description: "Decimal coordinate + এক ক্লিকে map link।" },
      { emoji: "🕐", title: "টাইমস্ট্যাম্প", description: "Taken, created, modified — timezone সহ যখন উপলব্ধ।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "সব parse আপনার ব্রাউজারেই। কিছুই ডিভাইস ছাড়ে না।" },
      { emoji: "🌐", title: "মাল্টি-ফরম্যাট", description: "JPG, PNG, WebP, HEIC, TIFF — সবই সাপোর্টেড।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ছবি কি আপলোড হয়?", answer: "না। File API ও exifr দিয়ে সবকিছু আপনার ব্রাউজারেই।" },
      { question: "কী কী metadata দেখতে পারি?", answer: "ক্যামেরা make/model, lens, exposure, aperture, ISO, focal length, flash, white balance, metering, timestamp, GPS coordinate, altitude, orientation — যতটুকু ফাইলে আছে।" },
      { question: "কেন আমার ছবিতে EXIF data নেই?", answer: "অনেক source metadata মুছে দেয় — screenshot, সোশ্যাল মিডিয়া থেকে সেভ করা ছবি, এবং অনেক PNG-তে EXIF নেই।" },
      { question: "HEIC ফাইলে কাজ করে?", answer: "হ্যাঁ, যে browser HEIC decode করতে পারে (মূলত Safari)-এ। অন্য browser-এ preview না হলেও metadata পড়া যায়।" },
      { question: "Map-এ GPS দেখতে পারবো?", answer: "হ্যাঁ। GPS coordinate থাকলে Location group-এ OpenStreetMap link দেখা যায়।" },
      { question: "এটা metadata মুছে দেয়?", answer: "না — এই টুল শুধু পড়ে। Metadata মুছতে আলাদা টুল লাগবে (শীঘ্রই আসছে)।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি ও তার metadata exifr ও File API দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type ImageMetadataContent = typeof imageMetadataContent;
