export const characterCounterContent = {
  en: {
    heroTag: "Character Counter",
    heroSubtitle:
      "Count characters against platform limits in real time — X (Twitter), Instagram, LinkedIn, SMS, meta descriptions, and more. See live what fits and what doesn't. Everything runs in your browser.",
    heroStats: [
      { value: "8 platforms", label: "Limits tracked" },
      { value: "Live", label: "Update" },
      { value: "100%", label: "Private" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Text never leaves your browser." },
      { emoji: "⚡", title: "Live counters", text: "Updates with every keystroke." },
      { emoji: "🎯", title: "8 platform limits", text: "X, Instagram, LinkedIn, SMS, SEO..." },
      { emoji: "📊", title: "Real-time alerts", text: "Over-limit detection with color coding." },
      { emoji: "📋", title: "One-click copy", text: "Copy text anywhere instantly." },
      { emoji: "💾", title: "Nothing stored", text: "No accounts, no logs." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "Character Counter tracks your text against eight different platform limits at once. Type or paste anything and see live how many characters you have left for X (Twitter) at 280, an SMS at 160, an SEO meta description at 160, an Instagram caption at 2,200, a LinkedIn post at 3,000, and more. Over-limit platforms are flagged in red so you can trim instantly." },
      { emoji: "📄", title: "Why you need it", text: "Different platforms have wildly different character limits, and getting it wrong means rejected posts, truncated SEO snippets, or split SMS messages. Writers, social media managers, SEO specialists, and developers use character counters daily. Having all limits in one live panel saves time and prevents embarrassing truncations." },
      { emoji: "⚡", title: "How it works", text: "The tool counts characters in real time using JavaScript. It tracks total characters (including spaces), characters without spaces, words, lines, and paragraphs. Then it compares the total against each platform's limit, showing the remaining count in green (safe), amber (close to limit), or red (over limit). Nothing is uploaded — the entire tool runs in your browser." },
      { emoji: "🔐", title: "Your text stays with you", text: "There is no server. No accounts. No analytics on the text itself. Whatever you paste — a tweet draft, a client email, medical notes — stays entirely inside your browser. Close the tab and it's gone from memory." },
    ],
    howToTitle: "How to check character count",
    howTo: [
      { step: 1, title: "Paste or type your text", description: "Drop text into the editor — every keystroke updates the counters live." },
      { step: 2, title: "Watch the platform limits", description: "See how many characters remain for each platform, color-coded for easy scanning." },
      { step: 3, title: "Trim if needed", description: "Over-limit platforms show in red — trim your text until every target goes green." },
      { step: 4, title: "Copy or download", description: "Copy the text to clipboard or download as a .txt file." },
    ],
    featuresTitle: "Built for real writing",
    features: [
      { emoji: "🎯", title: "8 platform limits", description: "X, Instagram, LinkedIn, Facebook, YouTube, SMS, SEO title, meta description." },
      { emoji: "⚡", title: "Live updating", description: "Every keystroke recalculates all counters with no perceptible delay." },
      { emoji: "🚨", title: "Over-limit alerts", description: "Red highlights show exactly which platforms you've exceeded." },
      { emoji: "📊", title: "Full breakdown", description: "Characters, characters without spaces, words, lines, paragraphs." },
      { emoji: "🌐", title: "Unicode-aware", description: "Counts Bangla, Arabic, emoji, and mixed-script text correctly." },
      { emoji: "💾", title: "No size limits", description: "Up to 500k characters. No signup, no watermark." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my text uploaded?", answer: "No. All counting happens inside your browser using pure JavaScript. Nothing is sent over the network." },
      { question: "How are characters counted?", answer: "Every character in the text — including spaces, punctuation, and emoji — counts as one. This matches how X (Twitter), SMS, and most platforms count." },
      { question: "Are the platform limits accurate?", answer: "Yes, they're the current documented limits as of 2026. Platforms occasionally change limits — if you spot a change, let us know." },
      { question: "Does emoji count as one character?", answer: "For our counter, yes. Most platforms also count emoji as one character, though some count them as two depending on encoding." },
      { question: "What's the difference between 'characters' and 'characters without spaces'?", answer: "Characters includes every character (including spaces). Characters without spaces strips whitespace. SEO tools often want the length without spaces for URLs." },
      { question: "Is there a character limit?", answer: "Yes — 500k characters per session, well beyond most practical tasks. There's no line or paragraph limit." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your text is analyzed entirely inside your browser using pure JavaScript. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "ক্যারেক্টার কাউন্টার",
    heroSubtitle:
      "প্ল্যাটফর্মের সীমার বিপরীতে আপনার টেক্সটের ক্যারেক্টার গণনা করুন — X (টুইটার), ইনস্টাগ্রাম, লিংকডইন, SMS, মেটা ডেসক্রিপশন ইত্যাদি। কতটা ফিট হবে লাইভে দেখুন।",
    heroStats: [
      { value: "৮ প্ল্যাটফর্ম", label: "সীমা ট্র্যাক" },
      { value: "লাইভ", label: "আপডেট" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "টেক্সট কখনো ব্রাউজার ছাড়ে না।" },
      { emoji: "⚡", title: "লাইভ কাউন্টার", text: "প্রতিটি কীস্ট্রোকেই আপডেট।" },
      { emoji: "🎯", title: "৮টি সীমা", text: "X, ইনস্টাগ্রাম, লিংকডইন, SMS..." },
      { emoji: "📊", title: "লাইভ সতর্কতা", text: "সীমা ছাড়ালে রঙে দেখায়।" },
      { emoji: "📋", title: "এক ক্লিকে কপি", text: "সাথে সাথে কপি করুন।" },
      { emoji: "💾", title: "কিছু সংরক্ষিত নয়", text: "কোনো লগ বা অ্যাকাউন্ট নেই।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "Character Counter আপনার টেক্সট আটটি আলাদা প্ল্যাটফর্ম সীমার বিপরীতে ট্র্যাক করে। কিছু লিখুন বা পেস্ট করুন এবং লাইভে দেখুন X (টুইটার)-এ ২৮০-এর মধ্যে কত বাকি, SMS-এ ১৬০-এর মধ্যে কত, SEO মেটা ডেসক্রিপশনে ১৬০-এর মধ্যে কত, ইনস্টাগ্রাম ক্যাপশনে ২,২০০-এর মধ্যে কত, লিংকডইন পোস্টে ৩,০০০-এর মধ্যে কত।" },
      { emoji: "📄", title: "কেন দরকার", text: "প্রতিটি প্ল্যাটফর্মের character limit আলাদা। ভুল হলে পোস্ট reject, ট্রাঙ্কেটেড SEO snippet, বা বিভক্ত SMS। লেখক, সোশ্যাল মিডিয়া ম্যানেজার, SEO বিশেষজ্ঞ সবাই প্রতিদিন ব্যবহার করেন।" },
      { emoji: "⚡", title: "কীভাবে কাজ করে", text: "টুলটি JavaScript দিয়ে লাইভে ক্যারেক্টার গণনা করে। মোট ক্যারেক্টার, স্পেস-ছাড়া ক্যারেক্টার, শব্দ, লাইন ও অনুচ্ছেদ ট্র্যাক করে। তারপর প্রতিটি প্ল্যাটফর্মের সীমার সাথে তুলনা করে — বাকি সংখ্যা সবুজ (নিরাপদ), হলুদ (কাছে), বা লাল (অতিক্রান্ত)।" },
      { emoji: "🔐", title: "আপনার টেক্সট আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। আপনি যা পেস্ট করেন সব আপনার ব্রাউজারেই থাকে। ট্যাব বন্ধ করলেই চলে যায়।" },
    ],
    howToTitle: "ক্যারেক্টার গণনা কীভাবে করবেন",
    howTo: [
      { step: 1, title: "টেক্সট পেস্ট বা টাইপ করুন", description: "এডিটরে টেক্সট দিন — প্রতিটি কীস্ট্রোকে লাইভ আপডেট।" },
      { step: 2, title: "প্ল্যাটফর্ম সীমা দেখুন", description: "প্রতিটি প্ল্যাটফর্মের জন্য কত বাকি দেখুন — রঙে চিহ্নিত।" },
      { step: 3, title: "প্রয়োজনে কমিয়ে আনুন", description: "লাল প্ল্যাটফর্ম মানে সীমা ছাড়িয়ে গেছে — সবুজ না হওয়া পর্যন্ত টেক্সট কমান।" },
      { step: 4, title: "কপি বা ডাউনলোড", description: "Text কপি করুন বা .txt ফাইল হিসেবে ডাউনলোড করুন।" },
    ],
    featuresTitle: "প্রকৃত লেখার জন্য তৈরি",
    features: [
      { emoji: "🎯", title: "৮টি সীমা", description: "X, ইনস্টাগ্রাম, লিংকডইন, ফেসবুক, ইউটিউব, SMS, SEO টাইটেল, মেটা।" },
      { emoji: "⚡", title: "লাইভ আপডেট", description: "প্রতিটি কীস্ট্রোকে সব কাউন্টার আপডেট।" },
      { emoji: "🚨", title: "সীমা সতর্কতা", description: "লাল হাইলাইট দেখায় কোথায় সীমা ছাড়িয়েছেন।" },
      { emoji: "📊", title: "সম্পূর্ণ বিশ্লেষণ", description: "ক্যারেক্টার, স্পেস-ছাড়া, শব্দ, লাইন, অনুচ্ছেদ।" },
      { emoji: "🌐", title: "Unicode-সচেতন", description: "বাংলা, আরবি, emoji সবই সঠিক।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "৫ লাখ ক্যারেক্টার পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার টেক্সট আপলোড হয়?", answer: "না। pure JavaScript দিয়ে আপনার ব্রাউজারেই।" },
      { question: "ক্যারেক্টার কীভাবে গণনা হয়?", answer: "স্পেস, punctuation, emoji — সব একটি ক্যারেক্টার হিসেবে গণনা হয়।" },
      { question: "প্ল্যাটফর্মের সীমা সঠিক?", answer: "হ্যাঁ, ২০২৬-এর ডকুমেন্টেড সীমা। কোনো পরিবর্তন দেখলে জানান।" },
      { question: "Emoji কি এক ক্যারেক্টার?", answer: "আমাদের কাউন্টারে হ্যাঁ। বেশিরভাগ প্ল্যাটফর্মও এক হিসেবে গণনা করে।" },
      { question: "Characters আর characters without spaces-এর পার্থক্য?", answer: "'Characters' — স্পেস সহ, 'Without spaces' — স্পেস ছাড়া।" },
      { question: "Character limit আছে?", answer: "৫ লাখ ক্যারেক্টার প্রতি সেশনে।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার টেক্সট pure JavaScript দিয়ে সম্পূর্ণ ব্রাউজারেই বিশ্লেষণ হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type CharacterCounterContent = typeof characterCounterContent;
