export const mergePdfContent = {
  en: {
    heroTag: "Merge PDF",
    heroSubtitle:
      "Combine multiple PDF files into one document right in your browser. Drag, reorder, merge, and download — no uploads, no servers, no accounts. Everything runs locally with pdf-lib.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "20", label: "Max files" },
      { value: "Local", label: "Processing" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Instant merge", text: "Runs in your browser." },
      { emoji: "🔀", title: "Reorder files", text: "Change the order before merging." },
      { emoji: "📄", title: "Preserves quality", text: "Pages copied exactly as-is." },
      { emoji: "📦", title: "Up to 20 PDFs", text: "Combine many documents at once." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "Merge PDF combines two or more PDF files into a single document. Drop the files, drag to reorder, and click Merge — the tool builds the new PDF in memory and downloads it instantly. Every page is copied exactly as it was, so quality, fonts, images, and layouts are never altered." },
      { emoji: "📄", icon: "target", title: "When you need it", text: "Combining invoices into one statement, merging scanned chapters into a single report, uniting signed contracts — any time you have several PDFs and need them to be one file. This tool avoids uploading those documents anywhere, which matters for contracts, IDs, and internal records." },
      { emoji: "⚡", icon: "printer", title: "How the merge works", text: "The tool uses pdf-lib — a pure-JavaScript PDF library. Each file is read into memory, its pages are copied byte-for-byte into a new PDF document, and the result is saved as a single Blob. No compression, no re-rendering, no network traffic at any point." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your files is gone from memory." },
    ],
    howToTitle: "How to merge PDFs",
    howTo: [
      { step: 1, title: "Drop your PDF files", description: "Drag PDF files into the upload area, or click to browse. Up to 20 files, each up to 100 MB." },
      { step: 2, title: "Reorder files", description: "Use the up/down arrows to change file order. Use X to remove a file. The final PDF follows this order exactly." },
      { step: 3, title: "Click Merge", description: "The tool builds the merged PDF in your browser and downloads it automatically." },
      { step: 4, title: "Or re-download", description: "If you lose the download, click the Download button again — no need to re-merge." },
    ],
    featuresTitle: "Built for real merging",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Files are read and merged entirely in your browser." },
      { emoji: "📄", title: "Up to 20 PDFs", description: "Combine up to 20 files into one document — no page-count limit." },
      { emoji: "🔀", title: "Full reordering", description: "Change the order of files before merging with up/down buttons." },
      { emoji: "🎯", title: "Page-exact copy", description: "Every page is copied byte-for-byte with no re-rendering or quality loss." },
      { emoji: "⚡", title: "Fast processing", description: "A 20-file merge typically completes in a few seconds on modern hardware." },
      { emoji: "💾", title: "No size limits", description: "Files up to 100 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my PDFs get uploaded to a server?", answer: "No. Everything happens inside your browser using pdf-lib. Your files never leave your device." },
      { question: "How many PDFs can I merge?", answer: "Up to 20 files at once. Each file can be up to 100 MB." },
      { question: "Is there a page-count limit?", answer: "No. As long as the total file size and count stay within the limits, you can merge as many pages as you want." },
      { question: "Will the PDF quality drop?", answer: "No. Pages are copied byte-for-byte without re-rendering — the merged PDF is identical to the originals." },
      { question: "Can I merge password-protected PDFs?", answer: "Encrypted PDFs will fail to load. Decrypt them first with the owner's password before merging." },
      { question: "Can I split a merged PDF?", answer: "Not with this tool. Use our Split PDF tool for that." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your PDF files are read and merged entirely inside your browser using pdf-lib. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF মার্জ",
    heroSubtitle:
      "একাধিক PDF ফাইল এক ডকুমেন্টে যুক্ত করুন — সম্পূর্ণ আপনার ব্রাউজারেই। ড্র্যাগ করুন, ক্রম বদলান, মার্জ করুন, এবং ডাউনলোড করুন। কোনো আপলোড নেই।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "২০", label: "সর্বোচ্চ ফাইল" },
      { value: "লোকাল", label: "প্রসেসিং" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক মার্জ", text: "ব্রাউজারেই চলে।" },
      { emoji: "🔀", title: "ফাইল reorder", text: "মার্জের আগে ক্রম বদলান।" },
      { emoji: "📄", title: "কোয়ালিটি সংরক্ষিত", text: "পেজ হুবহু কপি হয়।" },
      { emoji: "📦", title: "২০টি পর্যন্ত PDF", text: "একসাথে অনেক ডকুমেন্ট যুক্ত করুন।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি হয়।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "Merge PDF দুই বা ততোধিক PDF ফাইল এক ডকুমেন্টে যুক্ত করে। ফাইল ড্রপ করুন, ক্রম বদলান, Merge চাপুন — টুলটি নতুন PDF মেমরিতে তৈরি করে সাথে সাথে ডাউনলোড করে। প্রতিটি পেজ হুবহু কপি হয় — কোয়ালিটি, ফন্ট, ছবি, লেআউট কখনো পরিবর্তিত হয় না।" },
      { emoji: "📄", icon: "target", title: "কখন দরকার", text: "ইনভয়েসগুলো এক স্টেটমেন্টে, স্ক্যান করা চ্যাপ্টারগুলো এক রিপোর্টে, সাইন করা কন্ট্রাক্টগুলো একসাথে — যখন একাধিক PDF এক ফাইল করতে চান। এই টুল সেগুলো কোথাও আপলোড করে না, যা কন্ট্রাক্ট, ID এবং ইন্টার্নাল রেকর্ডের জন্য গুরুত্বপূর্ণ।" },
      { emoji: "⚡", icon: "printer", title: "মার্জ কীভাবে কাজ করে", text: "টুলটি pdf-lib ব্যবহার করে — একটি pure-JavaScript PDF লাইব্রেরি। প্রতিটি ফাইল মেমরিতে পড়া হয়, পেজ byte-for-byte নতুন PDF ডকুমেন্টে কপি হয়, এবং ফলাফল একটি Blob হিসেবে সেভ হয়।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "PDF কীভাবে মার্জ করবেন",
    howTo: [
      { step: 1, title: "PDF ফাইল দিন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ২০টি পর্যন্ত ফাইল, প্রতি ফাইল ১০০ MB পর্যন্ত।" },
      { step: 2, title: "ফাইল সাজান", description: "উপরে-নিচে অ্যারো দিয়ে ক্রম বদলান। X চেপে ফাইল মুছুন। চূড়ান্ত PDF এই ক্রম অনুসরণ করবে।" },
      { step: 3, title: "Merge চাপুন", description: "টুলটি আপনার ব্রাউজারেই মার্জড PDF তৈরি করে এবং স্বয়ংক্রিয়ভাবে ডাউনলোড করে।" },
      { step: 4, title: "বা আবার ডাউনলোড", description: "ডাউনলোড হারালে আবার Download চাপুন — আবার merge করতে হবে না।" },
    ],
    featuresTitle: "প্রকৃত মার্জের জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ফাইল সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও মার্জ করা হয়।" },
      { emoji: "📄", title: "২০টি পর্যন্ত PDF", description: "২০টি ফাইল এক ডকুমেন্টে যুক্ত করুন।" },
      { emoji: "🔀", title: "সম্পূর্ণ reorder", description: "উপরে-নিচে বোতাম দিয়ে মার্জের আগে ক্রম বদলান।" },
      { emoji: "🎯", title: "পেজ-সঠিক কপি", description: "প্রতিটি পেজ byte-for-byte কপি হয়, কোনো কোয়ালিটি লস নেই।" },
      { emoji: "⚡", title: "দ্রুত প্রসেসিং", description: "২০টি ফাইলের মার্জ সাধারণত কয়েক সেকেন্ডে সম্পন্ন হয়।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ১০০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "কতটি PDF মার্জ করা যায়?", answer: "একবারে ২০টি পর্যন্ত। প্রতি ফাইল ১০০ MB পর্যন্ত।" },
      { question: "পেজ সংখ্যার লিমিট?", answer: "না। মোট সাইজ ও ফাইল সংখ্যার সীমার মধ্যে যত পেজ চান মার্জ করুন।" },
      { question: "PDF কোয়ালিটি কমবে?", answer: "না। পেজ re-rendering ছাড়াই byte-for-byte কপি হয়।" },
      { question: "পাসওয়ার্ড-প্রোটেক্টেড PDF মার্জ করা যায়?", answer: "Encrypted PDF লোড হবে না। আগে owner password দিয়ে decrypt করুন।" },
      { question: "মার্জড PDF split করা যায়?", answer: "এই টুলে না। Split PDF টুল ব্যবহার করুন।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার PDF pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও মার্জ করা হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type MergePdfContent = typeof mergePdfContent;
