export const pdfRotatorContent = {
  en: {
    heroTag: "PDF Rotator",
    heroSubtitle:
      "Rotate pages in any PDF — right in your browser. Rotate all pages or just a few, 90° left, 90° right, or 180°. Download a fresh PDF instantly. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "90°/180°", label: "Rotation" },
      { value: "100%", label: "Private" },
      { value: "Page ranges", label: "Supported" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "PDF never leaves your device." },
      { emoji: "🔄", title: "90° / 180°", text: "All common rotations supported." },
      { emoji: "🎯", title: "Selective pages", text: "Rotate only the pages you need." },
      { emoji: "👀", title: "Live preview", text: "See the rotation as you apply it." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
      { emoji: "⚡", title: "Instant output", text: "New PDF ready in milliseconds." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "PDF Rotator changes the rotation of pages inside your PDF. Every PDF page carries a rotation value (0°, 90°, 180°, or 270°), telling readers which way to display it. This tool adjusts those values — rotating selected pages 90° clockwise, 90° counter-clockwise, or 180° — and saves a new PDF with the updated orientation." },
      { emoji: "📄", title: "When you need it", text: "Scanned documents often come out sideways. Phone photos of receipts sometimes land in landscape. Printers and scanners occasionally ignore page rotation metadata. If a PDF opens wrong in one app but right in another, rotating the pages to a fixed orientation solves it once and for all." },
      { emoji: "⚡", title: "How the rotation works", text: "The tool loads your PDF with pdf-lib, walks through each selected page, adds the chosen angle to its existing rotation, normalizes the result to 0/90/180/270, and rebuilds the file. Content is never re-rendered — only rotation metadata changes, so file size stays nearly identical and nothing is re-compressed." },
      { emoji: "🔐", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs in your browser using JavaScript and pdf-lib. When you close the tab, every trace of your PDF is gone from memory." },
    ],
    howToTitle: "How to rotate PDF pages",
    howTo: [
      { step: 1, title: "Drop your PDF", description: "Drag a PDF into the upload area, or click to browse. Up to 100 MB." },
      { step: 2, title: "Choose pages", description: "Rotate all pages, or enter specific page ranges like 1-3, 5, 7-9." },
      { step: 3, title: "Pick a rotation", description: "Rotate 90° left (counter-clockwise), 90° right (clockwise), or 180° (upside down)." },
      { step: 4, title: "Download", description: "Click Rotate & Download. Your new PDF is saved instantly." },
    ],
    featuresTitle: "Built for real PDFs",
    features: [
      { emoji: "🔄", title: "All common rotations", description: "90° left, 90° right, and 180° — the three you actually need." },
      { emoji: "🎯", title: "Selective pages", description: "Rotate all pages, or target specific ranges like 1-3, 5, 7-9." },
      { emoji: "🔒", title: "Zero uploads", description: "PDF parsing and saving happen entirely in your browser." },
      { emoji: "⚡", title: "Fast & lossless", description: "Only rotation metadata changes — nothing re-rendered or re-compressed." },
      { emoji: "📄", title: "Any size", description: "Up to 100 MB per PDF. No signup, no watermark." },
      { emoji: "📱", title: "Works everywhere", description: "Responsive layout — rotate PDFs on desktop, tablet, or phone." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my PDF uploaded?", answer: "No. Everything happens inside your browser using pdf-lib. Your file never leaves your device." },
      { question: "What's the difference between 90° left and 90° right?", answer: "90° left = counter-clockwise rotation (text moves from top to left). 90° right = clockwise rotation (text moves from top to right). Pick whichever makes your content upright." },
      { question: "Does rotating hurt quality?", answer: "No. Only the rotation metadata changes — the actual content bytes are untouched. File size stays nearly identical and nothing is re-compressed or re-rendered." },
      { question: "Can I rotate just one page?", answer: "Yes. Enter the page number (e.g. 3) or a range (e.g. 1-2, 5) in the page field, then choose a rotation." },
      { question: "Why does my PDF open correctly in one app but not another?", answer: "Some apps ignore PDF rotation metadata and display pages at 0°. Rotating the pages physically fixes the metadata so every reader agrees." },
      { question: "Can I undo a rotation?", answer: "Yes — just open the rotated PDF again and apply the opposite rotation (90° left cancels 90° right)." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your PDF is loaded, modified, and saved entirely inside your browser using pdf-lib. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF রোটেটর",
    heroSubtitle:
      "যেকোনো PDF-এর পেজ ঘোরান — সম্পূর্ণ আপনার ব্রাউজারেই। সব পেজ বা কয়েকটি, 90° বামে, 90° ডানে, বা 180° — যেকোনো ঘোরানো যাবে। সাথে সাথে নতুন PDF ডাউনলোড করুন।",
    heroStats: [
      { value: "90°/180°", label: "রোটেশন" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "পেজ রেঞ্জ", label: "সাপোর্টেড" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "PDF কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🔄", title: "৯০° / ১৮০°", text: "সব সাধারণ রোটেশন সাপোর্টেড।" },
      { emoji: "🎯", title: "নির্দিষ্ট পেজ", text: "শুধু যেসব পেজ দরকার সেগুলো ঘোরান।" },
      { emoji: "👀", title: "লাইভ প্রিভিউ", text: "যেভাবে ঘুরছে সাথে সাথে দেখুন।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি।" },
      { emoji: "⚡", title: "তাৎক্ষণিক আউটপুট", text: "নতুন PDF মিলিসেকেন্ডে তৈরি।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "PDF Rotator আপনার PDF-এর ভেতরের পেজের rotation value বদলায়। প্রতিটি PDF পেজে একটি rotation value থাকে (0°, 90°, 180°, বা 270°) — যা reader-দের বলে দেয় কোন দিকে display করতে হবে। এই টুল সেই value পরিবর্তন করে — নির্বাচিত পেজ 90° clockwise, 90° counter-clockwise, বা 180° ঘোরায় — এবং নতুন orientation সহ একটি নতুন PDF সেভ করে।" },
      { emoji: "📄", title: "কখন দরকার", text: "স্ক্যান করা ডকুমেন্ট অনেক সময় কাত হয়ে যায়। রিসিটের ছবি কখনো landscape-এ পড়ে। Printer ও scanner মাঝে মাঝে rotation metadata এড়িয়ে যায়। যদি একটি PDF একটি অ্যাপে ঠিক দেখায় কিন্তু অন্যটায় ভুল — পেজ rotate করে fixed orientation দিলে সমস্যা একবারে মিটে যায়।" },
      { emoji: "⚡", title: "রোটেশন কীভাবে কাজ করে", text: "টুলটি pdf-lib দিয়ে PDF লোড করে, প্রতিটি নির্বাচিত পেজে যায়, বিদ্যমান rotation-এ নির্বাচিত angle যোগ করে, ফলাফল 0/90/180/270-এ normalize করে, এবং ফাইলটি পুনর্গঠন করে। Content কখনো re-render হয় না — শুধু rotation metadata বদলায়, তাই ফাইল সাইজ প্রায় একই থাকে এবং কিছুই re-compress হয় না।" },
      { emoji: "🔐", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "PDF পেজ কীভাবে ঘোরাবেন",
    howTo: [
      { step: 1, title: "PDF দিন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ১০০ MB পর্যন্ত।" },
      { step: 2, title: "পেজ বাছুন", description: "সব পেজ ঘোরান, অথবা নির্দিষ্ট পেজ রেঞ্জ লিখুন: 1-3, 5, 7-9।" },
      { step: 3, title: "রোটেশন বাছুন", description: "90° বামে (counter-clockwise), 90° ডানে (clockwise), বা 180° (উল্টো)।" },
      { step: 4, title: "ডাউনলোড", description: "Rotate & Download চাপুন। নতুন PDF সাথে সাথে সেভ হবে।" },
    ],
    featuresTitle: "প্রকৃত PDF-এর জন্য তৈরি",
    features: [
      { emoji: "🔄", title: "সব সাধারণ রোটেশন", description: "90° বাম, 90° ডান, এবং 180° — যেগুলো সত্যিই দরকার।" },
      { emoji: "🎯", title: "নির্দিষ্ট পেজ", description: "সব পেজ, বা নির্দিষ্ট রেঞ্জ: 1-3, 5, 7-9।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "PDF parse ও save সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "⚡", title: "দ্রুত ও lossless", description: "শুধু rotation metadata বদলায় — কিছু re-render বা re-compress হয় না।" },
      { emoji: "📄", title: "যেকোনো সাইজ", description: "প্রতি PDF-এ ১০০ MB পর্যন্ত।" },
      { emoji: "📱", title: "সবখানে কাজ করে", description: "Desktop, tablet, phone — responsive।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "৯০° বাম আর ৯০° ডান-এর পার্থক্য কী?", answer: "90° বাম = counter-clockwise (উপর থেকে বামে যায়)। 90° ডান = clockwise (উপর থেকে ডানে যায়)। যেটায় content সোজা হয় সেটা বেছে নিন।" },
      { question: "ঘোরালে কোয়ালিটি নষ্ট হয়?", answer: "না। শুধু rotation metadata বদলায় — actual content byte অপরিবর্তিত। ফাইল সাইজ প্রায় একই থাকে, কিছু re-compress বা re-render হয় না।" },
      { question: "শুধু একটা পেজ ঘোরানো যায়?", answer: "হ্যাঁ। Page field-এ পেজ নম্বর (যেমন 3) বা range (যেমন 1-2, 5) লিখুন।" },
      { question: "একটা অ্যাপে ঠিক দেখায়, অন্যটায় ভুল কেন?", answer: "কিছু অ্যাপ PDF rotation metadata এড়িয়ে 0°-তে display করে। পেজ physically rotate করলে metadata ফিক্স হয়, সব reader একমত হয়।" },
      { question: "রোটেশন undo করা যায়?", answer: "হ্যাঁ — আবার PDF খুলে উল্টো rotation দিন (90° বাম 90° ডান-কে cancel করে)।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari ও Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার PDF pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই load, modify ও save হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type PdfRotatorContent = typeof pdfRotatorContent;
