export const jpgToPdfContent = {
  en: {
    heroTag: "JPG to PDF",
    heroSubtitle:
      "Combine JPG images into a single PDF document right in your browser. Drag, reorder, pick A4 or Letter, set orientation and margins, and download — no uploads, no servers, no accounts.",
    heroStats: [
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Supported" },
      { value: "A4/Letter", label: "Page size" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "Files never leave your device." },
      { emoji: "⚡", title: "Instant PDF", text: "Runs in your browser." },
      { emoji: "📄", title: "Multi-page", text: "Combine dozens of JPGs into one PDF." },
      { emoji: "🔀", title: "Reorder pages", text: "Drag to change the order before export." },
      { emoji: "📐", title: "A4 & Letter", text: "Portrait or landscape — your choice." },
      { emoji: "💾", title: "No uploads", text: "Everything happens locally." },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "What this tool does", text: "JPG to PDF Converter turns one or many JPG photos into a clean, multi-page PDF. Drop your images, drag to reorder, choose A4 or US Letter (portrait or landscape), set page margins, and click Export. Everything is encoded using pdf-lib, a pure-JavaScript library that runs entirely inside your browser." },
      { emoji: "📄", icon: "target", title: "When you need it", text: "Scanned documents? Photos of receipts? A portfolio of screenshots? Combining JPGs into a single PDF is the cleanest way to share them. PDFs preserve page order, embed the images at full resolution, and open reliably on every device — unlike folders of loose JPGs." },
      { emoji: "⚡", icon: "printer", title: "How the conversion works", text: "Each JPG is read locally, decoded, and embedded directly into the PDF file without re-compression — so every pixel from the original JPG is preserved. The PDF itself is built in memory and only written to a Blob when you click Download. No network requests are involved at any point." },
      { emoji: "🔐", icon: "lock", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. The entire tool runs as JavaScript in your browser. When you close the tab, every trace of your images is gone from memory." },
    ],
    howToTitle: "How to convert JPG to PDF",
    howTo: [
      { step: 1, title: "Drop your JPG files", description: "Drag JPG or JPEG files into the upload area, or click to browse. Up to 50 MB per file and up to 50 pages per PDF." },
      { step: 2, title: "Reorder pages", description: "Drag the page thumbnails to change the order. Move up, move down, or delete individual pages." },
      { step: 3, title: "Configure the PDF", description: "Choose page size (auto, A4, or Letter), orientation (portrait, landscape, or auto), and page margin." },
      { step: 4, title: "Export and download", description: "Click Export PDF. The file is built in your browser and downloaded instantly — no uploads involved." },
    ],
    featuresTitle: "Built for real PDFs",
    features: [
      { emoji: "🔒", title: "Zero uploads", description: "Images are read and embedded locally. Nothing travels over the network." },
      { emoji: "📄", title: "Up to 50 pages", description: "Combine dozens of JPGs into a single multi-page PDF document." },
      { emoji: "🔀", title: "Full reordering", description: "Drag thumbnails to reorder pages. Remove or duplicate individual entries." },
      { emoji: "📐", title: "A4 & US Letter", description: "Standard page sizes with portrait, landscape, or auto orientation." },
      { emoji: "🎯", title: "Full-resolution embedding", description: "Images are embedded without re-compression — every pixel preserved." },
      { emoji: "💾", title: "No size limits", description: "Files up to 50 MB each. No signup, no watermark, no daily quota." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden size limit." },
      { question: "Do my files get uploaded to a server?", answer: "No. Everything happens inside your browser using pdf-lib. Your files never leave your device." },
      { question: "What page sizes are supported?", answer: "Auto (matches each image's own size), A4 (210×297 mm), and US Letter (216×279 mm). Orientation can be portrait, landscape, or auto-detect." },
      { question: "How many pages can I combine?", answer: "Up to 50 pages per PDF. If you need more, you can run the tool again." },
      { question: "Will the JPG quality drop?", answer: "No. Images are embedded without re-compression — the PDF contains the original JPEG data byte-for-byte." },
      { question: "Can I reorder pages?", answer: "Yes. Drag thumbnails or use the up/down arrows to reorder, and click X to remove individual pages." },
      { question: "Can I merge a PDF with new images?", answer: "Not with this tool. Use our Merge PDF tool for that." },
      { question: "Does it work on mobile?", answer: "Yes. The tool is fully responsive and works on iOS Safari and Android Chrome." },
    ],
    privacyNote: "Your images are read and embedded entirely inside your browser using pdf-lib. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "JPG থেকে PDF",
    heroSubtitle:
      "JPG ছবি একটি PDF ডকুমেন্টে যুক্ত করুন — সম্পূর্ণ আপনার ব্রাউজারেই। ড্র্যাগ করুন, ক্রম বদলান, A4 বা Letter বেছে নিন, orientation ও margin ঠিক করুন, এবং ডাউনলোড করুন।",
    heroStats: [
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "সাপোর্টেড" },
      { value: "A4/Letter", label: "পেজ সাইজ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "⚡", title: "তাৎক্ষণিক PDF", text: "ব্রাউজারেই চলে।" },
      { emoji: "📄", title: "মাল্টি-পেজ", text: "একাধিক JPG এক PDF-এ।" },
      { emoji: "🔀", title: "পেজ সাজান", text: "এক্সপোর্টের আগে ক্রম বদলান।" },
      { emoji: "📐", title: "A4 ও Letter", text: "Portrait বা landscape — আপনার পছন্দ।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সবকিছু লোকালি হয়।" },
    ],
    introBlocks: [
      { emoji: "🪄", icon: "sparkle", title: "এই টুল কী করে", text: "JPG থেকে PDF কনভার্টার এক বা একাধিক JPG ছবি থেকে পরিষ্কার multi-page PDF তৈরি করে। ছবি ড্রপ করুন, ক্রম বদলান, A4 বা Letter বেছে নিন, margin সেট করুন, এবং Export চাপুন। সবকিছু pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "📄", icon: "target", title: "কখন দরকার", text: "স্ক্যান করা ডকুমেন্ট? রিসিটের ছবি? স্ক্রিনশটের পোর্টফোলিও? JPG-গুলো এক PDF-এ যুক্ত করাই শেয়ার করার পরিচ্ছন্ন উপায়। PDF পেজ ক্রম সংরক্ষণ করে, full resolution-এ ছবি embed করে, এবং সব ডিভাইসে নির্ভরযোগ্যভাবে খোলে।" },
      { emoji: "⚡", icon: "printer", title: "কনভার্সন কীভাবে কাজ করে", text: "প্রতিটি JPG লোকালি পড়া হয়, ডিকোড করা হয়, এবং PDF-এ সরাসরি embed করা হয় কোনো re-compression ছাড়াই — মূল JPG-এর প্রতিটি পিক্সেল সংরক্ষিত থাকে।" },
      { emoji: "🔐", icon: "lock", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়।" },
    ],
    howToTitle: "JPG কীভাবে PDF-এ রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "JPG ফাইল দিন", description: "এক বা একাধিক JPG/JPEG ফাইল ড্র্যাগ করুন বা ক্লিক করুন। প্রতি ফাইল ৫০ MB পর্যন্ত, প্রতি PDF-এ ৫০ পেজ পর্যন্ত।" },
      { step: 2, title: "পেজ সাজান", description: "থাম্বনেইল ড্র্যাগ করে ক্রম বদলান। উপরে-নিচে সরান বা আলাদা পেজ মুছুন।" },
      { step: 3, title: "PDF কনফিগার করুন", description: "পেজ সাইজ (auto, A4, Letter), orientation (portrait, landscape, auto), এবং margin বেছে নিন।" },
      { step: 4, title: "Export করুন", description: "Export PDF চাপুন। ফাইল আপনার ব্রাউজারেই তৈরি হয় ও সাথে সাথে ডাউনলোড হয়।" },
    ],
    featuresTitle: "প্রকৃত PDF-এর জন্য তৈরি",
    features: [
      { emoji: "🔒", title: "শূন্য আপলোড", description: "ছবি লোকালি পড়া ও embed করা হয়।" },
      { emoji: "📄", title: "৫০ পেজ পর্যন্ত", description: "একাধিক JPG এক multi-page PDF-এ যুক্ত করুন।" },
      { emoji: "🔀", title: "সম্পূর্ণ reorder", description: "থাম্বনেইল ড্র্যাগ করে ক্রম বদলান।" },
      { emoji: "📐", title: "A4 ও Letter", description: "portrait, landscape বা auto orientation সহ স্ট্যান্ডার্ড পেজ সাইজ।" },
      { emoji: "🎯", title: "ফুল-রেজোলিউশন embed", description: "re-compression ছাড়াই ছবি embed — প্রতিটি পিক্সেল সংরক্ষিত।" },
      { emoji: "💾", title: "সাইজ লিমিট নেই", description: "প্রতি ফাইল ৫০ MB পর্যন্ত।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার ফাইল কি আপলোড হয়?", answer: "না। pdf-lib দিয়ে সবকিছু আপনার ব্রাউজারেই হয়।" },
      { question: "কোন পেজ সাইজ সাপোর্টেড?", answer: "Auto (প্রতিটি ছবির নিজের মাপ), A4 (২১০×২৯৭ মিমি), এবং Letter (২১৬×২৭৯ মিমি)।" },
      { question: "কত পেজ যুক্ত করা যায়?", answer: "প্রতি PDF-এ ৫০ পেজ পর্যন্ত।" },
      { question: "JPG কোয়ালিটি কমবে?", answer: "না। re-compression ছাড়াই ছবি embed হয় — মূল JPG ডেটা হুবহু থাকে।" },
      { question: "পেজ ক্রম বদলানো যায়?", answer: "হ্যাঁ। থাম্বনেইল ড্র্যাগ করুন বা উপরে-নিচে সরান।" },
      { question: "PDF-এর সাথে নতুন ছবি merge করা যায়?", answer: "এই টুলে না। Merge PDF টুল ব্যবহার করুন।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। iOS Safari এবং Android Chrome-এ কাজ করে।" },
    ],
    privacyNote: "আপনার ছবি pdf-lib দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই পড়া ও embed করা হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type JpgToPdfContent = typeof jpgToPdfContent;
