export const pdfToPngContent = {
  en: {
    heroTag: "PDF to PNG",
    heroSubtitle:
      "Convert every page of your PDF into a high-quality PNG image — right in your browser. Choose pages, pick 72/150/300 DPI, download single files or all at once. No uploads, no servers, no accounts.",
    heroStats: [
      { value: "300 DPI", label: "Max quality" },
      { value: "100%", label: "Private" },
      { value: "Batch", label: "Pages" },
      { value: "Free", label: "Forever" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "100% private", text: "PDF never leaves your device." },
      { emoji: "🎨", title: "Up to 300 DPI", text: "Sharp, print-ready PNGs." },
      { emoji: "📄", title: "Any PDF", text: "Multiple pages in one batch." },
      { emoji: "🎯", title: "Page ranges", text: "Pick exactly which pages to export." },
      { emoji: "💾", title: "No uploads", text: "Rendering happens locally." },
      { emoji: "🌐", title: "Lossless PNG", text: "No JPEG artifacts, no re-compression." },
    ],
    introBlocks: [
      { emoji: "🪄", title: "What this tool does", text: "PDF to PNG renders each page of your PDF as a standalone PNG image. You pick a DPI (72 for screen, 150 for web, 300 for print), choose specific page ranges or all pages, and download. The entire rendering pipeline — PDF parsing, canvas drawing, and PNG encoding — runs inside your browser using pdf.js." },
      { emoji: "📄", title: "When you need it", text: "Turn slide decks into shareable images, extract charts from reports, generate thumbnails for a document viewer, or convert scanned forms into images that can be embedded anywhere. PNG is lossless, so nothing degrades — perfect for graphics, screenshots of text, or anything with sharp edges." },
      { emoji: "⚡", title: "How the conversion works", text: "PDF.js parses the file, renders each page onto an off-screen canvas at the scale you picked, and the browser encodes the canvas as PNG. At 300 DPI, an A4 page becomes roughly 2480×3508 pixels — ideal for print. Nothing is uploaded at any point." },
      { emoji: "🔐", title: "Your files stay with you", text: "There is no server. No accounts. No analytics. Close the tab and everything disappears from memory. Your PDFs — contracts, IDs, medical records — never touch a network." },
    ],
    howToTitle: "How to convert PDF to PNG",
    howTo: [
      { step: 1, title: "Drop your PDF", description: "Drag a PDF file into the upload area, or click to browse. Up to 100 MB." },
      { step: 2, title: "Pick pages and DPI", description: "Choose specific page ranges (e.g. 1-3, 5) or all pages, and select 72, 150, or 300 DPI." },
      { step: 3, title: "Convert", description: "Click Convert. Each page is rendered in your browser and encoded as a PNG." },
      { step: 4, title: "Download", description: "Download each PNG individually, or click Download all to save them in order." },
    ],
    featuresTitle: "Built for real PDFs",
    features: [
      { emoji: "🎨", title: "Up to 300 DPI", description: "Print-ready output — 300 DPI on A4 is ~2480×3508 pixels." },
      { emoji: "🔒", title: "Zero uploads", description: "PDF parsing and rendering happen entirely in your browser." },
      { emoji: "🎯", title: "Page ranges", description: "Extract just what you need: 1-3, 5, 7-9 — or everything." },
      { emoji: "🌐", title: "Lossless PNG", description: "No JPEG artifacts. Sharp text, crisp edges." },
      { emoji: "📄", title: "Any size", description: "Up to 100 MB per PDF. No signup, no watermark." },
      { emoji: "⚡", title: "Fast", description: "Web Workers keep the UI smooth even on large files." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { question: "Is this really free?", answer: "Yes — completely. No account, no watermark, no hidden limits." },
      { question: "Is my PDF uploaded?", answer: "No. Everything happens inside your browser using pdf.js. Your file never leaves your device." },
      { question: "What does DPI mean here?", answer: "DPI controls the output resolution. 72 DPI is 1:1 with PDF points (screen size), 150 DPI is 2x for web, and 300 DPI is 4x — the standard for print." },
      { question: "How big will the PNGs be?", answer: "At 300 DPI, an A4 page is roughly 2480×3508 pixels. File sizes vary by content — text-heavy pages compress well, photo-heavy pages are larger." },
      { question: "Can I convert just a few pages?", answer: "Yes. Enter ranges like 1-3, 5, 7-9 in the page field, or leave it empty to convert every page." },
      { question: "Does it work on encrypted PDFs?", answer: "Password-protected PDFs can't be opened without the password. Encrypted-but-openable PDFs (owner password only) usually work." },
      { question: "Will the PNG keep transparency?", answer: "PDF pages are composited onto a solid white background — PDFs don't have transparency, so this matches what you see on screen." },
      { question: "Does it work on mobile?", answer: "Yes. Large PDFs may take longer on phones, but the tool is fully responsive." },
    ],
    privacyNote: "Your PDF is parsed and rendered entirely inside your browser using pdf.js. Nothing is uploaded, tracked, or stored on any server. Close the tab and everything disappears.",
    relatedTitle: "Other tools you may like",
  },
  bn: {
    heroTag: "PDF থেকে PNG",
    heroSubtitle:
      "আপনার PDF-এর প্রতিটি পেজ উচ্চ-মানের PNG ছবিতে রূপান্তর করুন — সম্পূর্ণ আপনার ব্রাউজারেই। পেজ বেছে নিন, 72/150/300 DPI ঠিক করুন, এক বা সব ফাইল ডাউনলোড করুন।",
    heroStats: [
      { value: "300 DPI", label: "সর্বোচ্চ কোয়ালিটি" },
      { value: "১০০%", label: "প্রাইভেট" },
      { value: "ব্যাচ", label: "পেজ" },
      { value: "ফ্রি", label: "চিরকাল" },
    ],
    introHighlights: [
      { emoji: "🔒", title: "১০০% প্রাইভেট", text: "PDF কখনো ডিভাইস ছাড়ে না।" },
      { emoji: "🎨", title: "৩০০ DPI পর্যন্ত", text: "প্রিন্ট-রেডি, শার্প PNG।" },
      { emoji: "📄", title: "যেকোনো PDF", text: "একাধিক পেজ এক ব্যাচে।" },
      { emoji: "🎯", title: "পেজ রেঞ্জ", text: "কোন পেজ লাগবে ঠিক তা বেছে নিন।" },
      { emoji: "💾", title: "শূন্য আপলোড", text: "সব রেন্ডারিং লোকালি।" },
      { emoji: "🌐", title: "Lossless PNG", text: "JPEG artifact নেই, re-compression নেই।" },
    ],
    introBlocks: [
      { emoji: "🪄", title: "এই টুল কী করে", text: "PDF to PNG আপনার PDF-এর প্রতিটি পেজ আলাদা PNG ছবি হিসেবে রেন্ডার করে। DPI বেছে নিন (screen-এর জন্য 72, web-এর জন্য 150, print-এর জন্য 300), পেজ রেঞ্জ বা সব পেজ ঠিক করুন, এবং ডাউনলোড করুন। সম্পূর্ণ প্রক্রিয়া pdf.js দিয়ে আপনার ব্রাউজারেই।" },
      { emoji: "📄", title: "কখন দরকার", text: "স্লাইড ডেককে ছবিতে বানানো, রিপোর্ট থেকে চার্ট বের করা, ডকুমেন্ট ভিউয়ারের জন্য thumbnail, বা স্ক্যান করা ফর্ম ছবিতে রূপান্তর — সবের জন্য। PNG lossless, তাই কিছু নষ্ট হয় না।" },
      { emoji: "⚡", title: "কনভার্সন কীভাবে কাজ করে", text: "PDF.js ফাইল parse করে, প্রতিটি পেজ আপনার বেছে নেওয়া scale-এ off-screen canvas-এ render করে, এবং ব্রাউজার canvas-টিকে PNG হিসেবে encode করে। 300 DPI-তে A4 পেজ প্রায় 2480×3508 পিক্সেল — print-এর জন্য আদর্শ।" },
      { emoji: "🔐", title: "আপনার ফাইল আপনার সাথেই থাকে", text: "কোনো সার্ভার নেই। কোনো অ্যাকাউন্ট নেই। কোনো অ্যানালিটিক্স নেই। ট্যাব বন্ধ করলেই সব চলে যায়। আপনার PDF — চুক্তি, আইডি, মেডিক্যাল রেকর্ড — কখনো নেটওয়ার্ক ছোঁয় না।" },
    ],
    howToTitle: "PDF কীভাবে PNG-তে রূপান্তর করবেন",
    howTo: [
      { step: 1, title: "PDF দিন", description: "PDF ফাইল ড্র্যাগ করুন বা ক্লিক করুন। ১০০ MB পর্যন্ত।" },
      { step: 2, title: "পেজ ও DPI বাছুন", description: "নির্দিষ্ট পেজ রেঞ্জ (যেমন 1-3, 5) বা সব পেজ বেছে নিন, এবং 72, 150, বা 300 DPI সিলেক্ট করুন।" },
      { step: 3, title: "Convert করুন", description: "Convert চাপুন। প্রতিটি পেজ আপনার ব্রাউজারেই PNG হিসেবে encode হয়।" },
      { step: 4, title: "ডাউনলোড করুন", description: "প্রতিটি PNG আলাদা ডাউনলোড করুন বা Download all চাপুন।" },
    ],
    featuresTitle: "প্রকৃত PDF-এর জন্য তৈরি",
    features: [
      { emoji: "🎨", title: "৩০০ DPI পর্যন্ত", description: "Print-ready আউটপুট — 300 DPI-তে A4 পেজ ~২৪৮০×৩৫০৮ পিক্সেল।" },
      { emoji: "🔒", title: "শূন্য আপলোড", description: "PDF parse ও render সম্পূর্ণ আপনার ব্রাউজারেই।" },
      { emoji: "🎯", title: "পেজ রেঞ্জ", description: "যা দরকার তাই: 1-3, 5, 7-9 — বা সব।" },
      { emoji: "🌐", title: "Lossless PNG", description: "JPEG artifact নেই। শার্প text, স্পষ্ট edge।" },
      { emoji: "📄", title: "যেকোনো সাইজ", description: "প্রতি PDF-এ ১০০ MB পর্যন্ত।" },
      { emoji: "⚡", title: "দ্রুত", description: "Web Worker-এ বড় ফাইলেও UI স্মুথ।" },
    ],
    faqTitle: "মানুষ যা জিজ্ঞেস করে",
    faq: [
      { question: "এটা কি সত্যিই ফ্রি?", answer: "হ্যাঁ — সম্পূর্ণ ফ্রি। কোনো অ্যাকাউন্ট নেই, ওয়াটারমার্ক নেই।" },
      { question: "আমার PDF কি আপলোড হয়?", answer: "না। pdf.js দিয়ে সবকিছু আপনার ব্রাউজারেই। ফাইল কখনো ডিভাইস ছাড়ে না।" },
      { question: "DPI মানে কী?", answer: "DPI আউটপুট resolution নিয়ন্ত্রণ করে। 72 DPI = PDF পয়েন্টের সাথে ১:১ (screen), 150 DPI = 2x (web), 300 DPI = 4x — print-এর স্ট্যান্ডার্ড।" },
      { question: "PNG কত বড় হবে?", answer: "300 DPI-তে A4 পেজ প্রায় ২৪৮০×৩৫০৮ পিক্সেল। ফাইল সাইজ content-এর উপর নির্ভর করে।" },
      { question: "শুধু কয়েকটা পেজ করা যায়?", answer: "হ্যাঁ। Page field-এ 1-3, 5, 7-9 লিখুন, বা খালি রাখলে সব পেজ।" },
      { question: "Encrypted PDF-এ কাজ করে?", answer: "Password-protected PDF খুলতে password লাগবে। Owner-password-only PDF সাধারণত কাজ করে।" },
      { question: "PNG transparency রাখবে?", answer: "PDF পেজ সলিড সাদা ব্যাকগ্রাউন্ডে composite হয় — PDF-এ transparency নেই।" },
      { question: "মোবাইলে কাজ করে?", answer: "হ্যাঁ। বড় PDF-এ ফোনে কিছুটা সময় লাগতে পারে, তবে fully responsive।" },
    ],
    privacyNote: "আপনার PDF pdf.js দিয়ে সম্পূর্ণ আপনার ব্রাউজারেই parse ও render হয়। কোনো কিছু আপলোড, ট্র্যাক বা সংরক্ষণ করা হয় না।",
    relatedTitle: "অন্যান্য টুলস",
  },
};

export type PdfToPngContent = typeof pdfToPngContent;
